/datum/centcom_announcer/intern
	welcome_sounds = list(
		'modular_bandastation/announcers/sound/welcome/Welcome_1_fucked.ogg',
		'modular_bandastation/announcers/sound/welcome/Welcome_1.ogg',
		'modular_bandastation/announcers/sound/welcome/Welcome_2.ogg',
		'modular_bandastation/announcers/sound/welcome/Welcome_3.ogg',
		'modular_bandastation/announcers/sound/welcome/Welcome_4.ogg',
		'modular_bandastation/announcers/sound/welcome/Welcome_5.ogg',
		'modular_bandastation/announcers/sound/welcome/Welcome_6.ogg'
		)

	alert_sounds = list(
		'modular_bandastation/announcers/sound/alerts/1.ogg',
		'modular_bandastation/announcers/sound/alerts/2.ogg',
		'modular_bandastation/announcers/sound/alerts/3.ogg',
		'modular_bandastation/announcers/sound/alerts/4.ogg',
		'modular_bandastation/announcers/sound/alerts/5.ogg',
		'modular_bandastation/announcers/sound/alerts/6.ogg',
		'modular_bandastation/announcers/sound/alerts/7.ogg',
		'modular_bandastation/announcers/sound/alerts/8.ogg',
		'modular_bandastation/announcers/sound/alerts/9.ogg',
		'modular_bandastation/announcers/sound/alerts/10.ogg',
		'modular_bandastation/announcers/sound/alerts/11.ogg',
		'modular_bandastation/announcers/sound/alerts/12.ogg',
		'modular_bandastation/announcers/sound/alerts/13.ogg',
		'modular_bandastation/announcers/sound/alerts/14.ogg',
		'modular_bandastation/announcers/sound/alerts/15.ogg',
		'modular_bandastation/announcers/sound/alerts/16.ogg',
		'modular_bandastation/announcers/sound/alerts/17.ogg',
		'modular_bandastation/announcers/sound/alerts/18.ogg',
		'modular_bandastation/announcers/sound/alerts/19.ogg',
		'modular_bandastation/announcers/sound/alerts/20.ogg',
		'modular_bandastation/announcers/sound/alerts/21.ogg',
		'modular_bandastation/announcers/sound/alerts/22.ogg',
		'modular_bandastation/announcers/sound/alerts/23.ogg',
		'modular_bandastation/announcers/sound/alerts/24.ogg',
		'modular_bandastation/announcers/sound/alerts/25.ogg',
		'modular_bandastation/announcers/sound/alerts/26.ogg',
		'modular_bandastation/announcers/sound/alerts/27.ogg',
		'modular_bandastation/announcers/sound/alerts/28.ogg',
		'modular_bandastation/announcers/sound/alerts/29.ogg',
		'modular_bandastation/announcers/sound/alerts/30.ogg',
		'modular_bandastation/announcers/sound/alerts/31.ogg',
		'modular_bandastation/announcers/sound/alerts/32.ogg',
		'modular_bandastation/announcers/sound/alerts/33.ogg',
		'modular_bandastation/announcers/sound/alerts/34.ogg',
		'modular_bandastation/announcers/sound/alerts/35.ogg',
		'modular_bandastation/announcers/sound/alerts/36.ogg',
		'modular_bandastation/announcers/sound/alerts/37.ogg',
		'modular_bandastation/announcers/sound/alerts/38.ogg',
		'modular_bandastation/announcers/sound/alerts/39.ogg',
		'modular_bandastation/announcers/sound/alerts/40.ogg',
		'modular_bandastation/announcers/sound/alerts/41.ogg',
		'modular_bandastation/announcers/sound/alerts/42.ogg',
		'modular_bandastation/announcers/sound/alerts/43.ogg',
		'modular_bandastation/announcers/sound/alerts/44.ogg',
		'modular_bandastation/announcers/sound/alerts/45.ogg',
		'modular_bandastation/announcers/sound/alerts/46.ogg',
		'modular_bandastation/announcers/sound/alerts/47.ogg',
		'modular_bandastation/announcers/sound/alerts/48.ogg',
		'modular_bandastation/announcers/sound/alerts/49.ogg',
		'modular_bandastation/announcers/sound/alerts/50.ogg',
		'modular_bandastation/announcers/sound/alerts/51.ogg',
		'modular_bandastation/announcers/sound/alerts/52.ogg',
		'modular_bandastation/announcers/sound/alerts/53.ogg',
		'modular_bandastation/announcers/sound/alerts/54.ogg'
		)

	command_report_sounds = list(
		'modular_bandastation/announcers/sound/commandreport/1.ogg',
		'modular_bandastation/announcers/sound/commandreport/2.ogg',
		'modular_bandastation/announcers/sound/commandreport/3.ogg',
		'modular_bandastation/announcers/sound/commandreport/4.ogg',
		'modular_bandastation/announcers/sound/commandreport/5.ogg',
		'modular_bandastation/announcers/sound/commandreport/6.ogg',
		'modular_bandastation/announcers/sound/commandreport/7.ogg',
		'modular_bandastation/announcers/sound/commandreport/8.ogg',
		'modular_bandastation/announcers/sound/commandreport/9.ogg',
		'modular_bandastation/announcers/sound/commandreport/10.ogg',
		'modular_bandastation/announcers/sound/commandreport/11.ogg',
		'modular_bandastation/announcers/sound/commandreport/commandreport_beer.ogg',
		'modular_bandastation/announcers/sound/commandreport/commandreport_sleep.ogg'
		)

	event_sounds = list(ANNOUNCER_AIMALF = 'sound/announcer/default/aimalf.ogg',
		ANNOUNCER_ALIENS = 'modular_bandastation/announcers/sound/events/aliens.ogg',
		ANNOUNCER_ANIMES = 'modular_bandastation/announcers/sound/events/animes.ogg',
		ANNOUNCER_GRANOMALIES = 'modular_bandastation/announcers/sound/events/granomalies.ogg',
		ANNOUNCER_INTERCEPT = 'modular_bandastation/announcers/sound/events/intercept.ogg',
		ANNOUNCER_IONSTORM = 'modular_bandastation/announcers/sound/events/ionstorm.ogg',
		ANNOUNCER_METEORS = 'modular_bandastation/announcers/sound/events/meteors.ogg',
		ANNOUNCER_OUTBREAK5 = 'modular_bandastation/announcers/sound/events/outbreak5.ogg',
		ANNOUNCER_OUTBREAK7 = 'modular_bandastation/announcers/sound/events/outbreak7.ogg',
		ANNOUNCER_POWEROFF = 'modular_bandastation/announcers/sound/events/poweroff.ogg',
		ANNOUNCER_POWERON = 'modular_bandastation/announcers/sound/events/poweron.ogg',
		ANNOUNCER_RADIATION = 'modular_bandastation/announcers/sound/events/radiation.ogg',
		ANNOUNCER_SHUTTLECALLED = 'modular_bandastation/announcers/sound/events/shuttlecalled.ogg',
		ANNOUNCER_SHUTTLEDOCK = 'modular_bandastation/announcers/sound/events/shuttledock.ogg',
		ANNOUNCER_SHUTTLERECALLED = 'modular_bandastation/announcers/sound/events/shuttlerecalled.ogg',
		ANNOUNCER_SPANOMALIES = 'modular_bandastation/announcers/sound/events/spanomalies.ogg')

	custom_alert_message = span_alert("Пожалуйста, ожидайте важного сообщения от нашего нового стажера.<br>")
