#define CATEGORY_CLIENT "Клиент"
#define CATEGORY_EMOTE "Эмоции"
#define CATEGORY_ADMIN "Админ"
#define CATEGORY_XENO "Ксено"
#define CATEGORY_CARBON "Гуманоиды"
#define CATEGORY_HUMAN "Люди"
#define CATEGORY_ROBOT "Роботы"
#define CATEGORY_AI "ИИ"
#define CATEGORY_MISC "Прочее"
#define CATEGORY_MOVEMENT "Передвижение"
#define CATEGORY_COMMUNICATION "Общение"

#define WEIGHT_HIGHEST 0
#define WEIGHT_ADMIN 10
#define WEIGHT_CLIENT 20
#define WEIGHT_ROBOT 30
#define WEIGHT_MOB 40
#define WEIGHT_LIVING 50
#define WEIGHT_DEAD 60
#define WEIGHT_EMOTE 70
#define WEIGHT_AI 80
#define WEIGHT_LOWEST 999
