GLOBAL_LIST_INIT(jobs, world.file2list("massmeta/strings/names/jobs.txt"))
GLOBAL_LIST_INIT(cocktails, world.file2list("massmeta/strings/names/cocktails.txt"))
GLOBAL_LIST_INIT(locations, world.file2list("massmeta/strings/names/locations.txt"))
GLOBAL_LIST_INIT(ru_nouns, world.file2list("massmeta/strings/names/ru_nouns.txt"))
GLOBAL_LIST_INIT(ru_adjectives, world.file2list("massmeta/strings/names/ru_adjectives.txt"))
GLOBAL_LIST_INIT(ru_verbs, world.file2list("massmeta/strings/names/ru_verbs.txt"))
