/obj/effect/flotsam
	name = "flotsam"
	desc = "Treasure!"
	icon = 'icons/obj/flotsam.dmi'
	icon_state = "flotsam"
	anchored = TRUE
	layer = HIGH_OBJ_LAYER
	var/open_sound = 'sound/machines/closet/wooden_closet_open.ogg'
	var/open_sound_volume = 35

// /obj/effect/flotsam/attackby(obj/item/W, mob/user, list/modifiers, list/attack_modifiers)
// 	if(user && Adjacent(user))
// 		get_loot()
// 		return TRUE

/obj/effect/flotsam/attack_hand(mob/user, list/modifiers)
	. = ..()
	if(.)
		return
	if(Adjacent(user))
		get_loot()

/obj/effect/flotsam/attack_robot(mob/living/user)
	if(Adjacent(user))
		get_loot()

// /obj/effect/flotsam/attack_ghost(mob/dead/observer/ghost)
// 	return

/obj/effect/flotsam/proc/get_loot()
	var/loot = rand(1,100) //100 different crates with varying chances of spawning
	switch(loot)
		if(1 to 5) //5% chance
			new /obj/item/reagent_containers/cup/glass/bottle/rum(src.loc)
			new /obj/item/reagent_containers/cup/glass/bottle/whiskey(src.loc)
			new /obj/item/reagent_containers/cup/glass/bottle/whiskey(src.loc)
			new /obj/item/lighter(src.loc)
			new /obj/item/reagent_containers/cup/glass/bottle/absinthe/premium(src.loc)
			for(var/i in 1 to 3)
				new /obj/item/cigarette/rollie(src.loc)
		if(6 to 10)
			new /mob/living/basic/lightgeist(src.loc)
		if(11 to 15)
			new /mob/living/basic/bot/honkbot(src.loc)
		if(16 to 20)
			new /obj/item/stack/ore/diamond(src.loc, 10)
		if(21 to 25)
			for(var/i in 1 to 5)
				new /obj/item/poster/random_contraband(src.loc)
		if(26 to 30)
			new /obj/item/vending_refill/sovietsoda(src.loc)
			var/obj/item/circuitboard/machine/vendor/board = new (src.loc)
			board.set_type(/obj/machinery/vending/sovietsoda)
		if(31 to 35)
			new /obj/item/seeds/firelemon(src.loc)
		if(36 to 40)
			for(var/i in 1 to 5)
				new /obj/item/toy/snappop/phoenix(src.loc)
		if(41 to 45)
			new /obj/item/modular_computer/pda/clear(src.loc)
		if(46 to 50)
			new /obj/item/storage/box/syndie_kit/chameleon/broken
		if(51 to 52) // 2% chance
			new /obj/item/melee/baton(src.loc)
		if(53 to 54)
			new /obj/item/toy/balloon/corgi(src.loc)
		if(55 to 56)
			var/newitem = pick(subtypesof(/obj/item/toy/mecha))
			new newitem(src.loc)
		if(57 to 58)
			new /obj/item/toy/balloon/syndicate(src.loc)
		if(59 to 60)
			new /obj/item/borg/upgrade/modkit/aoe/mobs(src.loc)
			new /obj/item/clothing/suit/space(src.loc)
			new /obj/item/clothing/head/helmet/space(src.loc)
		if(61 to 62)
			for(var/i in 1 to 5)
				new /obj/item/clothing/head/costume/kitty(src.loc)
				new /obj/item/clothing/neck/petcollar(src.loc)
		if(63 to 64)
			new /obj/item/clothing/shoes/kindle_kicks(src.loc)
		if(65 to 66)
			new /obj/item/clothing/suit/costume/wellworn_shirt/graphic/ian(src.loc)
			new /obj/item/clothing/suit/hooded/ian_costume(src.loc)
		if(67 to 68)
			var/obj/item/gibtonite/free_bomb = new /obj/item/gibtonite(src.loc)
			free_bomb.quality = rand(GIBTONITE_QUALITY_LOW, GIBTONITE_QUALITY_HIGH)
			free_bomb.GibtoniteReaction(null, "A secure loot closet has spawned a live")
		if(69 to 70)
			new /obj/item/stack/ore/bluespace_crystal(src.loc, 5)
		if(71 to 72)
			new /obj/item/toy/plush/snakeplushie(src.loc)
		if(73 to 74)
			new /mob/living/basic/pet/gondola(src.loc)
		if(75 to 76)
			new /obj/item/bikehorn/airhorn(src.loc)
		if(77 to 78)
			new /obj/item/toy/plush/lizard_plushie(src.loc)
		if(79 to 80)
			new /obj/item/stack/sheet/mineral/bananium(src.loc, 10)
		if(81 to 82)
			new /obj/item/bikehorn/airhorn(src.loc)
		if(83 to 84)
			new /obj/item/toy/plush/beeplushie(src.loc)
		if(85 to 86)
			new /obj/item/defibrillator/compact(src.loc)
		if(87) //1% chance
			var/list/cannabis_seeds = typesof(/obj/item/seeds/cannabis)
			var/list/cannabis_plants = typesof(/obj/item/food/grown/cannabis)
			for(var/i in 1 to rand(2, 4))
				var/seed_type = pick(cannabis_seeds)
				new seed_type(src.loc)
			for(var/i in 1 to rand(2, 4))
				var/cannabis_type = pick(cannabis_plants)
				new cannabis_type(src.loc)
		if(88)
			new /obj/item/reagent_containers/cup/glass/bottle/lizardwine(src.loc)
		if(89)
			new /obj/item/melee/energy/sword/bananium(src.loc)
		if(90)
			new /obj/item/dnainjector/wackymut(src.loc)
		if(91)
			for(var/i in 1 to 30)
				new /mob/living/basic/cockroach/bloodroach(src.loc)
		if(92)
			new /obj/item/katana(src.loc)
		if(93)
			new /obj/item/dnainjector/xraymut(src.loc)
		if(94)
			new /mob/living/basic/mimic/crate(src.loc)
		if(95)
			new /obj/item/toy/plush/nukeplushie(src.loc)
		if(96)
			new /obj/item/banhammer(src.loc)
			for(var/i in 1 to 3)
				var/obj/effect/mine/sound/bwoink/mine = new (src.loc)
				mine.set_anchored(FALSE)
				mine.move_resist = MOVE_RESIST_DEFAULT
		if(97)
			for(var/i in 1 to 4)
				new /obj/item/clothing/mask/balaclava(src.loc)
			new /obj/item/gun/ballistic/shotgun/toy(src.loc)
			new /obj/item/gun/ballistic/automatic/pistol/toy(src.loc)
			new /obj/item/gun/ballistic/automatic/toy(src.loc)
			new /obj/item/gun/ballistic/automatic/l6_saw/toy/unrestricted(src.loc)
			new /obj/item/ammo_box/foambox(src.loc)
		if(98)
			for(var/i in 1 to 3)
				new /mob/living/basic/bee/toxin(src.loc)
		if(99)
			new /obj/item/implanter/sad_trombone(src.loc)
		if(100)
			new /obj/item/melee/skateboard/hoverboard(src.loc)
	playsound(loc, open_sound, open_sound_volume, TRUE, -3)
	qdel(src)
