/obj/machinery/rnd/production/techfab
	name = "technology fabricator"
	desc = "Produces researched prototypes with raw materials and energy."
	icon_state = "protolathe"
	circuit = /obj/item/circuitboard/machine/techfab
	categories = list(
		CATEGORY_POWER_DESIGNS,
		CATEGORY_MEDICAL_DESIGNS,
		CATEGORY_BLUESPACE_DESIGNS,
		CATEGORY_STOCK_PARTS,
		CATEGORY_EQUIPMENT,
		CATEGORY_TOOL_DESIGNS,
		CATEGORY_MINING_DESIGNS,
		CATEGORY_ELECTRONICS,
		CATEGORY_WEAPONS,
		CATEGORY_AMMO,
		CATEGORY_FIRING_PINS,
		CATEGORY_COMPUTER_PARTS,
		CATEGORY_AI_MODULES,
		CATEGORY_COMPUTER_BOARDS,
		CATEGORY_MACHINERY_TELEPORTATION,
		CATEGORY_MACHINERY_MEDICAL,
		CATEGORY_MACHINERY_ENGINEERING,
		CATEGORY_EXOSUIT_MODULES,
		CATEGORY_MACHINERY_HYDRO,
		CATEGORY_SUBSPACE_TELECOMS,
		CATEGORY_MACHINERY_RESEARCH,
		CATEGORY_MACHINERY_MISC,
		CATEGORY_COMPUTER_PARTS
	)
	console_link = FALSE
	production_animation = "protolathe_n"
	allowed_buildtypes = PROTOLATHE | IMPRINTER
