#define COMSIG_ATTACHMENT_ATTACHED "comsig_attachment_attached"
#define COMSIG_ATTACHMENT_DETACHED "comsig_attachment_detached"
#define COMSIG_ATTACHMENT_ATTACH_ATTEMPT "comsig_attachment_attach_attempt"
