/area/aircontrol
/area/airintake
/area/control_room
/area/controlaccess
/area/engine_access
/area/escapezone
/area/hallways/centralhall
/area/hallways/eastairlock
/area/hallways/labaccess
/area/hallways/loungehall
/area/lounge
/area/medicalstorage
/area/oxygen_storage
/area/shuttle_airlock
/area/shuttle_prison
/area/sleep_area
/area/supply_station
/area/testlab1
/area/testlab2
/area/testlab4
/area/toolstorage
/area/toxinlab
/area/vehicles/shuttle1