'TGUI':
  - changed-files:
      - any-glob-to-any-file: ['tgui/**']

':sound: Звук':
  - changed-files:
      - any-glob-to-any-file: ['**/*.ogg']

':world_map: Изменение Карты':
  - all:
      - changed-files:
          - any-glob-to-any-file: ['**/*.dmm']

':paintbrush: Спрайты':
  - changed-files:
      - any-glob-to-any-file: ['**/*.dmi']

':guitar: Инструменты':
  - changed-files:
      - any-glob-to-any-file: ['.gihub/**', 'tools/**', '.vscode/**', '.bin/**']

':floppy_disk: Изменение конфига':
  - changed-files:
      - any-glob-to-any-file: ['config/**']

':neckbeard: Документация':
  - changed-files:
      - any-glob-to-any-file: ['**/*.md']

':cd: SQL':
  - changed-files:
      - any-glob-to-any-file: ['SQL/**']

':feelsgood: Частичная модульность':
  - all:
      - changed-files:
          - any-glob-to-any-file: ['code/**', 'icons/**', 'sounds/**', '_maps/map_files/**', 'tgui/**']
          - any-glob-to-any-file: [modular_bandastation/**]
      - base-branch: 'master'
      - head-branch: '!merge-upstream'

':finnadie: НЕ МОДУЛЬНО':
  - all:
      - changed-files:
          - any-glob-to-any-file: ['code/**', 'icons/**', 'sounds/**', '_maps/map_files/**']
          - all-globs-to-all-files: '!modular_bandastation/**'
      - base-branch: 'master'
      - head-branch: '!merge-upstream'

':pray: Слияние с восходящим потоком':
  - all:
    - base-branch: 'master'
    - head-branch: 'merge-upstream'

':pencil: Перевод':
  - base-branch: 'translate'

':wrench: Фикс':
  - head-branch: ['^fix', 'fix']

':trollface: Фича':
  - head-branch: ['^feat', 'feat']

':shipit: Улучшение':
  - head-branch: ['^tweak', 'tweak']
