/mob/living/say(message, bubble_type,var/list/spans = list(), sanitize = TRUE, datum/language/language = null)
	if(findtext(message, "rouge"))
		to_chat(src, "<span class='boldwarning'>You feel like a fucking moron.</span>")
		adjustBrainLoss(60)
		src.playsound_local(get_turf(src), 'hippiestation/sound/misc/slidewhistle_down.ogg', 100, FALSE, pressure_affected = FALSE)
	..()
