/datum/design/mech_light_amplification
	name = "Exosuit Module (Light Amplification Module)"
	desc = "Exosuit vision enhancement module for night vision and meson capabilities."
	id = "mech_light_amplification"
	build_type = MECHFAB
	build_path = /obj/item/mecha_parts/mecha_equipment/light_amplification
	materials = list(/datum/material/iron=4000,/datum/material/glass = 2000,/datum/material/uranium = 2000,/datum/material/silver=2000)
	construction_time = 100
	category = list(
		RND_CATEGORY_MECHFAB_EQUIPMENT,
		RND_CATEGORY_MECHFAB_RIPLEY,
		RND_CATEGORY_MECHFAB_ODYSSEUS,
		RND_CATEGORY_MECHFAB_GYGAX,
		RND_CATEGORY_MECHFAB_DURAND,
		RND_CATEGORY_MECHFAB_HONK,
		RND_CATEGORY_MECHFAB_PHAZON,
		RND_CATEGORY_MECHFAB_CLARKE
	)
	category = list(
		RND_CATEGORY_MECHFAB_EQUIPMENT + RND_SUBCATEGORY_MECHFAB_EQUIPMENT_MISC,
		RND_CATEGORY_MECHFAB_RIPLEY + RND_SUBCATEGORY_MECHFAB_SUPPORTED_EQUIPMENT,
		RND_CATEGORY_MECHFAB_ODYSSEUS + RND_SUBCATEGORY_MECHFAB_SUPPORTED_EQUIPMENT,
		RND_CATEGORY_MECHFAB_GYGAX + RND_SUBCATEGORY_MECHFAB_SUPPORTED_EQUIPMENT,
		RND_CATEGORY_MECHFAB_DURAND + RND_SUBCATEGORY_MECHFAB_SUPPORTED_EQUIPMENT,
		RND_CATEGORY_MECHFAB_HONK + RND_SUBCATEGORY_MECHFAB_SUPPORTED_EQUIPMENT,
		RND_CATEGORY_MECHFAB_PHAZON + RND_SUBCATEGORY_MECHFAB_SUPPORTED_EQUIPMENT,
		RND_CATEGORY_MECHFAB_CLARKE + RND_SUBCATEGORY_MECHFAB_SUPPORTED_EQUIPMENT
	)
	departmental_flags = DEPARTMENT_BITFLAG_SCIENCE
