#undef LIGHTING_INTERVAL

#undef LIGHTING_FALLOFF
#undef LIGHTING_LAMBERTIAN
#undef LIGHTING_HEIGHT
#undef LIGHTING_TRANSITIONS

#undef LIGHTING_RESOLUTION
//#undef LIGHTING_LAYER
#undef LIGHTING_ICON
