#ifdef LIGHTING_INSTANT_UPDATES
#undef LIGHTING_INTERVAL
#undef LIGHTING_INSTANT_UPDATES
#endif

#undef LIGHTING_FALLOFF
#undef LIGHTING_LAMBERTIAN
#undef LIGHTING_HEIGHT

//#undef LIGHTING_LAYER
#undef LIGHTING_ICON

#undef LIGHTING_BASE_MATRIX
