/obj/structure/closet/crate/necropolis/tendril/Initialize(mapload)
	. = ..()
	var/loot = rand(1,19)
	var/mod
	switch(loot)
		if(1)
			new /obj/item/shared_storage/red(src)
		if(2)
			new /obj/item/soulstone/anybody/mining(src)
		if(3)
			new /obj/item/organ/internal/cyberimp/arm/katana(src)
		if(4)
			new /obj/item/clothing/glasses/godeye(src)
		if(5)
			new /obj/item/reagent_containers/cup/bottle/potion/flight(src)
		if(6)
			new /obj/item/clothing/gloves/gauntlets(src)
		if(7)
			mod = rand(1,4)
			switch(mod)
				if(1)
					new /obj/item/disk/design_disk/modkit_disc/resonator_blast(src)
				if(2)
					new /obj/item/disk/design_disk/modkit_disc/rapid_repeater(src)
				if(3)
					new /obj/item/disk/design_disk/modkit_disc/mob_and_turf_aoe(src)
				if(4)
					new /obj/item/disk/design_disk/modkit_disc/bounty(src)
		if(8)
			new /obj/item/rod_of_asclepius(src)
		if(9)
			new /obj/item/organ/internal/heart/cursed/wizard(src)
		if(10)
			new /obj/item/ship_in_a_bottle(src)
		if(11)
			new /obj/item/clothing/suit/hooded/berserker(src)
		if(12)
			new /obj/item/guardiancreator/miner(src)
		if(13)
			new /obj/item/warp_cube/red(src)
		if(14)
			new /obj/item/wisp_lantern(src)
		if(15)
			new /obj/item/immortality_talisman(src)
		if(16)
			new /obj/item/book/granter/action/spell/summonitem(src)
		if(17)
			new /obj/item/book_of_babel(src)
		if(18)
			new /obj/item/borg/upgrade/modkit/lifesteal(src)
			new /obj/item/bedsheet/cult(src)
		if(29)
			new /obj/item/clothing/neck/necklace/memento_mori(src)
	if(!contents.len)
		CRASH("Failed to generate loot. loot number: [loot][mod ? "subloot: [mod]" : null]")
	spawned_loot = TRUE
