/obj/structure/closet/athletic_mixed/PopulateContents()
	..()
	new /obj/item/clothing/under/polychromic/shortpants(src)
	new /obj/item/clothing/under/polychromic/shortpants(src)
	new /obj/item/clothing/under/polychromic/shortpants(src)