/datum/hud/blob_overmind/initialize_screen_objects()
	. = ..()
	add_screen_object(/atom/movable/screen/healths/blob, HUD_MOB_HEALTH, HUD_GROUP_INFO)
	add_screen_object(/atom/movable/screen/blob/blob_power, HUD_BLOB_POWER_DISPLAY, HUD_GROUP_INFO)
	add_screen_object(/atom/movable/screen/blob/jump_to_node, HUD_BLOB_JUMP_TO_NODE)
	add_screen_object(/atom/movable/screen/blob/jump_to_core, HUD_BLOB_JUMP_TO_CORE)
	add_screen_object(/atom/movable/screen/blob/blobbernaut, HUD_BLOB_BLOBBERNAUT)
	add_screen_object(/atom/movable/screen/blob/resource_blob, HUD_BLOB_RESOURCES)
	add_screen_object(/atom/movable/screen/blob/node_blob, HUD_BLOB_NODE, ui_loc = ui_hand_position(RIGHT_HANDS))
	add_screen_object(/atom/movable/screen/blob/factory_blob, HUD_BLOB_FACTORY)
	add_screen_object(/atom/movable/screen/blob/readapt_strain, HUD_BLOB_READAPT)
	add_screen_object(/atom/movable/screen/blob/relocate_core, HUD_BLOB_RELOCATE)
