/obj/item/storage/bag/garment/captain/PopulateContents()
	. = ..()
	new /obj/item/clothing/under/misc/doppler_uniform/command(src)
	new /obj/item/clothing/neck/doppler_mantle/command(src)
	new /obj/item/clothing/head/beret/doppler_command/command(src)
	new /obj/item/clothing/head/utility/hardhat/welding/doppler_command/command(src)

/obj/item/storage/bag/garment/hop/PopulateContents()
	. = ..()
	new /obj/item/clothing/under/misc/doppler_uniform/command(src)
	new /obj/item/clothing/neck/doppler_mantle/command(src)
	new /obj/item/clothing/head/beret/doppler_command/command(src)
	new /obj/item/clothing/head/utility/hardhat/welding/doppler_command/command(src)

/obj/item/storage/bag/garment/hos/PopulateContents()
	. = ..()
	new /obj/item/clothing/under/misc/doppler_uniform/security(src)
	new /obj/item/clothing/neck/doppler_mantle/security(src)
	new /obj/item/clothing/head/beret/doppler_command/security(src)
	new /obj/item/clothing/head/utility/hardhat/welding/doppler_command/security(src)

/obj/item/storage/bag/garment/warden/PopulateContents()
	. = ..()
	new /obj/item/clothing/under/misc/doppler_uniform/security(src)

/obj/item/storage/bag/garment/research_director/PopulateContents()
	. = ..()
	new /obj/item/clothing/under/misc/doppler_uniform/science(src)
	new /obj/item/clothing/neck/doppler_mantle/science(src)
	new /obj/item/clothing/head/beret/doppler_command/science(src)
	new /obj/item/clothing/head/utility/hardhat/welding/doppler_command/science(src)

/obj/item/storage/bag/garment/chief_medical/PopulateContents()
	new /obj/item/clothing/neck/doppler_mantle/medical(src)
	new /obj/item/clothing/head/beret/doppler_command/medical(src)
	new /obj/item/clothing/head/utility/hardhat/welding/doppler_command/medical(src)
	new /obj/item/clothing/gloves/latex/nitrile(src)
	new /obj/item/clothing/head/beret/medical/cmo(src)
	new /obj/item/clothing/suit/toggle/labcoat/cmo(src)
	new /obj/item/clothing/head/utility/surgerycap/cmo(src)
	new /obj/item/clothing/neck/cloak/cmo(src)
	new /obj/item/clothing/shoes/medical(src)
	new /obj/item/clothing/under/rank/medical/chief_medical_officer(src)
	new /obj/item/clothing/under/rank/medical/chief_medical_officer/skirt(src)
	new /obj/item/clothing/under/rank/medical/chief_medical_officer/scrubs(src)
	new /obj/item/clothing/under/rank/medical/chief_medical_officer/turtleneck(src)
	new /obj/item/clothing/under/rank/medical/chief_medical_officer/turtleneck/skirt(src)
	new /obj/item/clothing/under/rank/medical/chief_medical_officer/skirt/scrubs(src)


/obj/item/storage/bag/garment/engineering_chief/PopulateContents()
	. = ..()
	new /obj/item/clothing/under/misc/doppler_uniform/engineering(src)
	new /obj/item/clothing/neck/doppler_mantle/engineering(src)
	new /obj/item/clothing/head/beret/doppler_command/engineering(src)
	new /obj/item/clothing/head/utility/hardhat/welding/doppler_command/engineering(src)

/obj/item/storage/bag/garment/quartermaster/PopulateContents()
	. = ..()
	new /obj/item/clothing/under/misc/doppler_uniform/cargo(src)
	new /obj/item/clothing/neck/doppler_mantle/cargo(src)
	new /obj/item/clothing/head/beret/doppler_command/cargo(src)
	new /obj/item/clothing/head/utility/hardhat/welding/doppler_command/cargo(src)
