/datum/centcom_announcer/default
	event_sounds = list(ANNOUNCER_AIMALF = 'massmeta/sounds/announces/aimalf.ogg',
		ANNOUNCER_ALIENS = 'sound/announcer/default/aliens.ogg',
		ANNOUNCER_ANIMES = 'sound/announcer/default/animes.ogg',
		ANNOUNCER_GRANOMALIES = 'massmeta/sounds/announces/granomalies.ogg',
		ANNOUNCER_INTERCEPT = 'sound/announcer/default/intercept.ogg',
		ANNOUNCER_IONSTORM = 'massmeta/sounds/announces/ionstorm.ogg',
		ANNOUNCER_METEORS = 'massmeta/sounds/announces/meteors.ogg',
		ANNOUNCER_OUTBREAK5 = 'massmeta/sounds/announces/outbreak5.ogg',
		ANNOUNCER_OUTBREAK7 = 'massmeta/sounds/announces/outbreak7.ogg',
		ANNOUNCER_POWEROFF = 'massmeta/sounds/announces/poweroff.ogg',
		ANNOUNCER_POWERON = 'massmeta/sounds/announces/poweron.ogg',
		ANNOUNCER_RADIATION = 'massmeta/sounds/announces/radiation.ogg',
		ANNOUNCER_SHUTTLECALLED = 'massmeta/sounds/announces/shuttlecalled.ogg',
		ANNOUNCER_SHUTTLEDOCK = 'massmeta/sounds/announces/shuttledock.ogg',
		ANNOUNCER_SHUTTLERECALLED = 'massmeta/sounds/announces/shuttlerecalled.ogg',
		ANNOUNCER_SPANOMALIES = 'sound/announcer/default/spanomalies.ogg')
	command_report_sounds = list('massmeta/sounds/announces/commandreport.ogg')

/datum/centcom_announcer/intern
	event_sounds = list(ANNOUNCER_AIMALF = 'massmeta/sounds/announces/aimalf.ogg',
		ANNOUNCER_ALIENS = 'sound/announcer/intern/aliens.ogg',
		ANNOUNCER_ANIMES = 'sound/announcer/intern/animes.ogg',
		ANNOUNCER_GRANOMALIES = 'sound/announcer/intern/granomalies.ogg',
		ANNOUNCER_INTERCEPT = 'sound/announcer/intern/intercept.ogg',
		ANNOUNCER_IONSTORM = 'sound/announcer/intern/ionstorm.ogg',
		ANNOUNCER_METEORS = 'sound/announcer/intern/meteors.ogg',
		ANNOUNCER_OUTBREAK5 = 'sound/announcer/intern/outbreak5.ogg',
		ANNOUNCER_OUTBREAK7 = 'sound/announcer/intern/outbreak7.ogg',
		ANNOUNCER_POWEROFF = 'sound/announcer/intern/poweroff.ogg',
		ANNOUNCER_POWERON = 'sound/announcer/intern/poweron.ogg',
		ANNOUNCER_RADIATION = 'sound/announcer/intern/radiation.ogg',
		ANNOUNCER_SHUTTLECALLED = 'sound/announcer/intern/shuttlecalled.ogg',
		ANNOUNCER_SHUTTLEDOCK = 'sound/announcer/intern/shuttledock.ogg',
		ANNOUNCER_SHUTTLERECALLED = 'sound/announcer/intern/shuttlerecalled.ogg',
		ANNOUNCER_SPANOMALIES = 'sound/announcer/intern/spanomalies.ogg')

/datum/centcom_announcer/medbot
	event_sounds = list(ANNOUNCER_AIMALF = 'massmeta/sounds/announces/aimalf.ogg',
		ANNOUNCER_ALIENS = 'sound/announcer/medbot/aliens.ogg',
		ANNOUNCER_ANIMES = 'sound/announcer/medbot/animes.ogg',
		ANNOUNCER_GRANOMALIES = 'sound/announcer/medbot/granomalies.ogg',
		ANNOUNCER_INTERCEPT = 'sound/announcer/medbot/intercept.ogg',
		ANNOUNCER_IONSTORM = 'sound/announcer/medbot/ionstorm.ogg',
		ANNOUNCER_METEORS = 'sound/announcer/medbot/meteors.ogg',
		ANNOUNCER_OUTBREAK5 = 'sound/announcer/medbot/outbreak5.ogg',
		ANNOUNCER_OUTBREAK7 = 'sound/announcer/medbot/outbreak7.ogg',
		ANNOUNCER_POWEROFF = 'sound/announcer/medbot/poweroff.ogg',
		ANNOUNCER_POWERON = 'sound/announcer/medbot/poweron.ogg',
		ANNOUNCER_RADIATION = 'sound/announcer/medbot/radiation.ogg',
		ANNOUNCER_SHUTTLECALLED = 'sound/announcer/medbot/shuttlecalled.ogg',
		ANNOUNCER_SHUTTLEDOCK = 'sound/announcer/medbot/shuttledock.ogg',
		ANNOUNCER_SHUTTLERECALLED = 'sound/announcer/medbot/shuttlerecalled.ogg',
		ANNOUNCER_SPANOMALIES = 'sound/announcer/medbot/spanomalies.ogg')
