GLOBAL_LIST_INIT(crafting_category_food, list(
	CAT_FOOD,
	CAT_DRINK,
))

GLOBAL_LIST_INIT(crafting_category, list(
	CAT_WEAPON_RANGED,
	CAT_WEAPON_MELEE,
	CAT_WEAPON_AMMO,
	CAT_ROBOT,
	CAT_MISC,
	CAT_CLOTHING,
	CAT_CHEMISTRY,
	CAT_ATMOSPHERIC,
	CAT_STRUCTURE,
	CAT_TILES,
	CAT_WINDOWS,
	CAT_DOORS,
	CAT_FURNITURE,
	CAT_EQUIPMENT,
	CAT_CONTAINERS,
	CAT_ENTERTAINMENT,
	CAT_TOOLS,
	CAT_CULT,
))
