GLOBAL_LIST_INIT(available_vox_voices, list(
	"GLaDOS (Neutral)",
	"GLaDOS (Homicidal)",
	"Wheatley",
	"Soldier",
	//"Administrator",
	"Miss Pauling",
	"Rise Kujikawa",
	//"Joker",
	//"Ann Takamaki",
	//"Caleb",
	//"Lo Wang",
	//"Duke Nukem",
	"Announcer",
	"SpongeBob",
	"Sans",
	"Flowey",
	"Toriel",
	"Twilight Sparkle (Happy)",
	"Twilight Sparkle (Neutral)",
	"Fluttershy",
	"Rarity",
	"Applejack",
	"Rainbow Dash",
	"Pinkie Pie",
	"Derpy Hooves"))

// epic translation list for config compatibility
GLOBAL_LIST_INIT(vox_config_translator, list(
	"glados_neutral" = "GLaDOS (Neutral)",
	"glados_homicidal" = "GLaDOS (Homicidal)",
	"wheatley" = "Wheatley",
	"soldier" = "Soldier",
	"misspauling" = "Miss Pauling",
	"risekujikawa" = "Rise Kujikawa",
	"spongebob" = "SpongeBob",
	"sans" = "Sans",
	"flowey" = "Flowey",
	"toriel" = "Toriel",
	"announcer" = "Announcer",
	"twilightsparkle_neutral" = "Twilight Sparkle (Neutral)",
	"twilightsparkle_happy" = "Twilight Sparkle (Happy)",
	"fluttershy" = "Fluttershy",
	"rarity" = "Rarity",
	"applejack" = "Applejack",
	"rainbowdash" = "Rainbow Dash",
	"pinkiepie" = "Pinkie Pie",
	"derpyhooves" = "Derpy Hooves"))
