#include "world.dm"
#include "bloodsuckers\rulesets.dm"
#include "bloodsuckers\code\assets\bloodsucker_assets.dm"
#include "bloodsuckers\code\bloodsucker\bloodsucker_conversion.dm"
#include "bloodsuckers\code\bloodsucker\bloodsucker_datum.dm"
#include "bloodsuckers\code\bloodsucker\bloodsucker_flaws.dm"
#include "bloodsuckers\code\bloodsucker\bloodsucker_frenzy.dm"
#include "bloodsuckers\code\bloodsucker\bloodsucker_guardian.dm"
#include "bloodsuckers\code\bloodsucker\bloodsucker_hud.dm"
#include "bloodsuckers\code\bloodsucker\bloodsucker_integration.dm"
#include "bloodsuckers\code\bloodsucker\bloodsucker_life.dm"
#include "bloodsuckers\code\bloodsucker\bloodsucker_moodlets.dm"
#include "bloodsuckers\code\bloodsucker\bloodsucker_name.dm"
#include "bloodsuckers\code\bloodsucker\bloodsucker_objectives.dm"
#include "bloodsuckers\code\bloodsucker\bloodsucker_procs.dm"
#include "bloodsuckers\code\bloodsucker\bloodsucker_sol.dm"
#include "bloodsuckers\code\bloodsucker\bloodsucker_torpor.dm"
#include "bloodsuckers\code\bloodsucker\shaded_bloodsucker.dm"
#include "bloodsuckers\code\bloodsucker\subsystem_sunlight.dm"
#include "bloodsuckers\code\bloodsucker\vampiric.dm"
#include "bloodsuckers\code\clans\_clan.dm"
#include "bloodsuckers\code\clans\clan_brujah.dm"
#include "bloodsuckers\code\clans\clan_flavortext.dm"
#include "bloodsuckers\code\clans\clan_malkavian.dm"
#include "bloodsuckers\code\clans\clan_nosferatu.dm"
#include "bloodsuckers\code\clans\clan_tremere.dm"
#include "bloodsuckers\code\clans\clan_vassal.dm"
#include "bloodsuckers\code\clans\clan_ventrue.dm"
#include "bloodsuckers\code\objects\bloodsucker_blood_containers.dm"
#include "bloodsuckers\code\objects\bloodsucker_book.dm"
#include "bloodsuckers\code\objects\bloodsucker_stakes.dm"
#include "bloodsuckers\code\particles\bloodsucker_particles.dm"
#include "bloodsuckers\code\powers\brujah\brash.dm"
#include "bloodsuckers\code\powers\targeted\_powers_targeted.dm"
#include "bloodsuckers\code\powers\targeted\brawn.dm"
#include "bloodsuckers\code\powers\targeted\haste.dm"
#include "bloodsuckers\code\powers\targeted\lunge.dm"
#include "bloodsuckers\code\powers\targeted\mesmerize.dm"
#include "bloodsuckers\code\powers\targeted\trespass.dm"
#include "bloodsuckers\code\powers\tremere\_powers_tremere.dm"
#include "bloodsuckers\code\powers\tremere\auspex.dm"
#include "bloodsuckers\code\powers\tremere\dominate.dm"
#include "bloodsuckers\code\powers\tremere\thaumaturgy.dm"
#include "bloodsuckers\code\powers\vassal\distress.dm"
#include "bloodsuckers\code\powers\vassal\recuperate.dm"
#include "bloodsuckers\code\powers\vassal\vassal_fold.dm"
#include "bloodsuckers\code\powers\_powers.dm"
#include "bloodsuckers\code\powers\cloak.dm"
#include "bloodsuckers\code\powers\feed.dm"
#include "bloodsuckers\code\powers\fortitude.dm"
#include "bloodsuckers\code\powers\gohome.dm"
#include "bloodsuckers\code\powers\masquerade.dm"
#include "bloodsuckers\code\powers\veil.dm"
#include "bloodsuckers\code\structures\_bloodsucker_structure.dm"
#include "bloodsuckers\code\structures\bloodsucker_coffin.dm"
#include "bloodsuckers\code\structures\bloodsucker_lighting.dm"
#include "bloodsuckers\code\structures\bloodsucker_mirror.dm"
#include "bloodsuckers\code\structures\bloodsucker_rack.dm"
#include "bloodsuckers\code\structures\bloodsucker_recipes.dm"
#include "bloodsuckers\code\structures\bloodsucker_throne.dm"
#include "bloodsuckers\code\vassal\types\discordant_vassal.dm"
#include "bloodsuckers\code\vassal\types\favorite_vassal.dm"
#include "bloodsuckers\code\vassal\types\revenge_vassal.dm"
#include "bloodsuckers\code\vassal\batform.dm"
#include "bloodsuckers\code\vassal\ex_vassal.dm"
#include "bloodsuckers\code\vassal\vassal_datum.dm"
#include "bloodsuckers\code\vassal\vassal_pinpointer.dm"
#include "bloodsuckers\code\vassal\vassal_procs.dm"

/datum/modpack/antogonists
	id = "antagonists"
	icon = 'modular_meta/features/antagonists/preview.dmi'
	name = "Новые антагонисты (валиды) станции"
	group = "Features"
	desc = "Добавляем новых антагонистов в билд."
	author = "Glamyr"
