#define DOPPLERBOOP_DEFAULT_DURATION 1.5
#define DOPPLERBOOP_DEFAULT_VOLUME 40
#define DOPPLERBOOP_DEFAULT_PITCH 0
#define DOPPLERBOOP_DEFAULT_FALLOFF 6
#define DOPPLERBOOP_DEFAULT_FREQUENCY 1
#define MAX_DOPPLERBOOP_CHARACTERS 75
