#define RESKIN_ICON "reskin_icon"
#define RESKIN_ICON_STATE "reskin_icon_state"
#define RESKIN_WORN_ICON "reskin_worn_icon"
#define RESKIN_WORN_ICON_STATE "reskin_worn_icon_state"
#define RESKIN_SUPPORTS_VARIATIONS_FLAGS "reskin_supports_variations_flags"
#define RESKIN_INHAND_L "reskin_inhand_l"
#define RESKIN_INHAND_R "reskin_inhand_r"
#define RESKIN_INHAND_STATE "reskin_inhand_state"
