
// Fish path used for autogenerated fish
/obj/item/fish
	name = "generic looking aquarium fish"
	desc = "very bland"
	w_class = WEIGHT_CLASS_TINY

/// Automatically generates object of given base path from the behaviour type in loc
/proc/generate_fish(loc,behaviour_type,base_path=/obj/item/fish)
	var/datum/aquarium_behaviour/B = behaviour_type
	var/obj/item/F = new /obj/item/fish(loc)
	F.name = initial(B.name)
	F.icon = initial(B.icon)
	F.icon_state = initial(B.icon_state)
	F.desc = initial(B.desc)
	if(initial(B.color))
		F.add_atom_colour(initial(B.color),FIXED_COLOUR_PRIORITY)
	if(ispath(behaviour_type,/datum/aquarium_behaviour/fish))
		var/datum/aquarium_behaviour/fish/BF = behaviour_type
		var/fillet_type = initial(BF.fillet_type)
		if(fillet_type)
			F.AddElement(/datum/element/processable, TOOL_KNIFE, fillet_type, 1, 5)
	F.AddElement(/datum/element/deferred_aquarium_content,behaviour_type)
	return F

/proc/random_fish_type()
	var/static/probability_table
	if(!probability_table)
		probability_table = list()
		for(var/T in subtypesof(/datum/aquarium_behaviour/fish))
			var/datum/aquarium_behaviour/fish/F = T
			if(initial(F.availible_in_random_cases))
				probability_table[T] = initial(F.random_case_rarity)
	return pickweight(probability_table)

// Actual fish definitions below - there's no specific paths, they are autogenerated from behaviours

// Freshwater fish

/datum/aquarium_behaviour/fish/goldfish
	name = "goldfish"
	desc = "not actually made of gold"
	icon_state = "goldfish"
	color = "#f2da29"
	aquarium_vc_color = "#f2da29"
	dedicated_in_aquarium_icon_state = "fish_greyscale"

/datum/aquarium_behaviour/fish/angelfish
	name = "angelfish"
	desc = "Omnivore fish originating from Amazon River."
	icon_state = "angelfish"
	dedicated_in_aquarium_icon_state = "bigfish"
	sprite_height = 7
	source_height = 7

/datum/aquarium_behaviour/fish/guppy
	name = "guppy"
	desc = "One of the most popular aquarium fish."
	icon_state = "guppy"
	dedicated_in_aquarium_icon_state = "fish_greyscale"
	aquarium_vc_color = "#91AE64"
	sprite_width = 8
	sprite_height = 5

/datum/aquarium_behaviour/fish/plasmatetra
	name = "plasma tetra"
	desc = "Tetra fish with coloring similar to plasma."
	icon_state = "plastetra"
	dedicated_in_aquarium_icon_state = "fish_greyscale"
	aquarium_vc_color = "#D30EB0"

/datum/aquarium_behaviour/fish/catfish
	name = "cory catfish"
	desc = "Unrelated to actual cats."
	icon_state = "catfish"
	dedicated_in_aquarium_icon_state = "fish_greyscale"
	aquarium_vc_color = "#907420"

/datum/aquarium_behaviour/fish/spacecarp
	name = "space carp"
	desc = "This space predator fish is known to cause yearly damage to space stations during their migrations."
	icon_state = "carp"
	sprite_width = 8
	sprite_height = 8
	availible_in_random_cases = FALSE

// Saltwater fish below

/datum/aquarium_behaviour/fish/clownfish
	name = "clownfish"
	desc = "Honk!"
	icon_state = "clownfish"
	dedicated_in_aquarium_icon_state = "clownfish_small"
	required_fluid_type = AQUARIUM_FLUID_SALTWATER
	sprite_width = 8
	sprite_height = 5

/datum/aquarium_behaviour/fish/cardinal
	name = "cardinalfish"
	desc = "Small saltwater fish active at night."
	icon_state = "cardinalfish"
	dedicated_in_aquarium_icon_state = "fish_greyscale"
	required_fluid_type = AQUARIUM_FLUID_SALTWATER

/datum/aquarium_behaviour/fish/greenchromis
	name = "green chromis"
	desc = "Small fish with distinctive green sheen."
	icon_state = "greenchromis"
	dedicated_in_aquarium_icon_state = "fish_greyscale"
	aquarium_vc_color = "#00ff00"
	required_fluid_type = AQUARIUM_FLUID_SALTWATER

/datum/aquarium_behaviour/fish/firefish
	name = "firefish goby"
	desc = "Long thing two-colored fish."
	icon_state = "firefish"
	sprite_width = 6
	sprite_height = 5
	required_fluid_type = AQUARIUM_FLUID_SALTWATER

/datum/aquarium_behaviour/fish/pufferfish
	name = "pufferfish"
	desc = "I'll let reviewers write these dang descriptions."
	icon_state = "pufferfish"
	required_fluid_type = AQUARIUM_FLUID_SALTWATER
	sprite_width = 8
	sprite_height = 8

/datum/aquarium_behaviour/fish/pufferfish
	name = "lanternfish"
	desc = "Terror of the deep."
	icon_state = "lanternfish"
	required_fluid_type = AQUARIUM_FLUID_SALTWATER
	random_case_rarity = FISH_RARITY_VERY_RARE
	source_width = 28
	source_height = 21
	sprite_width = 8
	sprite_height = 8

