/obj/secure_closet/animal/New()
	..()
	sleep(2)
	new /obj/item/device/radio/signaler( src )
	new /obj/item/device/radio/electropack( src )
	new /obj/item/device/radio/electropack( src )
	new /obj/item/device/radio/electropack( src )
	new /obj/item/device/radio/electropack( src )
	new /obj/item/device/radio/electropack( src )
	return
