/obj/secure_closet/captains/New()
	..()
	sleep(2)
	new /obj/item/weapon/reagent_containers/food/drinks/flask(src)
	new /obj/item/device/radio/headset/headset_com( src )
	new /obj/item/weapon/gun/energy/general( src )
	new /obj/item/weapon/storage/id_kit( src )
	new /obj/item/clothing/under/rank/captain( src )
	new /obj/item/clothing/shoes/brown( src )
	new /obj/item/clothing/glasses/sunglasses( src )
	new /obj/item/clothing/suit/armor/vest( src )
	new /obj/item/clothing/head/helmet/swat( src )
	return
