/obj/secure_closet/engineering_chief/New()
	..()
	sleep(2)
	new /obj/item/weapon/storage/toolbox/mechanical( src )
	new /obj/item/device/radio/headset/headset_eng( src )
	new /obj/item/clothing/under/rank/chief_engineer( src )
	new /obj/item/clothing/gloves/yellow( src )
	new /obj/item/clothing/shoes/brown( src )
	new /obj/item/clothing/shoes/magboots( src )
	new /obj/item/clothing/ears/earmuffs( src )
	new /obj/item/clothing/glasses/meson( src )
	new /obj/item/clothing/suit/fire( src )
	new /obj/item/clothing/suit/hazardvest( src )
	new /obj/item/clothing/mask/gas( src )
	new /obj/item/clothing/head/helmet/welding( src )
	new /obj/item/clothing/head/helmet/hardhat( src )
	new /obj/item/device/multitool( src )
	new /obj/item/device/flash( src )
	return

/obj/secure_closet/engineering_electrical/New()
	..()
	sleep(2)
	new /obj/item/clothing/gloves/yellow( src )
	new /obj/item/clothing/gloves/yellow( src )
	new /obj/item/clothing/gloves/yellow( src )
	new /obj/item/weapon/storage/toolbox/electrical( src )
	new /obj/item/weapon/storage/toolbox/electrical( src )
	new /obj/item/weapon/storage/toolbox/electrical( src )
	new /obj/item/device/multitool( src )
	new /obj/item/device/multitool( src )
	new /obj/item/device/multitool( src )
	return

/obj/secure_closet/engineering_welding/New()
	..()
	sleep(2)
	new /obj/item/clothing/head/helmet/welding( src )
	new /obj/item/clothing/head/helmet/welding( src )
	new /obj/item/clothing/head/helmet/welding( src )
	new /obj/item/weapon/weldingtool( src )
	new /obj/item/weapon/weldingtool( src )
	new /obj/item/weapon/weldingtool( src )
	return

/obj/secure_closet/engineering_personal/New()
	..()
	sleep(2)
	new /obj/item/weapon/storage/toolbox/mechanical( src )
	new /obj/item/device/radio/headset/headset_eng( src )
	new /obj/item/clothing/under/rank/engineer( src )
	new /obj/item/clothing/shoes/orange( src )
	new /obj/item/clothing/suit/hazardvest( src )
	new /obj/item/clothing/mask/gas( src )
	new /obj/item/clothing/head/helmet/hardhat( src )
	new /obj/item/clothing/ears/earmuffs( src )
	new /obj/item/clothing/glasses/meson( src )
	return