/obj/secure_closet/medical1/New()
	..()
	sleep(2)
	new /obj/item/weapon/storage/gl_kit( src )
	new /obj/item/weapon/reagent_containers/glass/bottle/antitoxin( src )
	new /obj/item/weapon/reagent_containers/glass/bottle/antitoxin( src )
	new /obj/item/weapon/reagent_containers/glass/bottle/antitoxin( src )
	new /obj/item/weapon/reagent_containers/glass/bottle/inaprovaline( src )
	new /obj/item/weapon/reagent_containers/glass/bottle/inaprovaline( src )
	new /obj/item/weapon/reagent_containers/glass/bottle/inaprovaline( src )
	new /obj/item/weapon/reagent_containers/glass/bottle/stoxin( src )
	new /obj/item/weapon/reagent_containers/glass/bottle/stoxin( src )
	new /obj/item/weapon/reagent_containers/glass/bottle/toxin( src )
	new /obj/item/weapon/storage/firstaid/syringes( src )
	new /obj/item/weapon/reagent_containers/dropper( src )
	new /obj/item/weapon/reagent_containers/dropper( src )
	new /obj/item/weapon/reagent_containers/glass/beaker( src )
	new /obj/item/weapon/reagent_containers/glass/beaker( src )
	new /obj/item/weapon/storage/utilitybelt/medical( src )
	return

/obj/secure_closet/medical2/New()
	..()
	sleep(2)
	new /obj/item/weapon/tank/anesthetic( src )
	new /obj/item/weapon/tank/anesthetic( src )
	new /obj/item/weapon/tank/anesthetic( src )
	new /obj/item/weapon/tank/anesthetic( src )
	new /obj/item/weapon/tank/anesthetic( src )
	new /obj/item/clothing/mask/medical( src )
	new /obj/item/clothing/mask/medical( src )
	new /obj/item/clothing/mask/medical( src )
	new /obj/item/clothing/mask/medical( src )
	return

/obj/secure_closet/medical3/New()
	..()
	sleep(2)
	new /obj/item/device/radio/headset/headset_med( src )
	new /obj/item/device/radio/headset/headset_med( src )
	new /obj/item/device/radio/headset/headset_med( src )
	new /obj/item/clothing/under/rank/medical( src )
	new /obj/item/clothing/under/rank/medical( src )
	new /obj/item/clothing/under/rank/medical( src )
	new /obj/item/clothing/suit/labcoat( src )
	new /obj/item/clothing/suit/labcoat( src )
	new /obj/item/clothing/suit/labcoat( src )
	new /obj/item/clothing/mask/medical( src )
	new /obj/item/clothing/mask/medical( src )
	new /obj/item/clothing/mask/medical( src )
	return

/obj/secure_closet/CMO/New()
	..()
	sleep(2)
	new /obj/item/device/radio/headset/heads/cmo( src )
	new /obj/item/clothing/suit/labcoat/cmo( src )
	new /obj/item/clothing/under/rank/medical( src )
	new /obj/item/weapon/tank/air( src )
	new /obj/item/clothing/mask/gas( src )
	new /obj/item/clothing/suit/bio_suit/general( src )
	new /obj/item/clothing/shoes/white( src )
	new /obj/item/clothing/gloves/latex( src )
	new /obj/item/clothing/head/bio_hood/general( src )
	new /obj/item/clothing/suit/labcoat(src)
	return