/// Takes a set of pixel offsets (w and z here for consistency could be x and y) (applied to a floor item)
/// and turns them by the passed in angle
/// Returns a list in the form list(pixel_w, pixel_z)
/proc/rotate_pixel_offset(pixel_w, pixel_z, angle = 0)
	switch(angle)
		if(0)
			return list(pixel_w, pixel_z)
		if(90)
			return list(pixel_z, -pixel_w)
		if(180)
			return list(-pixel_w, -pixel_z)
		if(270)
			return list(-pixel_z, pixel_w)
	return list(pixel_w, pixel_z)
