// Weapon Categories
#define RND_CATEGORY_WEAPONS "/Оружие"
#define RND_SUBCATEGORY_WEAPONS_FIRING_PINS "/Ударники"
#define RND_SUBCATEGORY_WEAPONS_AMMO "/Боеприпасы"
#define RND_SUBCATEGORY_WEAPONS_PARTS "/Части оружия"
#define RND_SUBCATEGORY_WEAPONS_RANGED "/Дальнобойное оружие"
#define RND_SUBCATEGORY_WEAPONS_MELEE "/Холодное оружие"
#define RND_SUBCATEGORY_WEAPONS_KITS "/Комплекты деталей оружия"

// Wiremod Categories
#define RND_CATEGORY_CIRCUITRY "/Схемы"
#define RND_CATEGORY_CIRCUITRY_CORE "/Основное"
#define RND_SUBCATEGORY_CIRCUITRY_COMPONENTS "/Компоненты схем"
#define RND_SUBCATEGORY_CIRCUITRY_BCI_COMPONENTS "/Компоненты схем ИМК"
#define RND_SUBCATEGORY_CIRCUITRY_SHELLS "/Оболочки для схем"

// Tool Categories
#define RND_CATEGORY_TOOLS "/Инструменты"
#define RND_SUBCATEGORY_TOOLS_MEDICAL "/Медицинские инструменты"
#define RND_SUBCATEGORY_TOOLS_MEDICAL_ADVANCED "/Медицинские инструменты (Продвинутые)"
#define RND_SUBCATEGORY_TOOLS_MEDICAL_ALIEN "/Медицинские инструменты (Инопланетные)"
#define RND_SUBCATEGORY_TOOLS_ENGINEERING "/Инженерные инструменты"
#define RND_SUBCATEGORY_TOOLS_ENGINEERING_ADVANCED "/Инженерные инструменты (Продвинутые)"
#define RND_SUBCATEGORY_TOOLS_ENGINEERING_ALIEN "/Инженерные инструменты (Инопланетные)"
#define RND_SUBCATEGORY_TOOLS_SERVICE "/Обслуживания инструменты"
#define RND_SUBCATEGORY_TOOLS_BOTANY "/Ботанические инструменты"
#define RND_SUBCATEGORY_TOOLS_BOTANY_ADVANCED "/Ботанические инструменты (Продвинутые)"
#define RND_SUBCATEGORY_TOOLS_JANITORIAL "/Уборочные инструменты"
#define RND_SUBCATEGORY_TOOLS_PLUMBING "/Водопроводческие инструменты"
#define RND_SUBCATEGORY_TOOLS_ATMOSPHERICS "/Атмосферные инструменты"
#define RND_SUBCATEGORY_TOOLS_MINING "/Шахтёрские инструменты"
#define RND_SUBCATEGORY_TOOLS_CARGO "/Снабжения инструменты"
#define RND_SUBCATEGORY_TOOLS_PKA_MODS "/Моды ПКА"
#define RND_SUBCATEGORY_TOOLS_SECURITY "/Охранные инструменты"
#define RND_SUBCATEGORY_TOOLS_MISC "/Прочие инструменты"

#define RND_CATEGORY_CONSTRUCTION "/Строительство"
#define RND_SUBCATEGORY_CONSTRUCTION_MOUNTS "/Каркасы и крепления"
#define RND_SUBCATEGORY_CONSTRUCTION_ELECTRONICS "/Электроника"
#define RND_SUBCATEGORY_CONSTRUCTION_MACHINERY "/Машины"
#define RND_SUBCATEGORY_CONSTRUCTION_MATERIALS "/Материалы и сплавы"
#define RND_SUBCATEGORY_CONSTRUCTION_LIGHTING "/Освещение"
#define RND_SUBCATEGORY_CONSTRUCTION_ASSEMBLIES "/Электрические сборки"

#define RND_CATEGORY_COMPUTER "/Платы компьютеров"
#define RND_SUBCATEGORY_COMPUTER_ENTERTAINMENT "/Обслуживания консоли"
#define RND_SUBCATEGORY_COMPUTER_MEDICAL "/Медицинские консоли"
#define RND_SUBCATEGORY_COMPUTER_ROBOTICS "/Робототехники консоли"
#define RND_SUBCATEGORY_COMPUTER_GENETICS "/Генетические консоли"
#define RND_SUBCATEGORY_COMPUTER_RECORDS "/Записей консоли"
#define RND_SUBCATEGORY_COMPUTER_COMMAND "/Командные консоли"
#define RND_SUBCATEGORY_COMPUTER_SECURITY "/Охранные консоли"
#define RND_SUBCATEGORY_COMPUTER_RESEARCH "/Исследований консоли"
#define RND_SUBCATEGORY_COMPUTER_ENGINEERING "/Инженерные и атмосферные консоли"
#define RND_SUBCATEGORY_COMPUTER_CARGO "/Снабжения консоли"

#define RND_CATEGORY_MACHINE "/Платы машин"
#define RND_SUBCATEGORY_MACHINE_ATMOS "/Атмосферные машины"
#define RND_SUBCATEGORY_MACHINE_KITCHEN "/Кухонные машины"
#define RND_SUBCATEGORY_MACHINE_BAR "/Барные машины"
#define RND_SUBCATEGORY_MACHINE_BOTANY "/Ботанические машины"
#define RND_SUBCATEGORY_MACHINE_ENGINEERING "/Инженерные машины"
#define RND_SUBCATEGORY_MACHINE_RESEARCH "/Исследований машины"
#define RND_SUBCATEGORY_MACHINE_MEDICAL "/Медицинские машины"
#define RND_SUBCATEGORY_MACHINE_CHEMISTRY "/Химии машины"
#define RND_SUBCATEGORY_MACHINE_SECURITY "/Охранные машины"
#define RND_SUBCATEGORY_MACHINE_CARGO "/Снабжения машины"
#define RND_SUBCATEGORY_MACHINE_TELEPORT "/Телепортационные машины"
#define RND_SUBCATEGORY_MACHINE_ROBOTICS "/Робототехнические машины"
#define RND_SUBCATEGORY_MACHINE_GENETICS "/Генетические машины"
#define RND_SUBCATEGORY_MACHINE_FAB "/Фабрикаторы"
#define RND_SUBCATEGORY_MACHINE_SERVICE "/Обслуживания машины"
#define RND_SUBCATEGORY_MACHINE_TELECOMMS "/Телекоммуникационные машины"

#define RND_CATEGORY_EQUIPMENT "/Снаряжение"
#define RND_SUBCATEGORY_EQUIPMENT_SERVICE "/Обслуживания снаряжение"
#define RND_SUBCATEGORY_EQUIPMENT_JOKE "/Совершенно секретное снаряжение"
#define RND_SUBCATEGORY_EQUIPMENT_CHEMISTRY "/Химии снаряжение"
#define RND_SUBCATEGORY_EQUIPMENT_MEDICAL "/Медицинское снаряжение"
#define RND_SUBCATEGORY_EQUIPMENT_SECURITY "/Охранное снаряжение"
#define RND_SUBCATEGORY_EQUIPMENT_TELECOMMS "/Коммуникационное снаряжение"
#define RND_SUBCATEGORY_EQUIPMENT_BLUESPACE "/Блюспейс снаряжение"
#define RND_SUBCATEGORY_EQUIPMENT_ENGINEERING "/Инженерное снаряжение"
#define RND_SUBCATEGORY_EQUIPMENT_ATMOSPHERICS "/Атмосферное снаряжение"
#define RND_SUBCATEGORY_EQUIPMENT_SCIENCE "/Исследований снаряжение"
#define RND_SUBCATEGORY_EQUIPMENT_GAS_TANKS "/Газовые канистры"
#define RND_SUBCATEGORY_EQUIPMENT_GAS_TANKS_EQUIPMENT "/Газовых канистр снаряжение"
#define RND_SUBCATEGORY_EQUIPMENT_XENOBIOLOGY "/Ксенобиологии снаряжение"
#define RND_SUBCATEGORY_EQUIPMENT_GENETICS "/Генетическое снаряжение"
#define RND_SUBCATEGORY_EQUIPMENT_JANITOR "/Уборочное снаряжение"
#define RND_SUBCATEGORY_EQUIPMENT_KITCHEN "/Барное и кухонное снаряжение"
#define RND_SUBCATEGORY_EQUIPMENT_MISC "/Прочее снаряжение"

#define RND_CATEGORY_AI "/Искусственный интеллект"
#define RND_SUBCATEGORY_AI_CORE "/Сборка ИИ"
#define RND_SUBCATEGORY_AI_CORE_MODULES "/Основные законы ИИ"
#define RND_SUBCATEGORY_AI_DANGEROUS_MODULES "/Опасные законы ИИ"
#define RND_SUBCATEGORY_AI_LAW_MANIPULATION "/Управление законами ИИ"
#define RND_SUBCATEGORY_AI_MISC "/Прочие предметы с ИИ"
#define RND_SUBCATEGORY_AI_UPGRADES "/Улучшения ИИ"

#define RND_CATEGORY_MODULAR_COMPUTERS "/Модульные компьютеры"
#define RND_SUBCATEGORY_MODULAR_COMPUTERS_FRAMES "/Каркасы"
#define RND_SUBCATEGORY_MODULAR_COMPUTERS_PARTS "/Детали"

#define RND_CATEGORY_STOCK_PARTS "/Детали машин"
#define RND_SUBCATEGORY_STOCK_PARTS_MISC "/Прочие детали"
#define RND_SUBCATEGORY_STOCK_PARTS_TURBINE "/Детали турбины"
#define RND_SUBCATEGORY_STOCK_PARTS_TELECOMMS "/Детали телекоммуникаций"
#define RND_SUBCATEGORY_STOCK_PARTS_1 "/Тир-1 детали"
#define RND_SUBCATEGORY_STOCK_PARTS_2 "/Тир-2 детали"
#define RND_SUBCATEGORY_STOCK_PARTS_3 "/Тир-3 детали"
#define RND_SUBCATEGORY_STOCK_PARTS_4 "/Тир-4 детали"
#define RND_SUBCATEGORY_STOCK_PARTS_EXCHANGERS "/Устройства замены"

#define RND_CATEGORY_SYNDICATE "/Нелегальные дизайны"

#define RND_CATEGORY_EXOSUIT_BOARDS "/Платы экзокостюмов"
#define RND_SUBCATEGORY_EXOSUIT_BOARDS_RIPLEY "/Рипли"
#define RND_SUBCATEGORY_EXOSUIT_BOARDS_ODYSSEUS "/Одиссей"
#define RND_SUBCATEGORY_EXOSUIT_BOARDS_GYGAX "/Гигакс"
#define RND_SUBCATEGORY_EXOSUIT_BOARDS_DURAND "/Дюранд"
#define RND_SUBCATEGORY_EXOSUIT_BOARDS_HONK "/Х.О.Н.К."
#define RND_SUBCATEGORY_EXOSUIT_BOARDS_PHAZON "/Фазон"
#define RND_SUBCATEGORY_EXOSUIT_BOARDS_CLARKE "/Кларк"
#define RND_SUBCATEGORY_EXOSUIT_BOARDS_SAVANNAH_IVANOV "/Саванна-Иванов"

#define RND_CATEGORY_MECHFAB_RIPLEY "/Рипли"
#define RND_CATEGORY_MECHFAB_PADDY "/Падди"
#define RND_CATEGORY_MECHFAB_ODYSSEUS "/Одиссей"
#define RND_CATEGORY_MECHFAB_GYGAX "/Гигакс"
#define RND_CATEGORY_MECHFAB_DURAND "/Дюранд"
#define RND_CATEGORY_MECHFAB_HONK "/Х.О.Н.К."
#define RND_CATEGORY_MECHFAB_PHAZON "/Фазон"
#define RND_CATEGORY_MECHFAB_CLARKE "/Кларк"
#define RND_CATEGORY_MECHFAB_SAVANNAH_IVANOV "/Саванна-Иванов"
#define RND_SUBCATEGORY_MECHFAB_CHASSIS "/Шасси"
#define RND_SUBCATEGORY_MECHFAB_SUPPORTED_EQUIPMENT "/Поддерживаемое снаряжение"
#define RND_SUBCATEGORY_MECHFAB_CONTROL_INTERFACES "/Интерфейсы контроля"

#define RND_CATEGORY_MECHFAB_EQUIPMENT "/Снаряжение экзокостюмов"
#define RND_SUBCATEGORY_MECHFAB_EQUIPMENT_MINING "/Шахтёрское снаряжение"
#define RND_SUBCATEGORY_MECHFAB_EQUIPMENT_WEAPONS "/Оружие и боеприпасы"
#define RND_SUBCATEGORY_MECHFAB_EQUIPMENT_MODULES "/Броня и модули ремонта"
#define RND_SUBCATEGORY_MECHFAB_EQUIPMENT_MISC "/Прочее"
#define RND_SUBCATEGORY_MECHFAB_EQUIPMENT_MEDICAL "/Медицинское"
#define RND_SUBCATEGORY_MECHFAB_EQUIPMENT_HONK "/Клоунские дизайны"
#define RND_SUBCATEGORY_MECHFAB_EQUIPMENT_CONTROL_INTERFACES "/Интерфейсы контроля"

#define RND_CATEGORY_MECHFAB_CYBORG "/Киборг"
#define RND_SUBCATEGORY_MECHFAB_CYBORG_CHASSIS "/Шасси киборга"
#define RND_SUBCATEGORY_MECHFAB_CYBORG_COMPONENTS "/Компоненты"
#define RND_SUBCATEGORY_MECHFAB_CYBORG_CELLS "/Батареи"
#define RND_SUBCATEGORY_MECHFAB_CYBORG_CONTROL_INTERFACES "/Интерфейсы контроля"

#define RND_CATEGORY_MECHFAB_CYBORG_MODULES "/Модули киборгов"
#define RND_SUBCATEGORY_MECHFAB_CYBORG_MODULES_ALL "/Все киборги"
#define RND_SUBCATEGORY_MECHFAB_CYBORG_MODULES_MEDICAL "/Медицинские киборги"
#define RND_SUBCATEGORY_MECHFAB_CYBORG_MODULES_ENGINEERING "/Инженерные киборги"
#define RND_SUBCATEGORY_MECHFAB_CYBORG_MODULES_JANITOR "/Уборочные киборги"
#define RND_SUBCATEGORY_MECHFAB_CYBORG_MODULES_SECURITY "/Охранные киборги"
#define RND_SUBCATEGORY_MECHFAB_CYBORG_MODULES_MINING "/Шахтёрские киборги"
#define RND_SUBCATEGORY_MECHFAB_CYBORG_MODULES_SERVICE "/Обслуживания киборги"

#define RND_CATEGORY_MODSUITS "/MOD костюмы"
#define RND_SUBCATEGORY_MODUITS_CHASSIS "/Шасси"
#define RND_SUBCATEGORY_MODSUITS_PLATING "/Обшивки"
#define RND_SUBCATEGORY_MODSUITS_MISC "/Прочее"

#define RND_CATEGORY_MODSUIT_MODULES "/MODули"
#define RND_SUBCATEGORY_MODSUIT_MODULES_GENERAL "/Обычные модули"
#define RND_SUBCATEGORY_MODSUIT_MODULES_ENGINEERING "/Инженерные модули"
#define RND_SUBCATEGORY_MODSUIT_MODULES_MEDICAL "/Медицинские модули"
#define RND_SUBCATEGORY_MODSUIT_MODULES_SCIENCE "/Исследований модули"
#define RND_SUBCATEGORY_MODSUIT_MODULES_SECURITY "/Охранные модули"
#define RND_SUBCATEGORY_MODSUIT_MODULES_SUPPLY "/Снабжения модули"
#define RND_SUBCATEGORY_MODSUIT_MODULES_SERVICE "/Обслуживания модули"

#define RND_CATEGORY_CYBERNETICS "/Кибернетика"
#define RND_SUBCATEGORY_CYBERNETICS_ORGANS_1 "/Тир-1 кибернетические органы"
#define RND_SUBCATEGORY_CYBERNETICS_ORGANS_2 "/Тир-2 кибернетические органы"
#define RND_SUBCATEGORY_CYBERNETICS_ORGANS_3 "/Тир-3 кибернетические органы"
#define RND_SUBCATEGORY_CYBERNETICS_ORGANS_COMBAT "/Боевые кибернетические органы"
#define RND_SUBCATEGORY_CYBERNETICS_ORGANS_MISC "/Прочие кибернетические Organs"
#define RND_SUBCATEGORY_CYBERNETICS_IMPLANTS_COMBAT "/Кибернетические боевые импланты"
#define RND_SUBCATEGORY_CYBERNETICS_IMPLANTS_HEALTH "/Кибернетические импланты здоровья"
#define RND_SUBCATEGORY_CYBERNETICS_IMPLANTS_TOOLS "/Кибернетические импланты-инструменты"
#define RND_SUBCATEGORY_CYBERNETICS_IMPLANTS_UTILITY "/Кибернетические вспомогательные импланты"
#define RND_SUBCATEGORY_CYBERNETICS_IMPLANTS_MISC "/Кибернетические прочие импланты"
#define RND_SUBCATEGORY_CYBERNETICS_IMPLANTS_SECURITY "/Кибернетические охранные импланты"
#define RND_SUBCATEGORY_CYBERNETICS_ADVANCED_LIMBS "/Кибернетические продвинутые конечности"

// Limb Categories
#define RND_CATEGORY_LIMBS_DIGITIGRADE "digitigrade"
#define RND_CATEGORY_LIMBS_OTHER "Other Limbs"

/// Biogenerator Categories
#define RND_CATEGORY_BIO_FOOD "Еда"
#define RND_CATEGORY_BIO_CHEMICALS "Химикаты"
#define RND_CATEGORY_BIO_MATERIALS "Материалы"

// Meta categories
#define RND_CATEGORY_INITIAL "initial"
#define RND_CATEGORY_HACKED "hacked"
#define RND_CATEGORY_IMPORTED "/Imported Designs"
