// Категории оружия
#define RND_CATEGORY_WEAPONS "/Вооружение"
#define RND_SUBCATEGORY_WEAPONS_FIRING_PINS "/Ударники"
#define RND_SUBCATEGORY_WEAPONS_AMMO "/Боеприпасы"
#define RND_SUBCATEGORY_WEAPONS_PARTS "/Части оружия"
#define RND_SUBCATEGORY_WEAPONS_RANGED "/Дальнобойное оружие"
#define RND_SUBCATEGORY_WEAPONS_MELEE "/Оружие ближнего боя"
#define RND_SUBCATEGORY_WEAPONS_KITS "/Наборы для изготовления оружия"

// Категории проводки
#define RND_CATEGORY_CIRCUITRY "/Схема"
#define RND_CATEGORY_CIRCUITRY_CORE "/Ядро"
#define RND_SUBCATEGORY_CIRCUITRY_COMPONENTS "/Компоненты схемы"
#define RND_SUBCATEGORY_CIRCUITRY_BCI_COMPONENTS "/Компоненты BCI схемы"
#define RND_SUBCATEGORY_CIRCUITRY_SHELLS "/Контурные оболочки"

// Категории инструментов
#define RND_CATEGORY_TOOLS "/Инструменты"
#define RND_SUBCATEGORY_TOOLS_MEDICAL "/Медицинские инструменты"
#define RND_SUBCATEGORY_TOOLS_MEDICAL_ADVANCED "/Медицинские инструменты (продвинутые)"
#define RND_SUBCATEGORY_TOOLS_MEDICAL_ALIEN "/Медицинские инструменты (инопланетные)"
#define RND_SUBCATEGORY_TOOLS_ENGINEERING "/Инженерные инструменты"
#define RND_SUBCATEGORY_TOOLS_ENGINEERING_ADVANCED "/Инженерные инструменты (продвинутые)"
#define RND_SUBCATEGORY_TOOLS_ENGINEERING_ALIEN "/Инженерные инструменты (инопланетные)"
#define RND_SUBCATEGORY_TOOLS_SERVICE "/Сервисные инструменты"
#define RND_SUBCATEGORY_TOOLS_BOTANY "/Ботанические инструменты"
#define RND_SUBCATEGORY_TOOLS_BOTANY_ADVANCED "/Ботанические инструменты (продвинутые)"
#define RND_SUBCATEGORY_TOOLS_JANITORIAL "/Инструменты для уборки"
#define RND_SUBCATEGORY_TOOLS_PLUMBING "/Сантехнические инструменты"
#define RND_SUBCATEGORY_TOOLS_ATMOSPHERICS "/Атмосферные инструменты"
#define RND_SUBCATEGORY_TOOLS_MINING "/Инструменты для добычи ископаемых"
#define RND_SUBCATEGORY_TOOLS_CARGO "/Карго инструменты"
#define RND_SUBCATEGORY_TOOLS_PKA_MODS "/Модификации PKA"
#define RND_SUBCATEGORY_TOOLS_SECURITY "/Инструменты отдела безопасности"
#define RND_SUBCATEGORY_TOOLS_MISC "/Различные инструменты"

#define RND_CATEGORY_CONSTRUCTION "/Конструкции"
#define RND_SUBCATEGORY_CONSTRUCTION_MOUNTS "/Каркасы и крепления"
#define RND_SUBCATEGORY_CONSTRUCTION_ELECTRONICS "/Платы электроники"
#define RND_SUBCATEGORY_CONSTRUCTION_MACHINERY "/Механическое оборудование"
#define RND_SUBCATEGORY_CONSTRUCTION_MATERIALS "/Материалы и сплавы"
#define RND_SUBCATEGORY_CONSTRUCTION_LIGHTING "/Освещение"
#define RND_SUBCATEGORY_CONSTRUCTION_ASSEMBLIES "/Электрические компоненты"

#define RND_CATEGORY_COMPUTER "/Компьютерные платы"
#define RND_SUBCATEGORY_COMPUTER_ENTERTAINMENT "/Сервисные консоли"
#define RND_SUBCATEGORY_COMPUTER_MEDICAL "/Медицинские консоли"
#define RND_SUBCATEGORY_COMPUTER_ROBOTICS "/Робототехнические консоли"
#define RND_SUBCATEGORY_COMPUTER_GENETICS "/Генетические консоли"
#define RND_SUBCATEGORY_COMPUTER_RECORDS "/Консоли для записи"
#define RND_SUBCATEGORY_COMPUTER_COMMAND "/Командные консоли"
#define RND_SUBCATEGORY_COMPUTER_SECURITY "/Консоли отдела безопасности"
#define RND_SUBCATEGORY_COMPUTER_RESEARCH "/Исследовательские консоли"
#define RND_SUBCATEGORY_COMPUTER_ENGINEERING "/Инженерные и атмосферные консоли"
#define RND_SUBCATEGORY_COMPUTER_CARGO "/Карго консоли"

#define RND_CATEGORY_MACHINE "/Машинные платы"
#define RND_SUBCATEGORY_MACHINE_ATMOS "/Атмосферные устройства"
#define RND_SUBCATEGORY_MACHINE_KITCHEN "/Кухонные устройства"
#define RND_SUBCATEGORY_MACHINE_BAR "/Барные устройства"
#define RND_SUBCATEGORY_MACHINE_BOTANY "/Ботанические устройства"
#define RND_SUBCATEGORY_MACHINE_ENGINEERING "/Инженерные устройства"
#define RND_SUBCATEGORY_MACHINE_RESEARCH "/Исследовательские устройства"
#define RND_SUBCATEGORY_MACHINE_MEDICAL "/Медицинские устройства"
#define RND_SUBCATEGORY_MACHINE_CHEMISTRY "/Химические устройства"
#define RND_SUBCATEGORY_MACHINE_SECURITY "/Устройства отдела безопасности"
#define RND_SUBCATEGORY_MACHINE_CARGO "/Карго устройства"
#define RND_SUBCATEGORY_MACHINE_TELEPORT "/Устройства телепортации"
#define RND_SUBCATEGORY_MACHINE_ROBOTICS "/Устройства робототехники"
#define RND_SUBCATEGORY_MACHINE_GENETICS "/Генетические устройства"
#define RND_SUBCATEGORY_MACHINE_FAB "/Фабрикаторы"
#define RND_SUBCATEGORY_MACHINE_SERVICE "/Сервисные устройства"
#define RND_SUBCATEGORY_MACHINE_TELECOMMS "/Телекоммуникационные устройства"

#define RND_CATEGORY_EQUIPMENT "/Оборудование"
#define RND_SUBCATEGORY_EQUIPMENT_SERVICE "/Сервисное оборудование"
#define RND_SUBCATEGORY_EQUIPMENT_JOKE "/Сверхсекретное оборудование"
#define RND_SUBCATEGORY_EQUIPMENT_CHEMISTRY "/Химическое оборудование"
#define RND_SUBCATEGORY_EQUIPMENT_MEDICAL "/Медицинское оборудование"
#define RND_SUBCATEGORY_EQUIPMENT_SECURITY "/Оборудование отдела безопасности"
#define RND_SUBCATEGORY_EQUIPMENT_TELECOMMS "/Оборудование для связи"
#define RND_SUBCATEGORY_EQUIPMENT_BLUESPACE "/Оборудование для блюспейс"
#define RND_SUBCATEGORY_EQUIPMENT_ENGINEERING "/Инженерное оборудование"
#define RND_SUBCATEGORY_EQUIPMENT_ATMOSPHERICS "/Атмосферное оборудование"
#define RND_SUBCATEGORY_EQUIPMENT_SCIENCE "/Научное оборудование"
#define RND_SUBCATEGORY_EQUIPMENT_GAS_TANKS "/Газовые баллоны"
#define RND_SUBCATEGORY_EQUIPMENT_GAS_TANKS_EQUIPMENT "/Оборудование газовых баллонов"
#define RND_SUBCATEGORY_EQUIPMENT_XENOBIOLOGY "/Оборудование для ксенобиологии"
#define RND_SUBCATEGORY_EQUIPMENT_GENETICS "/Генетическое оборудование"
#define RND_SUBCATEGORY_EQUIPMENT_JANITOR "/Уборочное оборудование"
#define RND_SUBCATEGORY_EQUIPMENT_KITCHEN "/Оборудование для бара и кухни"
#define RND_SUBCATEGORY_EQUIPMENT_MISC "/Разное оборудование"

#define RND_CATEGORY_AI "/Искусственный Интеллект"
#define RND_SUBCATEGORY_AI_CORE "/Конструкция ИИ"
#define RND_SUBCATEGORY_AI_CORE_MODULES "/Основные модули ИИ"
#define RND_SUBCATEGORY_AI_DANGEROUS_MODULES "/Опасные модули ИИ"
#define RND_SUBCATEGORY_AI_LAW_MANIPULATION "/Манипуляция законами ИИ"
#define RND_SUBCATEGORY_AI_MISC "/Разные предметы ИИ"
#define RND_SUBCATEGORY_AI_UPGRADES "/Апгрейды ИИ"

#define RND_CATEGORY_MODULAR_COMPUTERS "/Модульные компьютеры"
#define RND_SUBCATEGORY_MODULAR_COMPUTERS_FRAMES "/Каркасы"
#define RND_SUBCATEGORY_MODULAR_COMPUTERS_PARTS "/Части"

#define RND_CATEGORY_STOCK_PARTS "/Запасные части"
#define RND_SUBCATEGORY_STOCK_PARTS_MISC "/Разные части"
#define RND_SUBCATEGORY_STOCK_PARTS_TURBINE "/Части турбины"
#define RND_SUBCATEGORY_STOCK_PARTS_TELECOMMS "/Части телекоммуникаций"
#define RND_SUBCATEGORY_STOCK_PARTS_1 "/Компоненты 1 уровня"
#define RND_SUBCATEGORY_STOCK_PARTS_2 "/Компоненты 2 уровня"
#define RND_SUBCATEGORY_STOCK_PARTS_3 "/Компоненты 3 уровня"
#define RND_SUBCATEGORY_STOCK_PARTS_4 "/Компоненты 4 уровня"
#define RND_SUBCATEGORY_STOCK_PARTS_EXCHANGERS "/Обменные устройства"

#define RND_CATEGORY_SYNDICATE "/Незаконные конструкции"

#define RND_CATEGORY_EXOSUIT_BOARDS "/Платы экзокостюмов"
#define RND_SUBCATEGORY_EXOSUIT_BOARDS_RIPLEY "/Рипли"
#define RND_SUBCATEGORY_EXOSUIT_BOARDS_ODYSSEUS "/Одиссей"
#define RND_SUBCATEGORY_EXOSUIT_BOARDS_GYGAX "/Гигаакс"
#define RND_SUBCATEGORY_EXOSUIT_BOARDS_DURAND "/Дюранд"
#define RND_SUBCATEGORY_EXOSUIT_BOARDS_HONK "/H.O.N.K."
#define RND_SUBCATEGORY_EXOSUIT_BOARDS_PHAZON "/Фазон"
#define RND_SUBCATEGORY_EXOSUIT_BOARDS_CLARKE "/Кларк"
#define RND_SUBCATEGORY_EXOSUIT_BOARDS_SAVANNAH_IVANOV "/Саванна-Иванов"

#define RND_CATEGORY_MECHFAB_RIPLEY "/Рипли"
#define RND_CATEGORY_MECHFAB_PADDY "/Пэдди"
#define RND_CATEGORY_MECHFAB_ODYSSEUS "/Одиссей"
#define RND_CATEGORY_MECHFAB_GYGAX "/Гигаакс"
#define RND_CATEGORY_MECHFAB_DURAND "/Дюранд"
#define RND_CATEGORY_MECHFAB_HONK "/H.O.N.K."
#define RND_CATEGORY_MECHFAB_PHAZON "/Фазон"
#define RND_CATEGORY_MECHFAB_CLARKE "/Кларк"
#define RND_CATEGORY_MECHFAB_SAVANNAH_IVANOV "/Саванна-Иванов"
#define RND_CATEGORY_MECHFAB_JUSTICE "/Справедливость"
#define RND_SUBCATEGORY_MECHFAB_CHASSIS "/Шасси"
#define RND_SUBCATEGORY_MECHFAB_SUPPORTED_EQUIPMENT "/Поддерживаемое оборудование"
#define RND_SUBCATEGORY_MECHFAB_CONTROL_INTERFACES "/Интерфейсы управления"

#define RND_CATEGORY_MECHFAB_EQUIPMENT "/Оборудование экзокостюмов"
#define RND_SUBCATEGORY_MECHFAB_EQUIPMENT_MINING "/Горное оборудование"
#define RND_SUBCATEGORY_MECHFAB_EQUIPMENT_WEAPONS "/Оружие и боеприпасы"
#define RND_SUBCATEGORY_MECHFAB_EQUIPMENT_MODULES "/Модули брони и ремонта"
#define RND_SUBCATEGORY_MECHFAB_EQUIPMENT_MISC "/Разное"
#define RND_SUBCATEGORY_MECHFAB_EQUIPMENT_MEDICAL "/Медицинское"
#define RND_SUBCATEGORY_MECHFAB_EQUIPMENT_HONK "/Модули ХОНК"
#define RND_SUBCATEGORY_MECHFAB_EQUIPMENT_CONTROL_INTERFACES "/Интерфейсы управления"

#define RND_CATEGORY_MECHFAB_CYBORG "/Киборг"
#define RND_SUBCATEGORY_MECHFAB_CYBORG_CHASSIS "/Шасси киборга"
#define RND_SUBCATEGORY_MECHFAB_CYBORG_COMPONENTS "/Компоненты"
#define RND_SUBCATEGORY_MECHFAB_CYBORG_CELLS "/Энергетические ячейки"
#define RND_SUBCATEGORY_MECHFAB_CYBORG_CONTROL_INTERFACES "/Интерфейсы управления"

#define RND_CATEGORY_MECHFAB_CYBORG_MODULES "/Модули киборга"
#define RND_SUBCATEGORY_MECHFAB_CYBORG_MODULES_ALL "/Все киборги"
#define RND_SUBCATEGORY_MECHFAB_CYBORG_MODULES_MEDICAL "/Медицинские киборги"
#define RND_SUBCATEGORY_MECHFAB_CYBORG_MODULES_ENGINEERING "/Инженерные киборги"
#define RND_SUBCATEGORY_MECHFAB_CYBORG_MODULES_JANITOR "/Уборочные киборги"
#define RND_SUBCATEGORY_MECHFAB_CYBORG_MODULES_SECURITY "/Охранные киборги"
#define RND_SUBCATEGORY_MECHFAB_CYBORG_MODULES_MINING "/Горные киборги"
#define RND_SUBCATEGORY_MECHFAB_CYBORG_MODULES_SERVICE "/Сервисные киборги"

#define RND_CATEGORY_MODSUITS "/МОД Костюмы"
#define RND_SUBCATEGORY_MODUITS_CHASSIS "/Шасси"
#define RND_SUBCATEGORY_MODSUITS_PLATING "/Обшивка"
#define RND_SUBCATEGORY_MODSUITS_MISC "/Разное"

#define RND_CATEGORY_MODSUIT_MODULES "/МОД Модули"
#define RND_SUBCATEGORY_MODSUIT_MODULES_GENERAL "/Общие модули"
#define RND_SUBCATEGORY_MODSUIT_MODULES_ENGINEERING "/Инженерные модули"
#define RND_SUBCATEGORY_MODSUIT_MODULES_MEDICAL "/Медицинские модули"
#define RND_SUBCATEGORY_MODSUIT_MODULES_SCIENCE "/Научные модули"
#define RND_SUBCATEGORY_MODSUIT_MODULES_SECURITY "/Охранные модули"
#define RND_SUBCATEGORY_MODSUIT_MODULES_SUPPLY "/Модули снабжения"
#define RND_SUBCATEGORY_MODSUIT_MODULES_SERVICE "/Сервисные модули"

#define RND_CATEGORY_CYBERNETICS "/Кибернетика"
#define RND_SUBCATEGORY_CYBERNETICS_ORGANS_1 "/Кибернетические органы 1 уровня"
#define RND_SUBCATEGORY_CYBERNETICS_ORGANS_2 "/Кибернетические органы 2 уровня"
#define RND_SUBCATEGORY_CYBERNETICS_ORGANS_3 "/Кибернетические органы 3 уровня"
#define RND_SUBCATEGORY_CYBERNETICS_ORGANS_COMBAT "/Боевые кибернетические органы"
#define RND_SUBCATEGORY_CYBERNETICS_ORGANS_MISC "/Разные кибернетические органы"
#define RND_SUBCATEGORY_CYBERNETICS_IMPLANTS_COMBAT "/Боевые кибернетические импланты"
#define RND_SUBCATEGORY_CYBERNETICS_IMPLANTS_HEALTH "/Кибернетические импланты здоровья"
#define RND_SUBCATEGORY_CYBERNETICS_IMPLANTS_TOOLS "/Инструменты для кибернетических имплантов"
#define RND_SUBCATEGORY_CYBERNETICS_IMPLANTS_UTILITY "/Кибернетические утилитарные импланты"
#define RND_SUBCATEGORY_CYBERNETICS_IMPLANTS_MISC "/Разные кибернетические импланты"
#define RND_SUBCATEGORY_CYBERNETICS_IMPLANTS_SECURITY "/Кибернетические импланты безопасности"
#define RND_SUBCATEGORY_CYBERNETICS_ADVANCED_LIMBS "/Кибернетические продвинутые конечности"

// Категории конечностей
#define RND_CATEGORY_LIMBS_DIGITIGRADE "диджитиградные"
#define RND_CATEGORY_LIMBS_OTHER "Другие конечности"

// Категории биогенераторов
#define RND_CATEGORY_BIO_FOOD "Еда"
#define RND_CATEGORY_BIO_CHEMICALS "Химикаты"
#define RND_CATEGORY_BIO_MATERIALS "Материалы"

// Мета категории
#define RND_CATEGORY_INITIAL "начальная"
#define RND_CATEGORY_HACKED "взломанная"
#define RND_CATEGORY_IMPORTED "/Импортированные дизайны"
