
/obj/machinery/mineral/equipment_vendor/RedeemVoucher(obj/item/mining_voucher/voucher, mob/redeemer)
	var/items = list("Survival Capsule and Explorer's Webbing", "Resonator and Advanced Scanner", "Mining Drone", "Extraction and Rescue Kit", "Crusher Kit", "Mining Conscription Kit", "Mecha Plasma Cutter")

	var/selection = input(redeemer, "Pick your equipment", "Mining Voucher Redemption") as null|anything in items
	if(!selection || !Adjacent(redeemer) || QDELETED(voucher) || voucher.loc != redeemer)
		return
	switch(selection)
		if("Survival Capsule and Explorer's Webbing")
			new /obj/item/storage/belt/mining/vendor(src.loc)
		if("Resonator and Advanced Scanner")
			new /obj/item/resonator(src.loc)
			new /obj/item/device/t_scanner/adv_mining_scanner(src.loc)
		if("Mining Drone")
			new /mob/living/simple_animal/hostile/mining_drone(src.loc)
			new /obj/item/weldingtool/hugetank(src.loc)
			new /obj/item/clothing/glasses/welding(src.loc)
		if("Extraction and Rescue Kit")
			new /obj/item/extraction_pack(loc)
			new /obj/item/fulton_core(loc)
			new /obj/item/stack/marker_beacon/thirty(loc)
		if("Crusher Kit")
			new /obj/item/twohanded/required/kinetic_crusher(loc)
			new /obj/item/storage/belt/mining/alt(loc)
			new /obj/item/extinguisher/mini(loc)
		if("Mining Conscription Kit")
			new /obj/item/storage/backpack/duffelbag/mining_conscript(loc)
		if("Mecha Plasma Cutter")
			new /obj/item/mecha_parts/mecha_equipment/weapon/energy/plasma(loc)
			new /obj/item/weldingtool/hugetank(src.loc)
			new /obj/item/clothing/glasses/welding(src.loc)

	SSblackbox.record_feedback("tally", "mining_voucher_redeemed", 1, selection)
	qdel(voucher)