#define VERB_SUBCATEGORY_ADMIN(CATEGORY) "Admin." + CATEGORY

#define VERB_CATEGORY_ADMIN "Admin"
#define VERB_CATEGORY_EVENTS VERB_SUBCATEGORY_ADMIN("Events")
#define VERB_CATEGORY_FUN VERB_SUBCATEGORY_ADMIN("Fun")
#define VERB_CATEGORY_GAME VERB_SUBCATEGORY_ADMIN("Game")

#define VERB_CATEGORY_DEBUG "Debug"
#define VERB_CATEGORY_MAPPING "Mapping"
#define VERB_CATEGORY_SERVER "Server"
