#define ANTAG_DATUM_CULT				/datum/antagonist/cult
#define ANTAG_DATUM_CULT_MASTER			/datum/antagonist/cult/master
#define ANTAG_DATUM_CLOCKCULT			/datum/antagonist/clockcult
#define ANTAG_DATUM_CLOCKCULT_SILENT	/datum/antagonist/clockcult/silent
#define ANTAG_DATUM_DEVIL				/datum/antagonist/devil
#define ANTAG_DATUM_NINJA				/datum/antagonist/ninja
#define ANTAG_DATUM_NINJA_FRIENDLY		/datum/antagonist/ninja/friendly
#define ANTAG_DATUM_NINJA_RANDOM		/datum/antagonist/ninja/randomAllegiance/
#define ANTAG_DATUM_TRAITOR 			/datum/antagonist/traitor
#define ANTAG_DATUM_TRAITOR_CUSTOM 		/datum/antagonist/traitor/custom
#define ANTAG_DATUM_TRAITOR_HUMAN		/datum/antagonist/traitor/human
#define ANTAG_DATUM_TRAITOR_HUMAN_CUSTOM	/datum/antagonist/traitor/human/custom
#define ANTAG_DATUM_TRAITOR_AI			/datum/antagonist/traitor/AI
#define ANTAG_DATUM_TRAITOR_AI_CUSTOM		/datum/antagonist/traitor/AI/custom
#define ANTAG_DATUM_IAA				/datum/antagonist/traitor/internal_affairs
#define ANTAG_DATUM_IAA_CUSTOM			/datum/antagonist/traitor/internal_affairs/custom
#define ANTAG_DATUM_IAA_HUMAN	  		/datum/antagonist/traitor/human/internal_affairs
#define ANTAG_DATUM_IAA_HUMAN_CUSTOM  		/datum/antagonist/traitor/human/internal_affairs/custom
#define ANTAG_DATUM_IAA_AI_CUSTOM  		/datum/antagonist/traitor/AI/internal_affairs/custom
#define ANTAG_DATUM_IAA_AI	  		/datum/antagonist/traitor/AI/internal_affairs
