#define ANTAG_DATUM_CULT				/datum/antagonist/cult
#define ANTAG_DATUM_CULT_MASTER			/datum/antagonist/cult/master
#define ANTAG_DATUM_CLOCKCULT			/datum/antagonist/clockcult
#define ANTAG_DATUM_CLOCKCULT_SILENT	/datum/antagonist/clockcult/silent
#define ANTAG_DATUM_DEVIL				/datum/antagonist/devil
#define ANTAG_DATUM_NINJA				/datum/antagonist/ninja
#define ANTAG_DATUM_TRAITOR 			/datum/antagonist/traitor
#define ANTAG_DATUM_TRAITOR_HUMAN		/datum/antagonist/traitor/human
#define ANTAG_DATUM_TRAITOR_AI			/datum/antagonist/traitor/AI
#define ANTAG_DATUM_IAA					/datum/antagonist/traitor/internal_affairs
#define ANTAG_DATUM_IAA_HUMAN	  		/datum/antagonist/traitor/human/internal_affairs
#define ANTAG_DATUM_IAA_AI	  			/datum/antagonist/traitor/AI/internal_affairs
#define ANTAG_DATUM_BROTHER 			/datum/antagonist/brother
#define ANTAG_DATUM_ABDUCTOR 			/datum/antagonist/abductor
#define ANTAG_DATUM_ABDUCTOR_SCIENTIST 	/datum/antagonist/abductor/scientist
#define ANTAG_DATUM_ABDUCTOR_AGENT 		/datum/antagonist/abductor/agent
#define ANTAG_DATUM_MONKEY				/datum/antagonist/monkey
#define ANTAG_DATUM_MONKEY_LEADER		/datum/antagonist/monkey/leader
#define ANTAG_DATUM_DARKSPAWN			/datum/antagonist/darkspawn
#define NUKE_RESULT_FLUKE 0
#define NUKE_RESULT_NUKE_WIN 1
#define NUKE_RESULT_CREW_WIN 2
#define NUKE_RESULT_CREW_WIN_SYNDIES_DEAD 3
#define NUKE_RESULT_DISK_LOST 4
#define NUKE_RESULT_DISK_STOLEN 5
#define NUKE_RESULT_NOSURVIVORS 6
#define NUKE_RESULT_WRONG_STATION 7
#define NUKE_RESULT_WRONG_STATION_DEAD 8

#define APPRENTICE_DESTRUCTION "destruction"
#define APPRENTICE_BLUESPACE "bluespace"
#define APPRENTICE_ROBELESS "robeless"
#define APPRENTICE_HEALING "healing"