// Attack visual effects
#define ATTACK_EFFECT_PUNCH     "punch"
#define ATTACK_EFFECT_KICK      "kick"
#define ATTACK_EFFECT_SMASH     "smash"
#define ATTACK_EFFECT_CLAW      "claw"
#define ATTACK_EFFECT_DISARM    "disarm"
#define ATTACK_EFFECT_BITE      "bite"
#define ATTACK_EFFECT_MECHFIRE  "mech_fire"
#define ATTACK_EFFECT_MECHTOXIN	"mech_toxin"
#define ATTACK_EFFECT_BOOP      "boop"
