#define BITMINING_COST_NONE 0
#define BITMINING_COST_LOW 1
#define BITMINING_COST_MEDIUM 2
#define BITMINING_COST_HIGH 3
#define BITMINING_COST_EXTREME 20

/// Rewards formula: (1 + rewards_points) * ORE_MULTIPLIER

#define BITMINING_REWARD_MIN 1
#define BITMINING_REWARD_LOW 2
#define BITMINING_REWARD_MEDIUM 3
#define BITMINING_REWARD_HIGH 4
#define BITMINING_REWARD_EXTREME 5

/// Blue in ui
#define BITMINING_DIFFICULTY_NONE 0
/// Yellow
#define BITMINING_DIFFICULTY_LOW 1
/// Orange
#define BITMINING_DIFFICULTY_MEDIUM 2
/// Red with skull
#define BITMINING_DIFFICULTY_HIGH 3
