#define BITRUNNER_COST_NONE 0
#define BITRUNNER_COST_LOW 1
#define BITRUNNER_COST_MEDIUM 2
#define BITRUNNER_COST_HIGH 3
#define BITRUNNER_COST_EXTREME 20

#define BITRUNNER_REWARD_MIN 1
#define BITRUNNER_REWARD_LOW 3
#define BITRUNNER_REWARD_MEDIUM 4
#define BITRUNNER_REWARD_HIGH 5
#define BITRUNNER_REWARD_EXTREME 6

/// Blue in ui
#define BITRUNNER_DIFFICULTY_NONE 0
/// Yellow
#define BITRUNNER_DIFFICULTY_LOW 1
/// Orange
#define BITRUNNER_DIFFICULTY_MEDIUM 2
/// Red with skull
#define BITRUNNER_DIFFICULTY_HIGH 3
