///The standard amount of bodyparts a carbon has. Currently 6, HEAD/L_ARM/R_ARM/CHEST/L_LEG/R_LEG
#define BODYPARTS_DEFAULT_MAXIMUM 6

#define PROSTHESIS_MAX_HP 20

#define AUGGED_LIMB_EMP_BRUTE_DAMAGE 2
#define AUGGED_LIMB_EMP_BURN_DAMAGE 1.5

#define AUGGED_LIMB_EMP_PARALYZE_TIME (3 SECONDS)

#define AUGGED_LEG_EMP_KNOCKDOWN_TIME (3 SECONDS)
#define AUGGED_CHEST_EMP_STUN_TIME (3 SECONDS)
#define AUGGED_CHEST_EMP_SHAKE_TIME (5 SECONDS)
#define AUGGED_HEAD_EMP_GLITCH_DURATION (6 SECONDS)
