#define CONTRACT_POWER 1
#define CONTRACT_WEALTH 2
#define CONTRACT_PRESTIGE 3
#define CONTRACT_MAGIC 4
#define CONTRACT_SLAVE 5
#define CONTRACT_REVIVE 6
#define CONTRACT_KNOWLEDGE 7
#define CONTRACT_UNWILLING 8

