#define CONTRACT_POWER 1
#define CONTRACT_WEALTH 2
#define CONTRACT_PRESTIGE 3
#define CONTRACT_MAGIC 4
#define CONTRACT_REVIVE 5
#define CONTRACT_KNOWLEDGE 6
#define CONTRACT_UNWILLING 7

#define BANE_SALT 1
#define BANE_LIGHT 2
#define BANE_IRON 3
#define BANE_WHITECLOTHES 4
#define BANE_SILVER 5
#define BANE_HARVEST 6
#define BANE_TOOLBOX 7

#define OBLIGATION_FOOD 1
#define OBLIGATION_DRINK 2
#define OBLIGATION_GREET 3
#define OBLIGATION_PRESENCEKNOWN 4
#define OBLIGATION_SAYNAME 5
#define OBLIGATION_ANNOUNCEKILL 6
#define OBLIGATION_ANSWERTONAME 7

#define BAN_HURTWOMAN 1
#define BAN_CHAPEL 2
#define BAN_HURTPRIEST 3
#define BAN_AVOIDWATER 4
#define BAN_STRIKEUNCONCIOUS 5
#define BAN_HURTLIZARD 6
#define BAN_HURTANIMAL 7

#define BANISH_WATER 1
#define BANISH_COFFIN 2
#define BANISH_FORMALDYHIDE 3
#define BANISH_RUNES 4
#define BANISH_CANDLES 5
#define BANISH_DESTRUCTION 6
#define BANISH_FUNERAL_GARB 7