//the IDs of crusher trophies
#define TROPHY_WATCHER "trophy watcher"
#define TROPHY_BEAR_PAW "trophy bear paw"
#define TROPHY_LOBSTER_CLAW "trophy lobster claw"
#define TROPHY_ICE_DEMON "trophy ice cube"
#define TROPHY_GOLIATH_TENTACLE "trophy goliath tentacle"
#define TROPHY_BRIMDEMON_FANG "trophy brimdemon fang"
#define TROPHY_BLASTER_TUBES "trophy blaster tubes"
#define TROPHY_WOLF_EAR "trophy wolf ear"
#define TROPHY_MINER_EYE "trophy miner eye"
#define TROPHY_TAIL_SPIKE "trophy tail spike"
#define TROPHY_VORTEX "trophy vortex"
#define TROPHY_ICE_BLOCK "trophy ice block"
#define TROPHY_BROOD_TONGUE "trophy brood tongue"
#define TROPHY_DEMON_CLAWS "trophy demon claws"
#define TROPHY_LEGIONNAIRE_SPINE "trophy legionnaire spine"
#define TROPHY_RAPTOR_FEATHER "trophy raptor feather"
