#define SUCCESSFUL_SPAWN 2
#define NOT_ENOUGH_PLAYERS 3
#define MAP_ERROR 4
#define WAITING_FOR_SOMETHING 5

#define EVENT_CANT_RUN 0
#define EVENT_READY 1
#define EVENT_CANCELLED 2

#define DEAD_WEIGHT_LOW 0.03
#define DEAD_WEIGHT_MEDIUM 0.05
#define DEAD_WEIGHT_HIGH 0.07
