#define BORG_MODULE_SECURITY 		(1<<0)
#define BORG_MODULE_MINER			(1<<1)
#define BORG_MODULE_JANITOR			(1<<2)
#define BORG_MODULE_MEDICAL			(1<<3)
#define BORG_MODULE_ENGINEERING		(1<<4)

#define EXOSUIT_MODULE_RIPLEY		(1<<0)
#define EXOSUIT_MODULE_ODYSSEUS		(1<<1)
#define EXOSUIT_MODULE_CLARKE		(1<<2)
#define EXOSUIT_MODULE_GYGAX		(1<<3)
#define EXOSUIT_MODULE_DURAND		(1<<4)
#define EXOSUIT_MODULE_HONK			(1<<5)
#define EXOSUIT_MODULE_PHAZON		(1<<6)

#define EXOSUIT_MODULE_WORKING		EXOSUIT_MODULE_RIPLEY | EXOSUIT_MODULE_CLARKE
#define EXOSUIT_MODULE_COMBAT		EXOSUIT_MODULE_GYGAX | EXOSUIT_MODULE_HONK | EXOSUIT_MODULE_DURAND | EXOSUIT_MODULE_PHAZON
#define EXOSUIT_MODULE_MEDICAL		EXOSUIT_MODULE_ODYSSEUS
