#define HOLOMAP_FILTER_DEATHSQUAD				1
#define HOLOMAP_FILTER_ERT						2
#define HOLOMAP_FILTER_NUKEOPS					4
#define HOLOMAP_FILTER_ELITESYNDICATE			8
#define HOLOMAP_FILTER_STATIONMAP				16
#define HOLOMAP_FILTER_STATIONMAP_STRATEGIC		32 //features markers over the captain's office, the armory, the SMES
#define HOLOMAP_FILTER_CLOCKCULT				64

#define HOLOMAP_AREACOLOR_COMMAND		"#447FC299"
#define HOLOMAP_AREACOLOR_SECURITY		"#AE121299"
#define HOLOMAP_AREACOLOR_MEDICAL		"#35803099"
#define HOLOMAP_AREACOLOR_SCIENCE		"#A154A699"
#define HOLOMAP_AREACOLOR_ENGINEERING	"#F1C23199"
#define HOLOMAP_AREACOLOR_CARGO			"#E06F0099"
#define HOLOMAP_AREACOLOR_HALLWAYS		"#FFFFFF66"
#define HOLOMAP_AREACOLOR_ARRIVALS		"#0000FFCC"
#define HOLOMAP_AREACOLOR_ESCAPE		"#FF0000CC"

#define HOLOMAP_AREACOLOR_REEBE		"#ffcc00"

#define HOLOMAP_EXTRA_STATIONMAP				"stationmapformatted"
#define HOLOMAP_EXTRA_STATIONMAP_STRATEGIC		"stationmapstrategic"
#define HOLOMAP_EXTRA_STATIONMAPAREAS			"stationareas"
#define HOLOMAP_EXTRA_STATIONMAPSMALL_NORTH		"stationmapsmallnorth"
#define HOLOMAP_EXTRA_STATIONMAPSMALL_SOUTH		"stationmapsmallsouth"
#define HOLOMAP_EXTRA_STATIONMAPSMALL_EAST		"stationmapsmalleast"
#define HOLOMAP_EXTRA_STATIONMAPSMALL_WEST		"stationmapsmallwest"

#define HOLOMAP_MARKER_SMES				"smes"
#define HOLOMAP_MARKER_DISK				"diskspawn"
#define HOLOMAP_MARKER_SYNDISHUTTLE		"syndishuttle"

#define HOLOMAP_OBSTACLE	"#FFFFFFDD"
#define HOLOMAP_PATH		"#66666699"