#define JOB_AVAILABLE 0
#define JOB_UNAVAILABLE_GENERIC 1
#define JOB_UNAVAILABLE_BANNED 2
#define JOB_UNAVAILABLE_PLAYTIME 3
#define JOB_UNAVAILABLE_ACCOUNTAGE 4
#define JOB_UNAVAILABLE_SLOTFULL 5

#define DEFAULT_RELIGION "Christianity"
#define DEFAULT_DEITY "Space Jesus"

#define JOB_DISPLAY_ORDER_DEFAULT 0

#define JOB_DISPLAY_ORDER_ASSISTANT 1
#define JOB_DISPLAY_ORDER_CAPTAIN 2
#define JOB_DISPLAY_ORDER_HEAD_OF_PERSONNEL 3
#define JOB_DISPLAY_ORDER_QUARTERMASTER 4
#define JOB_DISPLAY_ORDER_CARGO_TECHNICIAN 5
#define JOB_DISPLAY_ORDER_SHAFT_MINER 6
#define JOB_DISPLAY_ORDER_BARTENDER 7
#define JOB_DISPLAY_ORDER_HEAD_OF_SERVICE 8
#define JOB_DISPLAY_ORDER_COOK 9
#define JOB_DISPLAY_ORDER_BOTANIST 10
#define JOB_DISPLAY_ORDER_JANITOR 11
#define JOB_DISPLAY_ORDER_CLOWN 12
#define JOB_DISPLAY_ORDER_MIME 13
#define JOB_DISPLAY_ORDER_CURATOR 14
#define JOB_DISPLAY_ORDER_LAWYER 15
#define JOB_DISPLAY_ORDER_CHAPLAIN 16
#define JOB_DISPLAY_ORDER_AI 17
#define JOB_DISPLAY_ORDER_CYBORG 18
#define JOB_DISPLAY_ORDER_CHIEF_ENGINEER 19
#define JOB_DISPLAY_ORDER_STATION_ENGINEER 20
#define JOB_DISPLAY_ORDER_ATMOSPHERIC_TECHNICIAN 21
#define JOB_DISPLAY_ORDER_CHIEF_MEDICAL_OFFICER 22
#define JOB_DISPLAY_ORDER_MEDICAL_DOCTOR 23
#define JOB_DISPLAY_ORDER_PARAMEDIC 24
#define JOB_DISPLAY_ORDER_CHEMIST 25
#define JOB_DISPLAY_ORDER_VIROLOGIST 26
#define JOB_DISPLAY_ORDER_PSYCHOLOGIST 27
#define JOB_DISPLAY_ORDER_RESEARCH_DIRECTOR 28
#define JOB_DISPLAY_ORDER_SCIENTIST 29
#define JOB_DISPLAY_ORDER_ROBOTICIST 30
#define JOB_DISPLAY_ORDER_GENETICIST 31
#define JOB_DISPLAY_ORDER_HEAD_OF_SECURITY 32
#define JOB_DISPLAY_ORDER_WARDEN 33
#define JOB_DISPLAY_ORDER_DETECTIVE 34
#define JOB_DISPLAY_ORDER_SECURITY_OFFICER 35
#define JOB_DISPLAY_ORDER_PRISONER 36