#define LAZY_TEMPLATE_KEY_NUKIEBASE "LT_NUKIEBASE"
#define LAZY_TEMPLATE_KEY_WIZARDDEN "LT_WIZARDDEN"
#define LAZY_TEMPLATE_KEY_LIST_ALL list( \
	"Nukie Base" = LAZY_TEMPLATE_KEY_NUKIEBASE, \
	"Wizard Den" = LAZY_TEMPLATE_KEY_WIZARDDEN, \
)
