#define LAZY_TEMPLATE_KEY_NUKIEELEVATOR "LT_NUKIEELEVATOR"
#define LAZY_TEMPLATE_KEY_NUKIEBASE "LT_NUKIEBASE"
#define LAZY_TEMPLATE_KEY_WIZARDDEN "LT_WIZARDDEN"
#define LAZY_TEMPLATE_KEY_NINJA_HOLDING_FACILITY "LT_NINJAHOLDING"
#define LAZY_TEMPLATE_KEY_ABDUCTOR_SHIPS "LT_ABDUCTORSHIPS"
#define LAZY_TEMPLATE_KEY_HERETIC_SACRIFICE "LT_HERETICSACRIFICE"
#define LAZY_TEMPLATE_KEY_VOIDWALKER_VOID "LT_VOIDWALKERVOID"
// Troutstation edit
#define LAZY_TEMPLATE_KEY_FLOCK_OUTPOST "LT_FLOCKOUTPOST"

#define LAZY_TEMPLATE_KEY_LIST_ALL(...) list( \
	"Nukie Elevator" = LAZY_TEMPLATE_KEY_NUKIEELEVATOR, \
	"Nukie Base" = LAZY_TEMPLATE_KEY_NUKIEBASE, \
	"Wizard Den" = LAZY_TEMPLATE_KEY_WIZARDDEN, \
	"Ninja Holding" = LAZY_TEMPLATE_KEY_NINJA_HOLDING_FACILITY, \
	"Abductor Ships" = LAZY_TEMPLATE_KEY_ABDUCTOR_SHIPS, \
	"Heretic Sacrifice Level" = LAZY_TEMPLATE_KEY_HERETIC_SACRIFICE, \
	"Voidwalker Void" = LAZY_TEMPLATE_KEY_VOIDWALKER_VOID, \
	"Flock Outpost" = LAZY_TEMPLATE_KEY_FLOCK_OUTPOST, \
)
// Troutstation edit - added Flock Outpost (can't put comment inside a define)
