//Investigate logging defines
#define INVESTIGATE_ATMOS	         "atmos"
#define INVESTIGATE_BOTANY 	         "botany"
#define INVESTIGATE_CARGO 	         "cargo"
#define INVESTIGATE_EXPERIMENTOR 	 "experimentor"
#define INVESTIGATE_GRAVITY 	     "gravity"
#define INVESTIGATE_RECORDS 	     "records"
#define INVESTIGATE_SINGULO          "singulo"
#define INVESTIGATE_SUPERMATTER      "supermatter"
#define INVESTIGATE_TELESCI          "telesci"
#define INVESTIGATE_WIRES            "wires"
#define INVESTIGATE_PORTAL			"portals"
#define INVESTIGATE_HALLUCINATIONS   "hallucinations"

//Individual logging defines
#define INDIVIDUAL_ATTACK_LOG   "Attack log"
#define INDIVIDUAL_SAY_LOG      "Say log"
#define INDIVIDUAL_EMOTE_LOG    "Emote log"
#define INDIVIDUAL_OOC_LOG      "OOC log"
#define INDIVIDUAL_SHOW_ALL_LOG "All logs"
