#define MOVESPEED_DATA_INDEX_PRIORITY 1
#define MOVESPEED_DATA_INDEX_FLAGS 2
#define MOVESPEED_DATA_INDEX_MULTIPLICATIVE_SLOWDOWN 3
#define MOVESPEED_DATA_INDEX_MOVETYPE 4

#define MOVESPEED_DATA_INDEX_MAX 4

//flags - Note that requires overrides ignore.
#define MOVESPEED_MODIFIER_IGNORES_NOSLOW			(1 << 0)			//Modifier is not ignored when noslow is active.
#define MOVESPEED_MODIFIER_REQUIRES_GRAVITY			(1 << 1)			//Modifier only works with gravity active.
#define MOVESPEED_MODIFIER_NO_GRAVITY				(1 << 2)			//Modifier does not work with gravity inactive.
#define MOVESPEED_MODIFIER_REQUIRES_FLIGHT			(1 << 3)			//Modifier only works with flight active.
#define MOVESPEED_MODIFIER_NO_FLIGHT				(1 << 4)			//Modifier does not work flight active.

#define MOVESPEED_MODIFIER_FLAGS_DEFAULT_POSITIVE (MOVESPEED_MODIFIER_IGNORES_NOSLOW | MOVESPEED_MODIFIER_REQUIRES_GRAVITY)
#define MOVESPEED_MODIFIER_FLAGS_DEFAULT_NEGATIVE (MOVESPEED_MODIFIER_REQUIRES_GRAVITY)
#define MOVESPEED_MODIFIER_FLAGS_AUTO(_AMOUNT_MULTIPLICATIVE) (_AMOUNT_MULTIPLICATIVE > 0? MOVESPEED_MODIFIER_FLAGS_DEFAULT_NEGATIVE : MOVESPEED_MODIFIER_FLAGS_DEFAULT_POSITIVe)

//ids

#define MOVESPEED_ID_MOB_WALK_RUN_CONFIG_SPEED			"MOB_WALK_RUN"
#define MOVESPEED_ID_CONFIG_SPEEDMOD					"MOB_CONFIG_MODIFIER"

#define MOVESPEED_ID_SLIME_REAGENTMOD					"SLIME_REAGENT_MODIFIER"
#define MOVESPEED_ID_SLIME_HEALTHMOD					"SLIME_HEALTH_MODIFIER"
#define MOVESPEED_ID_SLIME_TEMPMOD						"SLIME_TEMPERATURE_MODIFIER"

#define MOVESPEED_ID_LIVING_TURF_SPEEDMOD				"LIVING_TURF_SPEEDMOD"

#define MOVESPEED_ID_CARBON_SOFTCRIT					"CARBON_SOFTCRIT"
#define MOVESPEED_ID_CARBON_OLDSPEED					"CARBON_DEPRECATED_SPEED"
#define MOVESPEED_ID_CARBON_CRAWLING					"CARBON_CRAWLING"
#define MOVESPEED_ID_CARBON_LIMB						"CARBON_LIMB"

#define MOVESPEED_ID_HUMAN_ITEM							"HUMAN_ITEM"
#define MOVESPEED_ID_HUMAN_TRAIT						"HUMAN_TRAIT"
#define MOVESPEED_ID_

#define MOVESPEED_ID_MONKEY_REAGENT_SPEEDMOD			"MONKEY_REAGENT_SPEEDMOD"
#define MOVESPEED_ID_MONKEY_TEMPERATURE_SPEEDMOD		"MONKEY_TEMPERATURE_SPEEDMOD"
#define MOVESPEED_ID_MONKEY_HEALTH_SPEEDMOD				"MONKEY_HEALTH_SPEEDMOD"

#define MOVESPEED_ID_SIMPLEMOB_VARSPEED					"SIMPLEMOB_VARSPEED_MODIFIER"
#define MOVESPEED_ID_ADMIN_VAREDIT						"ADMIN_VAREDIT_MODIFIER"

#define MOVESPEED_ID_PAI_SPACEWALK_SPEEDMOD				"PAI_SPACEWALK_MODIFIER"

#define MOVESPEED_ID_SANITY								"MOOD_SANITY"

#define MOVESPEED_ID_SPECIES							"SPECIES_SPEED_MOD"
