#define MOVESPEED_DATA_INDEX_PRIORITY 1
#define MOVESPEED_DATA_INDEX_FLAGS 2
#define MOVESPEED_DATA_INDEX_MULTIPLICATIVE_SLOWDOWN 3
#define MOVESPEED_DATA_INDEX_MOVETYPE 4

#define MOVESPEED_DATA_INDEX_MAX 4

//flags
#define IGNORE_NOSLOW	(1 << 0)

//ids

#define MOVESPEED_ID_MOB_WALK_RUN_CONFIG_SPEED			"MOB_WALK_RUN"
#define MOVESPEED_ID_CONFIG_SPEEDMOD					"MOB_CONFIG_MODIFIER"

#define MOVESPEED_ID_SLIME_REAGENTMOD					"SLIME_REAGENT_MODIFIER"
#define MOVESPEED_ID_SLIME_HEALTHMOD					"SLIME_HEALTH_MODIFIER"
#define MOVESPEED_ID_SLIME_TEMPMOD						"SLIME_TEMPERATURE_MODIFIER"

#define MOVESPEED_ID_LIVING_TURF_SPEEDMOD				"LIVING_TURF_SPEEDMOD"

#define MOVESPEED_ID_CARBON_SOFTCRIT					"CARBON_SOFTCRIT"
#define MOVESPEED_ID_CARBON_OLDSPEED					"CARBON_DEPRECATED_SPEED"
#define MOVESPEED_ID_CARBON_CRAWLING					"CARBON_CRAWLING"

#define MOVESPEED_ID_MONKEY_REAGENT_SPEEDMOD			"MONKEY_REAGENT_SPEEDMOD"
#define MOVESPEED_ID_MONKEY_TEMPERATURE_SPEEDMOD		"MONKEY_TEMPERATURE_SPEEDMOD"
#define MOVESPEED_ID_MONKEY_HEALTH_SPEEDMOD				"MONKEY_HEALTH_SPEEDMOD"

#define MOVESPEED_ID_SIMPLEMOB_VARSPEED					"SIMPLEMOB_VARSPEED_MODIFIER"
#define MOVESPEED_ID_ADMIN_VAREDIT						"ADMIN_VAREDIT_MODIFIER"

#define MOVESPEED_ID_PAI_SPACEWALK_SPEEDMOD				"PAI_SPACEWALK_MODIFIER"

#define MOVESPEED_ID_SANITY								"MOOD_SANITY"