#define NANITE_TIMER_DEACTIVATE 1
#define NANITE_TIMER_SELFDELETE 2
#define NANITE_TIMER_TRIGGER 3
#define NANITE_TIMER_RESET 4

#define NANITE_SYNC_DELAY 300

#define NANITE_SHOCK_IMMUNE 1
#define NANITE_EMP_IMMUNE 2

#define NANITE_PROGRAM_LIMIT 20