#define PATHFINDING_QUEUE_MOBS			"mobs"
#define PATHFINDING_QUEUE_DEFAULT		"default"

#define PATHFIND_FAIL_QUEUE_FULL			"QUEUE_FULL"
#define PATHFIND_FAIL_NO_START_TURF			"START_TURF_MISSING"
#define PATHFIND_FAIL_NO_END_TURF			"END_TURF_MISSING"
