#define POWER_BAR_DEPARTMENT_COMMON "common"
#define POWER_BAR_DEPARTMENT_CARGO "cargo"
#define POWER_BAR_DEPARTMENT_ENGINEERING "engineering"
#define POWER_BAR_DEPARTMENT_MEDICAL "medical"
#define POWER_BAR_DEPARTMENT_SCIENCE "science"
#define POWER_BAR_DEPARTMENT_SECURITY "security"

#define POWER_BAR_DONT_REACT (1 << 0)

// Feature flags to be flipped in TGS for live configuration
#define POWER_BAR_FLAG(flag) (max(-1, ##flag) == -1 ? (DEFAULT_##flag) : UNLINT(##flag))

#define DEFAULT_FFLAG_OVERCLOCK_USES_SLEEP TRUE
#ifndef FFLAG_OVERCLOCK_USES_SLEEP
#define FFLAG_OVERCLOCK_USES_SLEEP
#endif

#define DEFAULT_FFLAG_OVERCLOCK_TIME_SPENT (4 SECONDS)
#ifndef FFLAG_OVERCLOCK_TIME_SPENT
#define FFLAG_OVERCLOCK_TIME_SPENT
#endif

#define DEFAULT_FFLAG_DEFAULT_SINGULO_ENERGY 800
#ifndef FFLAG_DEFAULT_SINGULO_ENERGY
#define FFLAG_DEFAULT_SINGULO_ENERGY
#endif

#define DEFAULT_FFLAG_OVERCLOCK_MAX_OVERCLOCK_DAMAGE 0.29
#ifndef FFLAG_OVERCLOCK_MAX_OVERCLOCK_DAMAGE
#define FFLAG_OVERCLOCK_MAX_OVERCLOCK_DAMAGE
#endif

#define DEFAULT_FFLAG_OVERCLOCK_NECESSARY_HEALTH 0.8
#ifndef FFLAG_OVERCLOCK_NECESSARY_HEALTH
#define FFLAG_OVERCLOCK_NECESSARY_HEALTH
#endif

#define DEFAULT_FFLAG_INITIAL_OVERCLOCK_DELAY (10 SECONDS)
#ifndef FFLAG_INITIAL_OVERCLOCK_DELAY
#define FFLAG_INITIAL_OVERCLOCK_DELAY
#endif

#define DEFAULT_FFLAG_ADDED_OVERCLOCK_DELAY (5 SECONDS)
#ifndef FFLAG_ADDED_OVERCLOCK_DELAY
#define FFLAG_ADDED_OVERCLOCK_DELAY
#endif
