#define VERY_LOW_RESISTANCE 250
#define LOW_RESISTANCE 500
#define MED_RESISTANCE 1000
#define HIGH_RESISTANCE 2000
#define VERY_HIGH_RESISTANCE 4000

#define BIPOLAR_SAD "sad"
#define BIPOLAR_HAPPY "happy"
