#define RAD_VERY_LIGHT_INSULATION 0.5			//What girders have
#define RAD_LIGHT_INSULATION 0.4
#define RAD_MEDIUM_INSULATION  0.3				//What common walls have
#define RAD_HEAVY_INSULATION 0.2
#define RAD_EXTREME_INSULATION 0.01
#define RAD_FULL_INSULATION 0

#define RAD_HALF_LIFE 300
#define RAD_MINIMUM_CONTAMINATION 100