
//YES, IT'S THAT BAD.
#define SCICONSOLE_MENU_HREF  "<A href='?src=\ref[src];menu=SCICONSOLE_MENU'>Main Menu</A>"
#define SCICONSOLE_MENU 1
#define SCICONSOLE_RES_NODELIST 2
#define SCICONSOLE_NODEDESC 3
#define SCICONSOLE_UPDATE_DATABASE 4
#define SCICONSOLE_UPDATE_CIRCUIT 5
#define SCICONSOLE_UPDATE_PROTOLATHE 6
#define SCICONSOLE_LOCKED 7
#define SCICONSOLE_PROTOLATHE_MATS 8
#define SCICONSOLE_PROTOLATHE_CAT 9
#define SCICONSOLE_CIRCUIT_MATS 10
#define SCICONSOLE_CIRCUIT_CAT 11
#define SCICONSOLE_PROTOLATHE_NONE 12
#define SCICONSOLE_PROTOLATHE_SEARCH 13
#define SCICONSOLE_PROTOLATHE_CATVIEW 14
#define SCICONSOLE_PROTOLATHE_CHEMS 15
#define SCICONSOLE_CIRCUIT_CHEMS 16
#define SCICONSOLE_CIRCUIT_SEARCH 17
#define SCICONSOLE_CIRCUIT_NONE 18
#define SCICONSOLE_CIRCUIT_CATVIEW 19
#define SCICONSOLE_DA_NONE 20
#define SCICONSOLE_DA_UNLOADED 21
#define SCICONSOLE_DA_LOADED 22
#define SCICONSOLE_SETTINGS 23
#define SCICONSOLE_LINKING 24
#define SCICONSOLE_



