
//YES, IT'S THAT BAD.
#define SCICONSOLE_MENU_HREF  "<A href='?src=\ref[src];menu=SCICONSOLE_MENU'>Main Menu</A>"
#define SCICONSOLE_MENU 1
#define SCICONSOLE_RES_NODELIST 2
#define SCICONSOLE_NODEDESC 3
#define SCICONSOLE_UPDATE_DATABASE 4
#define SCICONSOLE_UPDATE_CIRCUIT 5
#define SCICONSOLE_UPDATE_PROTOLATHE 6
#define SCICONSOLE_LOCKED 7


