//Reverb preset defines
#define ECHO_GENERIC 		0
#define ECHO_ROOM 			2
#define ECHO_BATHROOM		3
#define ECHO_LIVINGROOM 	4
#define ECHO_AUDITORIUM		6
#define ECHO_CONCERT_HALL	7
#define ECHO_CAVE 			8
#define ECHO_HANGAR			10
#define ECHO_HALLWAY 		12
#define ECHO_SEWER_PIPE 	21
#define ECHO_CARPETTED_HALLWAY	11
