
#define SPEECH_CONTROLLER_QUEUE_SAY_VERB "say_verb"

#define SPEECH_CONTROLLER_QUEUE_WHISPER_VERB "whisper_verb"

#define SPEECH_CONTROLLER_QUEUE_EMOTE_VERB "emote_verb"

#define MOB_INDEX 1

#define MESSAGE_INDEX 2

#define CATEGORY_INDEX 3
