/// Flags for the organ_flags var on /obj/item/organ
DEFINE_BITFIELD(organ_flags, list(
	"ORGAN_SYNTHETIC" = ORGAN_SYNTHETIC,
	"ORGAN_FROZEN" = ORGAN_FROZEN,
	"ORGAN_FAILING" = ORGAN_FAILING,
	"ORGAN_EXTERNAL" = ORGAN_EXTERNAL,
	"ORGAN_VITAL" = ORGAN_VITAL,
	"ORGAN_EDIBLE" = ORGAN_EDIBLE,
	"ORGAN_SYNTHETIC_EMP" = ORGAN_SYNTHETIC_EMP,
	"ORGAN_UNREMOVABLE" = ORGAN_UNREMOVABLE,
))

/// When the surgery step fails :(
#define SURGERY_STEP_FAIL -1
