/// Tram crossing light logic
#define XING_STATE_GREEN 0
#define XING_STATE_AMBER 1
#define XING_STATE_RED 2
#define XING_STATE_MALF 3

#define XING_DISTANCE_AMBER 70
#define XING_DISTANCE_RED 40

#define XING_SIGNAL_DIRECTION_WEST "west-"
#define XING_SIGNAL_DIRECTION_EAST "east-"

#define XING_DEFAULT_TRAM_LENGTH 10

/// Tram destinations/platforms
#define TRAMSTATION_WEST 1
#define TRAMSTATION_CENTRAL 2
#define TRAMSTATION_EAST 3

#define HILBERT_PORT 1
#define HILBERT_CENTRAL 2
#define HILBERT_STARBOARD 3

#define BIRDSHOT_PRISON_WING 1
#define BIRDSHOT_SECURITY_WING 2

#define BIRDSHOT_MAINTENANCE_LEFT 1
#define BRIDSHOT_MAINTENANCE_RIGHT 2

/// Tram navigation directions
#define OUTBOUND 1
#define INBOUND -1
