var/list/occupations = list(
	"Station Engineer", "Station Engineer", "Station Engineer", "Station Engineer", "Station Engineer",
	"Shaft Miner", "Shaft Miner", "Shaft Miner",
	"Security Officer", "Security Officer", "Security Officer", "Security Officer", "Security Officer",
	"Detective",
	"Warden",
	"Geneticist", "Geneticist",
	"Scientist",	"Scientist", "Scientist",
	"Atmospheric Technician", "Atmospheric Technician", "Atmospheric Technician", "Atmospheric Technician",
	"Medical Doctor", "Medical Doctor", "Medical Doctor", "Medical Doctor", "Medical Doctor",
	"Head of Personnel",
	"Head of Security",
	"Chief Engineer",
	"Research Director",
	"Chaplain",
	"Roboticist",
	"Cyborg","Cyborg",//"Cyborg","Cyborg","Cyborg",
	"AI",
	"Barman",
	"Chef",
	"Janitor",
	"Clown", "Mime",
	"Chemist", "Chemist",
	"Quartermaster",
	"Cargo Technician","Cargo Technician",
	"Mail Sorter", "Mail Sorter",
	"Botanist", "Botanist",
	"Librarian",
	"Lawyer",
	"Virologist",
	"Chief Medical Officer")

var/list/assistant_occupations = list(
	"Assistant")
