/mob/living
	var/adjectives = list(
		"fat",
		"autistic",
		"retarded",
		"cool",
		"curvy",
		"plump",
		"nice",
		"radical",
		"tiny",
		"big",
		"normal",
		"average",
		"perfect",
		"interesting",
		"fast",
		"slow",
		"greasy",
		"oilly",
		"crazy",
		"dark",
		"mysterious",
		"nerdy",
		"not cool",
		"hot",
		"rhadamanthine",
		"platitudinous",
		"sugoi",
		"kawaii",
		"gay",
		"robust",
		"moist",
		"petite",
		"skinny",
		"mad",
	)
	var/adverbs = list(
		"radically",
		"stupidly",
		"sexily",
		"kindly",
		"delicately",
		"abruptly",
		"brutally",
		"savagely",
		"creepily",
		"bombaciously",
		"ackwardly",
		"mathametically",
		"sloppily",
		"silently",
		"robustily",
		"amazingly",
		"simply",
		"greatly",
		"terribly",
	)
	var/_verbs = list(
		"dance",
		"dab",
		"live",
		"breathe",
		"murder",
		"chill",
		"strip",
		"relax",
		"honk",
		"hack",
		"tune into their dark and inner POWER",
		"write freaky fanfiction",
		"exercise",
		"cry",
		"joke",
		"shopping",
		"pulsate",
	)
	var/hobbies = list(
		"reading books",
		"breaking the law",
		"killing people",
		"pissing off people",
		"making food",
		"writhing around in their own vomit and filth",
		"unsuccesfully seducing people",
		"succesfully seducing people",
		"shitposting",
		"bursting into song",
		"calling the shuttle early",
		"beating the clown",
		"throwing Ian into the washer",
		"playing obscure games about living on a space station",  //me irl
		"playing poker in maintenance",
		"wasting their life",
		"pondering the existence of a caring god",
		"walking up and down the hallway",
		"chilling, relaxing all cool, shooting some b-ball right outside the school",
		"roleplaying",
		"slipping people",
		"sleeping",
		"kissing strangers",
		"writing",
		"swimming... in <b>SPACE</b>",
		"farting",
		)
	var/flavor_text

/mob/living/proc/GenerateFlavorText()
	flavor_text = "They are very [pick(adjectives)]. They enjoy [pick(hobbies)]. They also [pick(adverbs)] [pick(_verbs)]."
	desc = "[desc] \n [flavor_text]"