/mob/living/Login()
	..()
	if(ticker && ticker.mode)
		switch(ticker.mode.name)
			if("sandbox")
				CanBuild()
			if("revolution")
				if ((src.mind in ticker.mode:revolutionaries) || (src.mind in ticker.mode:head_revolutionaries))
					ticker.mode:update_rev_icons_added(src.mind)
			if("cult")
				if (src.mind in ticker.mode:cult)
					ticker.mode:update_cult_icons_added(src.mind)