#define FLOCK_AGENT_DAMAGE_LAYER 1
#define FLOCK_AGENT_HEAD_LAYER 2
#define FLOCK_AGENT_HANDS_LAYER 3
#define FLOCK_AGENT_TOTAL_LAYERS 3

#define FLOCK_OBJECTIVE_CONSUME_IRRELEVANT 0
#define FLOCK_OBJECTIVE_CONSUME_DESIRED 2
#define FLOCK_OBJECTIVE_CONSUME_DETESTED -1
