#undef IC_INPUT
#undef IC_OUTPUT
#undef IC_ACTIVATOR

#undef DATA_CHANNEL
#undef PULSE_CHANNEL

#undef IC_SPAWN_DEFAULT
//#undef IC_SPAWN_RESEARCH // Research designs depend on this unfortunately.

#undef IC_FORMAT_ANY
#undef IC_FORMAT_STRING
#undef IC_FORMAT_CHAR
#undef IC_FORMAT_COLOR
#undef IC_FORMAT_NUMBER
#undef IC_FORMAT_DIR
#undef IC_FORMAT_BOOLEAN
#undef IC_FORMAT_REF
#undef IC_FORMAT_LIST

#undef IC_FORMAT_PULSE

#undef IC_PINTYPE_ANY
#undef IC_PINTYPE_STRING
#undef IC_PINTYPE_CHAR
#undef IC_PINTYPE_COLOR
#undef IC_PINTYPE_NUMBER
#undef IC_PINTYPE_DIR
#undef IC_PINTYPE_BOOLEAN
#undef IC_PINTYPE_REF
#undef IC_PINTYPE_LIST

#undef IC_PINTYPE_PULSE_IN
#undef IC_PINTYPE_PULSE_OUT

#undef IC_MAX_LIST_LENGTH