/obj/structure/closet/athletic_mixed/New()
	..()
	sleep(2)
	new /obj/item/clothing/under/shorts/grey(src)
	new /obj/item/clothing/under/shorts/black(src)
	new /obj/item/clothing/under/shorts/red(src)
	new /obj/item/clothing/under/shorts/blue(src)
	new /obj/item/clothing/under/shorts/green(src)

/obj/structure/closet/boxinggloves/New()
	..()
	sleep(2)
	new /obj/item/clothing/gloves/boxing/blue(src)
	new /obj/item/clothing/gloves/boxing/green(src)
	new /obj/item/clothing/gloves/boxing/yellow(src)
	new /obj/item/clothing/gloves/boxing(src)

/obj/structure/closet/masks/New()
	..()
	sleep(2)
	new /obj/item/clothing/mask/luchador(src)
	new /obj/item/clothing/mask/luchador/rudos(src)
	new /obj/item/clothing/mask/luchador/tecnicos(src)

/obj/structure/closet/lasertag/red/New()
	..()
	sleep(2)
	new /obj/item/clothing/suit/redtag(src)
	new /obj/item/clothing/suit/redtag(src)
	new /obj/item/weapon/gun/energy/laser/redtag(src)
	new /obj/item/weapon/gun/energy/laser/redtag(src)

/obj/structure/closet/lasertag/blue/New()
	..()
	sleep(2)
	new /obj/item/clothing/suit/bluetag(src)
	new /obj/item/clothing/suit/bluetag(src)
	new /obj/item/weapon/gun/energy/laser/bluetag(src)
	new /obj/item/weapon/gun/energy/laser/bluetag(src)