/obj/structure/closet/jcloset/New()
	..()
	sleep(2)
	new /obj/item/device/flashlight(src)
	new /obj/item/clothing/shoes/galoshes(src)
	new /obj/item/weapon/caution(src)
	new /obj/item/weapon/caution(src)
	new /obj/item/weapon/caution(src)
	new /obj/item/weapon/caution(src)
	new /obj/item/weapon/caution(src)
	new /obj/item/weapon/caution(src)

/obj/structure/closet/jcloset2/New()
	..()
	sleep(2)
	new /obj/item/weapon/chem_grenade/cleaner(src)
	new /obj/item/weapon/chem_grenade/cleaner(src)
	new /obj/item/weapon/chem_grenade/cleaner(src)
	new /obj/item/weapon/cleaner(src)
	new /obj/item/weapon/cleaner(src)
	new /obj/item/weapon/cleaner(src)
	new /obj/item/weapon/trashbag(src)
	new /obj/item/device/portalathe(src)
