/obj/closet/jcloset/New()
	..()
	sleep(2)
	new /obj/item/clothing/suit/bio_suit(src)
	new /obj/item/clothing/head/bio_hood(src)
	new /obj/item/clothing/under/rank/janitor(src)
	new /obj/item/clothing/under/rank/janitor(src)
	new /obj/item/clothing/shoes/black(src)
	new /obj/item/clothing/shoes/black(src)
	new /obj/item/device/flashlight(src)
	new /obj/item/clothing/shoes/galoshes(src)
	new /obj/item/weapon/caution(src)
	new /obj/item/weapon/caution(src)
	new /obj/item/weapon/caution(src)
	new /obj/item/weapon/caution(src)
	new /obj/item/weapon/caution(src)
	new /obj/item/weapon/caution(src)
