/obj/structure/closet/secure_closet/kitchen/New()
	..()
	sleep(2)
	/*new /obj/item/clothing/head/chefhat(src)
	new /obj/item/clothing/head/chefhat(src)
	new /obj/item/clothing/under/rank/chef(src)
	new /obj/item/clothing/under/rank/chef(src)*/
	new /obj/item/weapon/reagent_containers/food/snacks/flour(src)
	new /obj/item/weapon/reagent_containers/food/snacks/flour(src)
	new /obj/item/weapon/reagent_containers/food/snacks/flour(src)
	new /obj/item/weapon/reagent_containers/food/snacks/flour(src)
	new /obj/item/weapon/reagent_containers/food/snacks/flour(src)
	new /obj/item/weapon/reagent_containers/food/snacks/flour(src)
	new /obj/item/weapon/reagent_containers/food/snacks/flour(src)
	new /obj/item/weapon/reagent_containers/food/snacks/flour(src)
	new /obj/item/weapon/reagent_containers/food/snacks/flour(src)
	new /obj/item/weapon/reagent_containers/food/snacks/flour(src)
	new /obj/item/weapon/reagent_containers/food/snacks/flour(src)
	new /obj/item/weapon/reagent_containers/food/snacks/flour(src)
	new /obj/item/weapon/reagent_containers/food/snacks/flour(src)
	new /obj/item/weapon/reagent_containers/food/snacks/flour(src)
	new /obj/item/weapon/reagent_containers/food/snacks/flour(src)
	new /obj/item/weapon/reagent_containers/food/snacks/flour(src)
	new /obj/item/weapon/reagent_containers/food/condiment/sugar(src)
	/*new /obj/item/weapon/tray(src)
	new /obj/item/weapon/tray(src)
	new /obj/item/weapon/tray(src)
	new /obj/item/weapon/tray(src)
	new /obj/item/weapon/tray(src)
	new /obj/item/weapon/tray(src)
	new /obj/item/weapon/kitchenknife(src)*/
	/*new /obj/item/clothing/head/chefhat(src)
	new /obj/item/clothing/head/chefhat(src)
	new /obj/item/clothing/under/rank/chef(src)
	new /obj/item/clothing/under/rank/chef(src)
	new /obj/item/weapon/kitchen/utensil/fork(src)
	new /obj/item/weapon/kitchen/utensil/knife(src)
	new /obj/item/weapon/kitchen/utensil/spoon(src)
	new /obj/item/weapon/kitchen/rollingpin(src)*/

/obj/structure/closet/secure_closet/meat/New()
	..()
	sleep(2)
	new /obj/item/weapon/reagent_containers/food/snacks/sliceable/meat/monkey(src)
	new /obj/item/weapon/reagent_containers/food/snacks/sliceable/meat/monkey(src)
	new /obj/item/weapon/reagent_containers/food/snacks/sliceable/meat/monkey(src)
	new /obj/item/weapon/reagent_containers/food/snacks/sliceable/meat/monkey(src)

/obj/structure/closet/secure_closet/fridge/New()
	..()
	sleep(2)
	new /obj/item/weapon/reagent_containers/food/drinks/milk(src)
	new /obj/item/weapon/reagent_containers/food/drinks/milk(src)
	new /obj/item/weapon/reagent_containers/food/drinks/milk(src)
	new /obj/item/weapon/reagent_containers/food/drinks/milk(src)
	new /obj/item/weapon/reagent_containers/food/drinks/milk(src)
	new /obj/item/weapon/reagent_containers/food/drinks/soymilk(src)
	new /obj/item/weapon/reagent_containers/food/drinks/soymilk(src)
	new /obj/item/weapon/reagent_containers/food/drinks/soymilk(src)
	new /obj/item/weapon/reagent_containers/food/drinks/soymilk(src)
	new /obj/item/weapon/reagent_containers/food/drinks/soymilk(src)
	new /obj/item/kitchen/egg_box(src)
	new /obj/item/kitchen/egg_box(src)

/obj/structure/closet/secure_closet/money_freezer/New()
	..()
	sleep(2)
	new /obj/item/weapon/money/c1000(src)
	new /obj/item/weapon/money/c1000(src)
	new /obj/item/weapon/money/c1000(src)
	new /obj/item/weapon/money/c500(src)
	new /obj/item/weapon/money/c500(src)
	new /obj/item/weapon/money/c500(src)
	new /obj/item/weapon/money/c500(src)
	new /obj/item/weapon/money/c500(src)
	new /obj/item/weapon/money/c200(src)
	new /obj/item/weapon/money/c200(src)
	new /obj/item/weapon/money/c200(src)
	new /obj/item/weapon/money/c200(src)
	new /obj/item/weapon/money/c200(src)

