/obj/closet/l3closet/New()
	..()
	sleep(2)
	new /obj/item/clothing/suit/bio_suit( src )
	new /obj/item/clothing/under/color/white( src )
	new /obj/item/clothing/shoes/white( src )
	new /obj/item/clothing/head/bio_hood( src )
