/obj/closet/malf/suits/New()
	..()
	sleep(2)
	new /obj/item/weapon/tank/jetpack(src)
	new /obj/item/clothing/mask/breath(src)
	new /obj/item/clothing/head/helmet/space/syndicate(src)
	new /obj/item/clothing/suit/space/syndicate(src)
	new /obj/item/weapon/crowbar(src)
	new /obj/item/weapon/cell(src)
	new /obj/item/device/multitool(src)
