/obj/station_objects/closet/thunderdome/New()
	..()
	sleep(2)

/obj/station_objects/closet/thunderdome/tdred/New()
	..()
	sleep(2)
	new /obj/item/clothing/suit/armor/tdome/red(src)
	new /obj/item/clothing/suit/armor/tdome/red(src)
	new /obj/item/clothing/suit/armor/tdome/red(src)
	new /obj/item/weapon/melee/energy/sword(src)
	new /obj/item/weapon/melee/energy/sword(src)
	new /obj/item/weapon/melee/energy/sword(src)
	new /obj/item/weapon/gun/energy/laser(src)
	new /obj/item/weapon/gun/energy/laser(src)
	new /obj/item/weapon/gun/energy/laser(src)
	new /obj/item/weapon/melee/baton(src)
	new /obj/item/weapon/melee/baton(src)
	new /obj/item/weapon/melee/baton(src)
	new /obj/item/weapon/storage/flashbang_kit(src)
	new /obj/item/weapon/storage/flashbang_kit(src)
	new /obj/item/weapon/storage/flashbang_kit(src)
	new /obj/item/clothing/head/helmet/thunderdome(src)
	new /obj/item/clothing/head/helmet/thunderdome(src)
	new /obj/item/clothing/head/helmet/thunderdome(src)

/obj/station_objects/closet/thunderdome/tdgreen/New()
	..()
	sleep(2)
	new /obj/item/clothing/suit/armor/tdome/green(src)
	new /obj/item/clothing/suit/armor/tdome/green(src)
	new /obj/item/clothing/suit/armor/tdome/green(src)
	new /obj/item/weapon/melee/energy/sword(src)
	new /obj/item/weapon/melee/energy/sword(src)
	new /obj/item/weapon/melee/energy/sword(src)
	new /obj/item/weapon/gun/energy/laser(src)
	new /obj/item/weapon/gun/energy/laser(src)
	new /obj/item/weapon/gun/energy/laser(src)
	new /obj/item/weapon/melee/baton(src)
	new /obj/item/weapon/melee/baton(src)
	new /obj/item/weapon/melee/baton(src)
	new /obj/item/weapon/storage/flashbang_kit(src)
	new /obj/item/weapon/storage/flashbang_kit(src)
	new /obj/item/weapon/storage/flashbang_kit(src)
	new /obj/item/clothing/head/helmet/thunderdome(src)
	new /obj/item/clothing/head/helmet/thunderdome(src)
	new /obj/item/clothing/head/helmet/thunderdome(src)
