/obj/closet/wardrobe/New()
	new /obj/item/clothing/under/color/blue( src )
	new /obj/item/clothing/under/color/blue( src )
	new /obj/item/clothing/under/color/blue( src )
	new /obj/item/clothing/under/color/blue( src )
	new /obj/item/clothing/under/color/blue( src )
	new /obj/item/clothing/under/color/blue( src )
	new /obj/item/clothing/shoes/brown( src )
	new /obj/item/clothing/shoes/brown( src )
	new /obj/item/clothing/shoes/brown( src )
	new /obj/item/clothing/shoes/brown( src )
	new /obj/item/clothing/shoes/brown( src )
	new /obj/item/clothing/shoes/brown( src )
	return

/obj/closet/wardrobe/red/New()
	new /obj/item/clothing/under/color/red( src )
	new /obj/item/clothing/under/color/red( src )
	new /obj/item/clothing/under/color/red( src )
	new /obj/item/clothing/under/color/red( src )
	new /obj/item/clothing/under/color/red( src )
	new /obj/item/clothing/under/color/red( src )
	new /obj/item/clothing/shoes/brown( src )
	new /obj/item/clothing/shoes/brown( src )
	new /obj/item/clothing/shoes/brown( src )
	new /obj/item/clothing/shoes/brown( src )
	new /obj/item/clothing/shoes/brown( src )
	new /obj/item/clothing/shoes/brown( src )
	return
/obj/closet/wardrobe/forensics_red/New()
	new /obj/item/clothing/under/rank/forensic_technician( src )
	new /obj/item/clothing/under/rank/forensic_technician( src )
	new /obj/item/clothing/under/rank/forensic_technician( src )
	new /obj/item/clothing/under/rank/forensic_technician( src )
	new /obj/item/clothing/under/rank/forensic_technician( src )
	new /obj/item/clothing/under/rank/forensic_technician( src )
	new /obj/item/clothing/shoes/brown( src )
	new /obj/item/clothing/shoes/brown( src )
	new /obj/item/clothing/shoes/brown( src )
	new /obj/item/clothing/shoes/brown( src )
	new /obj/item/clothing/shoes/brown( src )
	new /obj/item/clothing/shoes/brown( src )
	return

/obj/closet/wardrobe/pink/New()
	new /obj/item/clothing/under/color/pink( src )
	new /obj/item/clothing/under/color/pink( src )
	new /obj/item/clothing/under/color/pink( src )
	new /obj/item/clothing/under/color/pink( src )
	new /obj/item/clothing/under/color/pink( src )
	new /obj/item/clothing/under/color/pink( src )
	new /obj/item/clothing/shoes/brown( src )
	new /obj/item/clothing/shoes/brown( src )
	new /obj/item/clothing/shoes/brown( src )
	new /obj/item/clothing/shoes/brown( src )
	new /obj/item/clothing/shoes/brown( src )
	new /obj/item/clothing/shoes/brown( src )
	return

/obj/closet/wardrobe/black/New()
	new /obj/item/clothing/under/color/black( src )
	new /obj/item/clothing/under/color/black( src )
	new /obj/item/clothing/under/color/black( src )
	new /obj/item/clothing/under/color/black( src )
	new /obj/item/clothing/under/color/black( src )
	new /obj/item/clothing/under/color/black( src )
	new /obj/item/clothing/shoes/black( src )
	new /obj/item/clothing/shoes/black( src )
	new /obj/item/clothing/shoes/black( src )
	new /obj/item/clothing/shoes/black( src )
	new /obj/item/clothing/shoes/black( src )
	new /obj/item/clothing/shoes/black( src )
	new /obj/item/clothing/head/that( src )
	new /obj/item/clothing/head/that( src )
	new /obj/item/clothing/head/that( src )
	return

/obj/closet/wardrobe/chaplain_black/New()
	//new /obj/item/clothing/suit/imperium_monk( src ) //No. -- Urist
	new /obj/item/clothing/under/rank/chaplain( src )
	new /obj/item/clothing/under/rank/chaplain( src )
	new /obj/item/clothing/shoes/black( src )
	new /obj/item/clothing/shoes/black( src )
	new /obj/item/clothing/suit/nun( src )
	new /obj/item/clothing/suit/chaplain_hoodie( src )
	new /obj/item/clothing/head/chaplain_hood( src )
	new /obj/item/clothing/suit/holidaypriest( src )
	new /obj/item/weapon/candlepack( src )
	new /obj/item/weapon/candlepack( src )
	return

/obj/closet/wardrobe/green/New()
	new /obj/item/clothing/under/color/green( src )
	new /obj/item/clothing/under/color/green( src )
	new /obj/item/clothing/under/color/green( src )
	new /obj/item/clothing/under/color/green( src )
	new /obj/item/clothing/under/color/green( src )
	new /obj/item/clothing/under/color/green( src )
	new /obj/item/clothing/shoes/black( src )
	new /obj/item/clothing/shoes/black( src )
	new /obj/item/clothing/shoes/black( src )
	new /obj/item/clothing/shoes/black( src )
	new /obj/item/clothing/shoes/black( src )
	new /obj/item/clothing/shoes/black( src )
	return

/obj/closet/wardrobe/orange/New()
	new /obj/item/clothing/under/color/orange( src )
	new /obj/item/clothing/under/color/orange( src )
	new /obj/item/clothing/under/color/orange( src )
	new /obj/item/clothing/under/color/orange( src )
	new /obj/item/clothing/under/color/orange( src )
	new /obj/item/clothing/under/color/orange( src )
	new /obj/item/clothing/shoes/orange( src )
	new /obj/item/clothing/shoes/orange( src )
	new /obj/item/clothing/shoes/orange( src )
	new /obj/item/clothing/shoes/orange( src )
	new /obj/item/clothing/shoes/orange( src )
	new /obj/item/clothing/shoes/orange( src )
	return

/obj/closet/wardrobe/yellow/New()
	new /obj/item/clothing/under/color/yellow( src )
	new /obj/item/clothing/under/color/yellow( src )
	new /obj/item/clothing/under/color/yellow( src )
	new /obj/item/clothing/under/color/yellow( src )
	new /obj/item/clothing/under/color/yellow( src )
	new /obj/item/clothing/under/color/yellow( src )
	new /obj/item/clothing/shoes/orange( src )
	new /obj/item/clothing/shoes/orange( src )
	new /obj/item/clothing/shoes/orange( src )
	new /obj/item/clothing/shoes/orange( src )
	new /obj/item/clothing/shoes/orange( src )
	new /obj/item/clothing/shoes/orange( src )
	return
/obj/closet/wardrobe/atmospherics_yellow/New()
	new /obj/item/clothing/under/rank/atmospheric_technician( src )
	new /obj/item/clothing/under/rank/atmospheric_technician( src )
	new /obj/item/clothing/under/rank/atmospheric_technician( src )
	new /obj/item/clothing/under/rank/atmospheric_technician( src )
	new /obj/item/clothing/under/rank/atmospheric_technician( src )
	new /obj/item/clothing/under/rank/atmospheric_technician( src )
	new /obj/item/clothing/shoes/black( src )
	new /obj/item/clothing/shoes/black( src )
	new /obj/item/clothing/shoes/black( src )
	new /obj/item/clothing/shoes/black( src )
	new /obj/item/clothing/shoes/black( src )
	new /obj/item/clothing/shoes/black( src )
	return
/obj/closet/wardrobe/engineering_yellow/New()
	new /obj/item/clothing/under/rank/engineer( src )
	new /obj/item/clothing/under/rank/engineer( src )
	new /obj/item/clothing/under/rank/engineer( src )
	new /obj/item/clothing/under/rank/engineer( src )
	new /obj/item/clothing/under/rank/engineer( src )
	new /obj/item/clothing/under/rank/engineer( src )
	new /obj/item/clothing/shoes/orange( src )
	new /obj/item/clothing/shoes/orange( src )
	new /obj/item/clothing/shoes/orange( src )
	new /obj/item/clothing/shoes/orange( src )
	new /obj/item/clothing/shoes/orange( src )
	new /obj/item/clothing/shoes/orange( src )
	return

/obj/closet/wardrobe/white/New()
	new /obj/item/clothing/under/color/white( src )
	new /obj/item/clothing/under/color/white( src )
	new /obj/item/clothing/under/color/white( src )
	new /obj/item/clothing/under/color/white( src )
	new /obj/item/clothing/under/color/white( src )
	new /obj/item/clothing/shoes/white( src )
	new /obj/item/clothing/shoes/white( src )
	new /obj/item/clothing/shoes/white( src )
	new /obj/item/clothing/shoes/white( src )
	new /obj/item/clothing/shoes/white( src )
	//new /obj/item/weapon/storage/stma_kit( src )
	//new /obj/item/clothing/suit/labcoat(src)
	//new /obj/item/clothing/suit/labcoat(src)
	//new /obj/item/clothing/suit/labcoat(src)
	return
/obj/closet/wardrobe/toxins_white/New()
	new /obj/item/clothing/under/rank/scientist( src )
	new /obj/item/clothing/under/rank/scientist( src )
	new /obj/item/clothing/under/rank/scientist( src )
	new /obj/item/clothing/under/rank/scientist( src )
	new /obj/item/clothing/under/rank/scientist( src )
	new /obj/item/clothing/shoes/white( src )
	new /obj/item/clothing/shoes/white( src )
	new /obj/item/clothing/shoes/white( src )
	new /obj/item/clothing/shoes/white( src )
	new /obj/item/clothing/shoes/white( src )
	new /obj/item/weapon/storage/stma_kit( src )
	new /obj/item/clothing/suit/labcoat(src)
	new /obj/item/clothing/suit/labcoat(src)
	new /obj/item/clothing/suit/labcoat(src)
	return
/obj/closet/wardrobe/genetics_white/New()
	new /obj/item/clothing/under/rank/geneticist( src )
	new /obj/item/clothing/under/rank/geneticist( src )
	new /obj/item/clothing/under/rank/geneticist( src )
	new /obj/item/clothing/under/rank/geneticist( src )
	new /obj/item/clothing/under/rank/geneticist( src )
	new /obj/item/clothing/shoes/white( src )
	new /obj/item/clothing/shoes/white( src )
	new /obj/item/clothing/shoes/white( src )
	new /obj/item/clothing/shoes/white( src )
	new /obj/item/clothing/shoes/white( src )
	new /obj/item/weapon/storage/stma_kit( src )
	new /obj/item/clothing/suit/labcoat(src)
	new /obj/item/clothing/suit/labcoat(src)
	new /obj/item/clothing/suit/labcoat(src)
	return
/obj/closet/wardrobe/grey/New()
	new /obj/item/clothing/under/color/grey( src )
	new /obj/item/clothing/under/color/grey( src )
	new /obj/item/clothing/under/color/grey( src )
	new /obj/item/clothing/under/color/grey( src )
	new /obj/item/clothing/under/color/grey( src )
	new /obj/item/clothing/under/color/grey( src )
	new /obj/item/clothing/shoes/black( src )
	new /obj/item/clothing/shoes/black( src )
	new /obj/item/clothing/shoes/black( src )
	new /obj/item/clothing/shoes/black( src )
	new /obj/item/clothing/shoes/black( src )
	new /obj/item/clothing/shoes/black( src )
	return

/obj/closet/wardrobe/mixed/New()
	new /obj/item/clothing/under/color/blue( src )
	new /obj/item/clothing/under/color/blue( src )
	new /obj/item/clothing/under/color/blue( src )
	new /obj/item/clothing/under/color/pink( src )
	new /obj/item/clothing/under/color/pink( src )
	new /obj/item/clothing/under/color/pink( src )
	new /obj/item/clothing/shoes/brown( src )
	new /obj/item/clothing/shoes/brown( src )
	new /obj/item/clothing/shoes/brown( src )
	new /obj/item/clothing/shoes/brown( src )
	new /obj/item/clothing/shoes/brown( src )
	new /obj/item/clothing/shoes/brown( src )
	return
/obj/closet/lawcloset/New()
	new /obj/item/clothing/under/lawyer/black( src )
	new /obj/item/clothing/under/lawyer/red ( src )
	new /obj/item/clothing/under/lawyer/blue ( src )
	new /obj/item/clothing/shoes/brown(src)
	new /obj/item/clothing/shoes/brown(src)
	new /obj/item/clothing/shoes/black(src)
	new /obj/item/weapon/storage/briefcase(src)
	new /obj/item/weapon/storage/briefcase(src)