/obj/structure/closet/wardrobe/New()
	new /obj/item/clothing/under/color/blue(src)
	new /obj/item/clothing/under/color/blue(src)
	new /obj/item/clothing/under/color/blue(src)
	new /obj/item/clothing/shoes/brown(src)
	new /obj/item/clothing/shoes/brown(src)
	new /obj/item/clothing/shoes/brown(src)
	return

//says red, is actually the security locker
/obj/structure/closet/wardrobe/red/New()
	new /obj/item/clothing/under/rank/security(src)
	new /obj/item/clothing/under/rank/security(src)
	new /obj/item/clothing/under/rank/security(src)
	new /obj/item/clothing/shoes/jackboots(src)
	new /obj/item/clothing/shoes/jackboots(src)
	new /obj/item/clothing/shoes/jackboots(src)
	new /obj/item/clothing/gloves/red(src)
	new /obj/item/clothing/gloves/red(src)
	new /obj/item/clothing/gloves/red(src)
	new /obj/item/clothing/gloves/red(src)
	new /obj/item/clothing/head/secsoft(src)
	new /obj/item/clothing/head/secsoft(src)
	new /obj/item/clothing/head/secsoft(src)
	return

/obj/structure/closet/wardrobe/warden/New()
	new /obj/item/clothing/under/rank/warden(src)
	new /obj/item/clothing/shoes/jackboots(src)
	new /obj/item/clothing/head/helmet/warden(src)
	new /obj/item/weapon/storage/belt/security(src)
	new /obj/item/clothing/gloves/red(src)
	new /obj/item/clothing/suit/storage/gearharness(src)

obj/structure/closet/wardrobe/hos/New()
	new /obj/item/clothing/suit/storage/armourrigvest(src)
	new /obj/item/clothing/suit/armor/hos(src)
	new /obj/item/clothing/head/helmet/HoS(src)
	new /obj/item/weapon/storage/belt/security(src)
	new /obj/item/clothing/gloves/hos(src)
	new /obj/item/clothing/shoes/jackboots(src)
	new /obj/item/clothing/under/rank/head_of_security(src)
	new /obj/item/clothing/under/jensen(src)
	new /obj/item/clothing/suit/armor/hos/jensen(src)
	new /obj/item/clothing/head/helmet/HoS/dermal(src)

obj/structure/closet/wardrobe/hop/New()
	new /obj/item/clothing/under/rank/head_of_personnel(src)
	new /obj/item/clothing/suit/armor/vest(src)
	new /obj/item/clothing/shoes/brown(src)
	new /obj/item/clothing/gloves/blue(src)
	new /obj/item/clothing/head/helmet(src)

/obj/structure/closet/wardrobe/pink/New()
	new /obj/item/clothing/under/color/pink(src)
	new /obj/item/clothing/under/color/pink(src)
	new /obj/item/clothing/under/color/pink(src)
	new /obj/item/clothing/shoes/brown(src)
	new /obj/item/clothing/shoes/brown(src)
	new /obj/item/clothing/shoes/brown(src)
	return

/obj/structure/closet/wardrobe/black/New()
	new /obj/item/clothing/under/color/black(src)
	new /obj/item/clothing/under/color/black(src)
	new /obj/item/clothing/under/color/black(src)
	new /obj/item/clothing/shoes/black(src)
	new /obj/item/clothing/shoes/black(src)
	new /obj/item/clothing/shoes/black(src)
	new /obj/item/clothing/head/that(src)
	new /obj/item/clothing/head/that(src)
	new /obj/item/clothing/head/that(src)
	return

/obj/structure/closet/wardrobe/chaplain_black/New()
	//new /obj/item/clothing/suit/imperium_monk(src) //No. -- Urist
	new /obj/item/clothing/under/rank/chaplain(src)
	new /obj/item/clothing/shoes/black(src)
	new /obj/item/clothing/suit/nun(src)
	new /obj/item/clothing/head/nun_hood(src)
	new /obj/item/clothing/suit/storage/chaplain_hoodie(src)
	new /obj/item/clothing/head/chaplain_hood(src)
	new /obj/item/clothing/suit/holidaypriest(src)
	//new /obj/item/clothing/suit/hastur (src) //No. -- Urist
	//new /obj/item/clothing/head/hasturhood (src) //No. -- Urist
	return

/obj/structure/closet/wardrobe/green/New()
	new /obj/item/clothing/under/color/green(src)
	new /obj/item/clothing/under/color/green(src)
	new /obj/item/clothing/under/color/green(src)
	new /obj/item/clothing/shoes/black(src)
	new /obj/item/clothing/shoes/black(src)
	new /obj/item/clothing/shoes/black(src)

/obj/structure/closet/wardrobe/orange/New()
	new /obj/item/clothing/under/color/orange(src)
	new /obj/item/clothing/under/color/orange(src)
	new /obj/item/clothing/under/color/orange(src)
	new /obj/item/clothing/shoes/orange(src)
	new /obj/item/clothing/shoes/orange(src)
	new /obj/item/clothing/shoes/orange(src)

/obj/structure/closet/wardrobe/yellow/New()
	new /obj/item/clothing/under/color/yellow(src)
	new /obj/item/clothing/under/color/yellow(src)
	new /obj/item/clothing/under/color/yellow(src)
	new /obj/item/clothing/shoes/orange(src)
	new /obj/item/clothing/shoes/orange(src)
	new /obj/item/clothing/shoes/orange(src)

/obj/structure/closet/wardrobe/atmospherics_yellow/New()
	new /obj/item/clothing/under/rank/atmospheric_technician(src)
	new /obj/item/clothing/under/rank/atmospheric_technician(src)
	new /obj/item/clothing/under/rank/atmospheric_technician(src)
	new /obj/item/clothing/shoes/black(src)
	new /obj/item/clothing/shoes/black(src)
	new /obj/item/clothing/shoes/black(src)
	new /obj/item/clothing/shoes/magboots(src) //[Redacted] ZAS! >:C

/obj/structure/closet/wardrobe/engineering_yellow/New()
	new /obj/item/clothing/under/rank/engineer(src)
	new /obj/item/clothing/under/rank/engineer(src)
	new /obj/item/clothing/under/rank/engineer(src)
	new /obj/item/clothing/head/helmet/hardhat(src)
	new /obj/item/clothing/head/helmet/hardhat(src)
	new /obj/item/clothing/head/helmet/hardhat(src)
	new /obj/item/weapon/storage/belt/utility/full(src)
	new /obj/item/weapon/storage/belt/utility/full(src)
	new /obj/item/weapon/storage/belt/utility/full(src)
	new /obj/item/clothing/shoes/orange(src)
	new /obj/item/clothing/shoes/orange(src)
	new /obj/item/clothing/shoes/orange(src)

/obj/structure/closet/wardrobe/white/New()
	new /obj/item/clothing/under/color/white(src)
	new /obj/item/clothing/under/color/white(src)
	new /obj/item/clothing/under/color/white(src)
	new /obj/item/clothing/shoes/white(src)
	new /obj/item/clothing/shoes/white(src)
	new /obj/item/clothing/shoes/white(src)

/obj/structure/closet/wardrobe/toxins_white/New()
	new /obj/item/clothing/under/rank/scientist(src)
	new /obj/item/clothing/under/rank/scientist(src)
	new /obj/item/clothing/under/rank/scientist(src)
	new /obj/item/clothing/suit/storage/labcoat/science(src)
	new /obj/item/clothing/suit/storage/labcoat/science(src)
	new /obj/item/clothing/suit/storage/labcoat/science(src)
	new /obj/item/clothing/shoes/white(src)
	new /obj/item/clothing/shoes/white(src)
	new /obj/item/clothing/shoes/white(src)
	return

/obj/structure/closet/wardrobe/robotics_black/New()
	new /obj/item/clothing/under/rank/roboticist(src)
	new /obj/item/clothing/under/rank/roboticist(src)
	new /obj/item/clothing/suit/storage/labcoat(src)
	new /obj/item/clothing/suit/storage/labcoat(src)
	new /obj/item/clothing/shoes/black(src)
	new /obj/item/clothing/shoes/black(src)
	return

/obj/structure/closet/wardrobe/chemistry_white/New()
	new /obj/item/clothing/under/rank/chemist(src)
	new /obj/item/clothing/under/rank/chemist(src)
	new /obj/item/clothing/under/rank/chemist(src)
	new /obj/item/clothing/suit/storage/labcoat/chemist(src)
	new /obj/item/clothing/suit/storage/labcoat/chemist(src)
	new /obj/item/clothing/suit/storage/labcoat/chemist(src)
	new /obj/item/clothing/shoes/white(src)
	new /obj/item/clothing/shoes/white(src)
	new /obj/item/clothing/shoes/white(src)

/obj/structure/closet/wardrobe/genetics_white/New()
	new /obj/item/clothing/under/rank/geneticist(src)
	new /obj/item/clothing/under/rank/geneticist(src)
	new /obj/item/clothing/under/rank/geneticist(src)
	new /obj/item/clothing/suit/storage/labcoat/genetics(src)
	new /obj/item/clothing/suit/storage/labcoat/genetics(src)
	new /obj/item/clothing/suit/storage/labcoat/genetics(src)
	new /obj/item/clothing/shoes/white(src)
	new /obj/item/clothing/shoes/white(src)
	new /obj/item/clothing/shoes/white(src)




/obj/structure/closet/wardrobe/virology_white/New()
	new /obj/item/clothing/suit/storage/labcoat/virologist(src)
	new /obj/item/clothing/suit/storage/labcoat/virologist(src)
	new /obj/item/clothing/suit/storage/labcoat/virologist(src)
	new /obj/item/clothing/under/rank/virologist(src)
	new /obj/item/clothing/under/rank/virologist(src)
	new /obj/item/clothing/under/rank/virologist(src)
	new /obj/item/clothing/shoes/white(src)
	new /obj/item/clothing/shoes/white(src)
	new /obj/item/clothing/shoes/white(src)

/obj/structure/closet/wardrobe/grey/New()
	new /obj/item/clothing/under/color/grey(src)
	new /obj/item/clothing/under/color/grey(src)
	new /obj/item/clothing/under/color/grey(src)
	new /obj/item/clothing/shoes/black(src)
	new /obj/item/clothing/shoes/black(src)
	new /obj/item/clothing/shoes/black(src)

/obj/structure/closet/wardrobe/mixed/New()
	new /obj/item/clothing/under/color/white(src)
	new /obj/item/clothing/under/color/blue(src)
	new /obj/item/clothing/under/color/yellow(src)
	new /obj/item/clothing/under/color/green(src)
	new /obj/item/clothing/under/color/orange(src)
	new /obj/item/clothing/under/color/pink(src)
	new /obj/item/clothing/shoes/black(src)
	new /obj/item/clothing/shoes/brown(src)
	new /obj/item/clothing/shoes/white(src)

/obj/structure/closet/lawcloset/New()
	if(prob(50))
		new /obj/item/clothing/suit/lawyer/bluejacket(src)
	else
		new /obj/item/clothing/suit/lawyer/purpjacket(src)
	if(prob(50))
		new /obj/item/clothing/suit/lawyer/bluejacket(src)
	else
		new /obj/item/clothing/suit/lawyer/purpjacket(src)
	if(prob(50))
		new /obj/item/clothing/suit/lawyer/bluejacket(src)
	else
		new /obj/item/clothing/suit/lawyer/purpjacket(src)
	new /obj/item/clothing/shoes/brown(src)
	new /obj/item/clothing/shoes/brown(src)
	new /obj/item/clothing/shoes/brown(src)


/obj/structure/closet/wardrobe/medic_white/New()
	new /obj/item/clothing/under/rank/medical(src)
	new /obj/item/clothing/under/rank/medical(src)
	new /obj/item/clothing/under/rank/medical(src)
	new /obj/item/clothing/suit/storage/labcoat(src)
	new /obj/item/clothing/suit/storage/labcoat(src)
	new /obj/item/clothing/suit/storage/labcoat(src)
	new /obj/item/weapon/storage/belt/medical(src)
	new /obj/item/weapon/storage/belt/medical(src)
	new /obj/item/weapon/storage/belt/medical(src)
	new /obj/item/clothing/shoes/white(src)
	new /obj/item/clothing/shoes/white(src)
	new /obj/item/clothing/shoes/white(src)

/obj/structure/closet/wardrobe/nurse/New()
	new /obj/item/clothing/under/rank/nursesuit (src)
	new /obj/item/clothing/under/rank/nursesuit (src)
	new /obj/item/clothing/under/rank/nursesuit (src)
	new /obj/item/clothing/head/nursehat (src)
	new /obj/item/clothing/head/nursehat (src)
	new /obj/item/clothing/head/nursehat (src)
	new /obj/item/clothing/shoes/white(src)
	new /obj/item/clothing/shoes/white(src)
	new /obj/item/clothing/shoes/white(src)

/obj/structure/closet/wardrobe/cmo/New()
	new /obj/item/clothing/gloves/latex(src)
	new /obj/item/clothing/suit/bio_suit/cmo(src)
	new /obj/item/clothing/head/bio_hood/general(src)
	new /obj/item/clothing/suit/storage/labcoat/cmo(src)
	new /obj/item/clothing/suit/storage/labcoat/cmoalt(src)
	new /obj/item/clothing/shoes/brown(src)
	new /obj/item/clothing/under/rank/chief_medical_officer(src)

/obj/structure/closet/wardrobe/rd/New()
	new /obj/item/clothing/under/rank/research_director(src)
	new /obj/item/clothing/under/rank/research_director(src)
	new /obj/item/clothing/under/rank/research_director(src)
	new /obj/item/clothing/suit/bio_suit/scientist(src)
	new /obj/item/clothing/head/bio_hood/scientist(src)
	new /obj/item/clothing/suit/storage/labcoat(src)
	new /obj/item/clothing/suit/storage/labcoat(src)
	new /obj/item/clothing/suit/storage/labcoat(src)
	new /obj/item/clothing/shoes/white(src)
	new /obj/item/clothing/shoes/white(src)
	new /obj/item/clothing/shoes/white(src)
	new /obj/item/clothing/gloves/latex(src)
	new /obj/item/clothing/gloves/latex(src)
	new /obj/item/clothing/gloves/latex(src)

/obj/structure/closet/wardrobe/robotics_yellow/New()
	new /obj/item/clothing/under/rank/roboticist(src)
	new /obj/item/clothing/under/rank/roboticist(src)
	new /obj/item/clothing/under/rank/roboticist(src)
	new /obj/item/clothing/suit/storage/labcoat(src)
	new /obj/item/clothing/suit/storage/labcoat(src)
	new /obj/item/clothing/suit/storage/labcoat(src)
	new /obj/item/clothing/gloves/black(src)
	new /obj/item/clothing/gloves/black(src)
	new /obj/item/clothing/gloves/black(src)
	new /obj/item/clothing/shoes/black(src)
	new /obj/item/clothing/shoes/black(src)
	new /obj/item/clothing/shoes/black(src)

/obj/structure/closet/wardrobe/bartender_black/New()
	new /obj/item/clothing/under/rank/bartender(src)
	new /obj/item/clothing/under/rank/bartender(src)
	new /obj/item/clothing/under/rank/bartender(src)
	new /obj/item/clothing/shoes/black(src)
	new /obj/item/clothing/shoes/black(src)
	new /obj/item/clothing/shoes/black(src)

/obj/structure/closet/wardrobe/chef_white/New()
	new /obj/item/clothing/under/rank/chef(src)
	new /obj/item/clothing/under/rank/chef(src)
	new /obj/item/clothing/under/rank/chef(src)
	new /obj/item/clothing/suit/storage/chef(src)
	new /obj/item/clothing/suit/storage/chef(src)
	new /obj/item/clothing/suit/storage/chef(src)
	new /obj/item/clothing/head/chefhat(src)
	new /obj/item/clothing/head/chefhat(src)
	new /obj/item/clothing/head/chefhat(src)
	new /obj/item/clothing/shoes/black(src)
	new /obj/item/clothing/shoes/black(src)
	new /obj/item/clothing/shoes/black(src)

/obj/structure/closet/wardrobe/hydro_green/New()
	new /obj/item/clothing/under/rank/hydroponics(src)
	new /obj/item/clothing/under/rank/hydroponics(src)
	new /obj/item/clothing/under/rank/hydroponics(src)
	new /obj/item/clothing/head/helmet/greenbandana(src)
	new /obj/item/clothing/head/helmet/greenbandana(src)
	new /obj/item/clothing/head/helmet/greenbandana(src)
	new /obj/item/clothing/suit/storage/apron(src)
	new /obj/item/clothing/suit/storage/apron(src)
	new /obj/item/clothing/suit/storage/apron(src)
	new /obj/item/clothing/gloves/botanic_leather(src)
	new /obj/item/clothing/gloves/botanic_leather(src)
	new /obj/item/clothing/gloves/botanic_leather(src)
	new /obj/item/clothing/shoes/black(src)
	new /obj/item/clothing/shoes/black(src)
	new /obj/item/clothing/shoes/black(src)

/obj/structure/closet/wardrobe/librarian_red/New()
	new /obj/item/clothing/under/suit_jacket/red(src)
	new /obj/item/clothing/under/suit_jacket/red(src)
	new /obj/item/clothing/under/suit_jacket/red(src)
	new /obj/item/clothing/shoes/black(src)
	new /obj/item/clothing/shoes/black(src)
	new /obj/item/clothing/shoes/black(src)

/obj/structure/closet/wardrobe/cargo_yellow/New()
	new /obj/item/clothing/under/rank/cargo(src)
	new /obj/item/clothing/under/rank/cargo(src)
	new /obj/item/clothing/under/rank/cargo(src)
	new /obj/item/clothing/shoes/black(src)
	new /obj/item/clothing/shoes/black(src)
	new /obj/item/clothing/shoes/black(src)

/obj/structure/closet/wardrobe/qm_yellow/New()
	new /obj/item/clothing/under/rank/cargo(src)
	new /obj/item/clothing/under/rank/cargo(src)
	new /obj/item/clothing/under/rank/cargo(src)
	new /obj/item/clothing/shoes/black(src)
	new /obj/item/clothing/shoes/black(src)
	new /obj/item/clothing/shoes/black(src)
