#!/bin/bash
set -e
# Generate maps
tools/nanomap_renderer/nanomap-renderer minimap --w 2040 --h 2040 "./_maps/map_files/Birdshot/birdshot.dmm"
tools/nanomap_renderer/nanomap-renderer minimap --w 2040 --h 2040 "./_maps/map_files/Deltastation/DeltaStation2.dmm"
tools/nanomap_renderer/nanomap-renderer minimap --w 2040 --h 2040 "./_maps/map_files/IceBoxStation/IceBoxStation.dmm"
tools/nanomap_renderer/nanomap-renderer minimap --w 2040 --h 2040 "./_maps/map_files/MetaStation/MetaStation.dmm"
tools/nanomap_renderer/nanomap-renderer minimap --w 2040 --h 2040 "./_maps/map_files/NorthStar/north_star.dmm"
tools/nanomap_renderer/nanomap-renderer minimap --w 2040 --h 2040 "./_maps/map_files/tramstation/tramstation.dmm"
tools/nanomap_renderer/nanomap-renderer minimap --w 2040 --h 2040 "./_maps/map_files/wawastation/wawastation.dmm"
tools/nanomap_renderer/nanomap-renderer minimap --w 2040 --h 2040 "./_maps/map_files/Mining/Lavaland.dmm"
# Move and rename files so the game understands them
cd "data/minimaps"
mv "birdshot-1.png" "Birdshot Station_nanomap_z1.png"
mv "DeltaStation2-1.png" "Delta Station_nanomap_z1.png"
mv "IceBoxStation-1.png" "Ice Box Station_nanomap_z1.png"
mv "IceBoxStation-2.png" "Ice Box Station_nanomap_z2.png"
mv "IceBoxStation-3.png" "Ice Box Station_nanomap_z3.png"
mv "MetaStation-1.png" "MetaStation_nanomap_z1.png"
mv "north_star-1.png" "NorthStar_nanomap_z1.png"
mv "north_star-2.png" "NorthStar_nanomap_z2.png"
mv "north_star-3.png" "NorthStar_nanomap_z3.png"
mv "north_star-4.png" "NorthStar_nanomap_z4.png"
mv "tramstation-1.png" "Tramstation_nanomap_z1.png"
mv "tramstation-2.png" "Tramstation_nanomap_z2.png"
mv "wawastation-1.png" "Wawastation_nanomap_z1.png"
mv "wawastation-2.png" "Wawastation_nanomap_z2.png"
mv "Lavaland-1.png" "Lavaland_nanomap_z1.png"
cd "../../"
cp "data/minimaps/Birdshot Station_nanomap_z1.png" "icons/_nanomaps"
cp "data/minimaps/Delta Station_nanomap_z1.png" "icons/_nanomaps"
cp "data/minimaps/Ice Box Station_nanomap_z1.png" "icons/_nanomaps"
cp "data/minimaps/Ice Box Station_nanomap_z2.png" "icons/_nanomaps"
cp "data/minimaps/Ice Box Station_nanomap_z3.png" "icons/_nanomaps"
cp "data/minimaps/MetaStation_nanomap_z1.png" "icons/_nanomaps"
cp "data/minimaps/NorthStar_nanomap_z1.png" "icons/_nanomaps"
cp "data/minimaps/NorthStar_nanomap_z2.png" "icons/_nanomaps"
cp "data/minimaps/NorthStar_nanomap_z3.png" "icons/_nanomaps"
cp "data/minimaps/NorthStar_nanomap_z4.png" "icons/_nanomaps"
cp "data/minimaps/Tramstation_nanomap_z1.png" "icons/_nanomaps"
cp "data/minimaps/Tramstation_nanomap_z2.png" "icons/_nanomaps"
cp "data/minimaps/Wawastation_nanomap_z1.png" "icons/_nanomaps"
cp "data/minimaps/Wawastation_nanomap_z2.png" "icons/_nanomaps"
cp "data/minimaps/Lavaland_nanomap_z1.png" "icons/_nanomaps"
