#define SECHUD_BLUESHIELD "hudblueshield"
#define SECHUD_NANOTRASEN_REPRESENTATIVE "hudnanotrasen_representative"
#define SECHUD_MAGISTARTE "hudmagistrate"
#define SECHUD_EXPLORER "hudexplorer"
#define SECHUD_TSF "hudtsf"
#define SECHUD_USSP "hudussp"
