/mob/living/silicon/robot/keyDown(_key, client/user)
	switch(_key)
		if("1", "2", "3")
			cmd_toggle_module(text2num(key))
		if("4")
			a_intent_change("left")
		if("q", "numpad7", "northwest")
			cmd_unequip_module()
	..()