/mob/living/silicon/hivebot/examine(mob/user)
	to_chat(user, "<span class='notice'>*---------*</span>")
	to_chat(user, text("<span class='notice'>This is \icon[src] <B>[src.name]</B>!</span>"))
	if (src.stat == 2)
		to_chat(user, text("<span class='warning'>[src.name] is powered-down.</span>"))
	if (src.getBruteLoss())
		if (src.getBruteLoss() < 75)
			to_chat(user, text("<span class='warning'>[src.name] looks slightly dented</span>"))
		else
			to_chat(user, text("<span class='danger'>[src.name] looks severely dented!</span>"))
	if (src.getFireLoss())
		if (src.getFireLoss() < 75)
			to_chat(user, text("<span class='warning'>[src.name] looks slightly burnt!</span>"))
		else
			to_chat(user, text("<span class='danger'>[src.name] looks severely burnt!</span>"))
	if (src.stat == 1)
		to_chat(user, text("<span class='warning'>[src.name] doesn't seem to be responding.</span>"))
