#define COMSIG_MOB_STOP_HUNGER "stop_hunger_mob"
#define COMSIG_MOB_START_HUNGER "start_hunger_mob"
#define COMSIG_MOB_FEED "feed_hunger_mob"
#define COMSIG_MOB_FED_ON "fed_on_mob"
#define COMSIG_MOB_RETURN_HUNGER "return_hunger_mob"
#define COMSIG_MOB_REFUSED_EAT "refused_hunger_mob"
#define COMSIG_MOB_OVERATE "overate_hunger_mob"
#define COMSIG_MOB_EAT_NORMAL "normal_eat_hunger_mob"
#define COMSIG_MOB_STARVING "starving_hunger_mob"
#define COMSIG_MOB_FULLY_STARVING "full_starve_hunger_mob"
#define COMSIG_SECRETION_UPDATE "secretion_update"
#define COMSIG_FEEDING_CHECK "latch_check"
#define COMSIG_HUNGER_UPDATED "update_hunger_mob"
#define COMSIG_LIVING_ATE "living_ate_object"
#define COMSIG_MOB_ADJUST_HUNGER "adjust_hunger_mob"

#define COMSIG_EMOTION_STORE "store_emotion"
#define EMOTION_BUFFER_SPEAK_FROM_BUFFER "release_emotion"
#define COMSIG_EMOTION_HEARD "heard_emotion"
#define EMOTION_BUFFER_UPDATE_OVERLAY_STATES "update_emotion_overlay"

#define COMSIG_ATOM_JOIN_STACK "join_stack"
#define COMSIG_STACK_MOVE "stack_move"
#define COMSIG_CHECK_CAN_ADD_NEW_STACK "check_stack_add"
#define COMSIG_MOBSTACKER_DESTROY "mobstack_destroy_stack"
