// AuStation includes file
#include "code\controllers\configuration\entries\game_options.dm"
#include "code\controllers\configuration\entries\general.dm"
#include "code\controllers\subsystem\autotransfer.dm"
#include "code\controllers\subsystem\autosandbox.dm"
#include "code\datums\ai_laws.dm"
#include "code\game\objects\items\AI_modules.dm"
#include "code\game\objects\items\robot\robot_upgrades.dm"
#include "code\modules\food_and_drinks\drinks\drinks.dm"
#include "code\modules\reagents\chemistry\reagents\other_reagents.dm"
#include "code\modules\reagents\chemistry\recipes\others.dm"
#include "code\modules\reagents\reagent_containers\bottle.dm"
#include "code\modules\research\designs\AI_module_designs.dm"
#include "code\modules\research\designs\mechfabricator_designs.dm"
