// AuStation includes file. Add all modularized code files here.

#include "code\datums\diseases\tuberculosis.dm"
#include "code\game\machinery\Sleeper.dm"
#include "code\game\objects\items\stacks\medical.dm"
#include "code\game\objects\items\storage\firstaid.dm"
#include "code\modules\food_and_drinks\food\snacks_other.dm"
#include "code\modules\food_and_drinks\kitchen_machinery\smartfridge.dm"
#include "code\modules\hydroponics\grown\ambrosia.dm"
#include "code\modules\hydroponics\grown\berries.dm"
#include "code\modules\hydroponics\grown\flowers.dm"
#include "code\modules\hydroponics\grown\kudzu.dm"
#include "code\modules\hydroponics\grown\mushrooms.dm"
#include "code\modules\reagents\chemistry\reagents\medicine_reagents.dm"
#include "code\modules\reagents\chemistry\recipes\medicine.dm"
#include "code\modules\reagents\chemistry\recipes\others.dm"
#include "code\modules\reagents\chemistry\recipes\pyrotechnics.dm"
#include "code\modules\reagents\chemistry\recipes\toxins.dm"
#include "code\modules\reagents\reagent_containers\bottle.dm"
#include "code\modules\reagents\reagent_containers\glass.dm"
#include "code\modules\reagents\reagent_containers\medigel.dm"
#include "code\modules\reagents\reagent_containers\patch.dm"
#include "code\modules\reagents\reagent_containers\pill.dm"
#include "code\modules\reagents\reagent_containers\syringes.dm"
#include "code\modules\research\designs\limbgrower_designs.dm"
#include "code\modules\research\designs\machine_designs.dm"
#include "code\modules\vending\medical.dm"
#include "code\modules\vending\medical_wall.dm"
