# Bitmask restoration! (Corners)
# Allows for easy mass extraction of template pngs and their configs from a dmi
# Use this if you have a dmi and you want a cutter config you can edit easily
# Of note, while it tries its best it is nowhere near perfect. We don't parity check against the existing dmi
# And we also do not account for overrided states very well
# Always double check (and be aware that dmi is weird so you may get diffs of 1 rgb value when doin this)
mode = "BitmaskSliceReconstruct"
# List of icon states to pull out, expanded to get the standard ordering for diagonals
extract = [
    "0", "3", "12", "15", "255",
    "6-diagonal", "10-diagonal", "5-diagonal", "9-diagonal",
    "38-diagonal", "74-diagonal", "21-diagonal", "137-diagonal"
]

# Map of name -> state that will be encoded into a positions list later
# Lets you extract particular states and use them to fill in for states later
# Useful to carry over odd snowflake states
#[bespoke]

# Map of key -> value to set on the created config
# Lets you set arbitrary values on the created config, mostly useful for batch processing
# IMPORTANT NOTE: We sort of assume you'll setup a default template here (since this is for batch processing),
# so if things work odd that's likely why
#[set]
#template = "\"bitmask/diagonal_corner_32x32\""
