/**
 * Master record of NtOS programs.
 */
export const NtOS = {
  "NtosAiRestorer": "./NtOS/interfaces/AiRestorer.js",
  "NtosArcade": "./NtOS/interfaces/Arcade.js",
  "NtosBountyBoard": "./NtOS/interfaces/BountyBoard.js",
  "NtosCard": "./NtOS/interfaces/Card.js",
  "NtosCargo": "./NtOS/interfaces/Cargo.js",
  "NtosConfiguration": "./NtOS/interfaces/Configuration.js",
  "NtosCrewManifest": "./NtOS/interfaces/CrewManifest.js",
  "NtosCyborgRemoteMonitor": "./NtOS/interfaces/CyborgRemoteMonitor.js",
  "NtosFileManager": "./NtOS/interfaces/FileManager.js",
  "NtosGasAnalyzer": "./NtOS/interfaces/GasAnalyzer.js",
  "NtosJobManager": "./NtOS/interfaces/JobManager.js",
  "NtosMain": "./NtOS/interfaces/Main.js",
  "NtosMessenger": "./NtOS/interfaces/Messenger.js",
  "NtosNetChat": "./NtOS/interfaces/NetChat.js",
  "NtosNetDos": "./NtOS/interfaces/NetDos.js",
  "NtosNetDownloader": "./NtOS/interfaces/NetDownloader.js",
  "NtosNetMonitor": "./NtOS/interfaces/NetMonitor.js",
  "NtosNewscaster": "./NtOS/interfaces/Newscaster.js",
  "NtosNotepad": "./NtOS/interfaces/Notepad.js",
  "NtosPhysScanner": "./NtOS/interfaces/PhysScanner.js",
  "NtosPortraitPrinter": "./NtOS/interfaces/PortraitPrinter.js",
  "NtosPowerMonitor": "./NtOS/interfaces/PowerMonitor.js",
  "NtosRadar": "./NtOS/interfaces/Radar.js",
  "NtosRecords": "./NtOS/interfaces/Records.js",
  "NtosRevelation": "./NtOS/interfaces/Revelation.js",
  "NtosRoboControl": "./NtOS/interfaces/RoboControl.js",
  "NtosRobotact": "./NtOS/interfaces/Robotact.js",
  "NtosScipaper": "./NtOS/interfaces/Scipaper.js",
  "NtosSecurEye": "./NtOS/interfaces/SecurEye.js",
  "NtosShipping": "./NtOS/interfaces/Shipping.js",
  "NtosSignaler": "./NtOS/interfaces/Signaler.js",
  "NtosSkillTracker": "./NtOS/interfaces/SkillTracker.js",
  "NtosStationAlertConsole": "./NtOS/interfaces/StationAlertConsole.js",
  "NtosStatus": "./NtOS/interfaces/Status.js",
  "NtosSupermatterMonitor": "./NtOS/interfaces/SupermatterMonitor.js",
  "NtosTechweb": "./NtOS/interfaces/Techweb.js",
};
