Name = "CC_NanoTrasen" #The name he uses to connect
no_absolute_paths = True
debug_on = False
SName = ["cc","nt","trasen","nano","nanotrasen"] #Other names he will respond to
DISABLE_ALL_NON_MANDATORY_SOCKET_CONNECTIONS = False
directory = "c:/cc_nt/bot/" # Directory the bot is located in, make sure to keep the "/" at the end
version = "TG CC-BY-SA 6"
Network = 'irc.rizon.net' #e.g. "irc.rizon.net"
channel = "#italiano" #what channel you want the bot in
channels = ["#italiano"] #same as above
greeting = "Welcome!" #what he says when a person he hasn't seen before joins
prefix = "!" #prefix for bot commands
Port = 7000
