#define INTERACT_DROP "Drop"
#define INTERACT_USE "Use"
#define INTERACT_THROW "Throw"

#define TAKE_ITEMS 1
#define TAKE_CLOSETS 2
#define TAKE_HUMANS 3

#define MIN_SPEED_MULTIPLIER_TIER_1 0.5
#define MIN_SPEED_MULTIPLIER_TIER_2 0.4
#define MIN_SPEED_MULTIPLIER_TIER_3 0.3
#define MIN_SPEED_MULTIPLIER_TIER_4 0.1

#define MAX_SPEED_MULTIPLIER_TIER_1 2
#define MAX_SPEED_MULTIPLIER_TIER_2 3
#define MAX_SPEED_MULTIPLIER_TIER_3 5
#define MAX_SPEED_MULTIPLIER_TIER_4 6

#define MAX_INTERACTION_POINTS_TIER_1 2
#define MAX_INTERACTION_POINTS_TIER_2 3
#define MAX_INTERACTION_POINTS_TIER_3 4
#define MAX_INTERACTION_POINTS_TIER_4 6

#define CURRENT_TASK_NONE "NO TASK" // manipulator is off
#define CURRENT_TASK_IDLE "IDLE" // manipulator is skipping a cycle because it has nothing to do
#define CURRENT_TASK_MOVING_PICKUP "MOVING TO PICKUP POINT"
#define CURRENT_TASK_MOVING_DROPOFF "MOVING TO DROPOFF POINT"
#define CURRENT_TASK_INTERACTING "INTERACTING"
#define CURRENT_TASK_STOPPING "STOPPING"

#define WORKER_SINGLE_USE "Single Time Use"
#define WORKER_EMPTY_USE "Empty Hand Use"
#define WORKER_NORMAL_USE "Normal Use"

#define TASKING_ROUND_ROBIN "Round Robin" // 1 - 2 - 3 - 2 - 3
#define TASKING_STRICT_ROBIN "Strict Robin" // 1 - 2 - 3 - (waiting for 1) - 1 - 2
#define TASKING_PREFER_FIRST "Prefer First" // 1 - 2 - 1 - 2 - 3 - 2 - 1 - 3 (first availiable)

#define TRANSFER_TYPE_PICKUP "Pick Up"
#define TRANSFER_TYPE_DROPOFF "Drop Off"

#define BASE_POWER_USAGE 0.2
#define BASE_INTERACTION_TIME 0.3 SECONDS

#define STARTING_MULTIPLIER 5
#define MAX_MULTIPLIER 10

#define CYCLE_SKIP_TIMEOUT 1 SECONDS

#define POINT_OVERFLOW_ALLOWED "ALLOW"
#define POINT_OVERFLOW_FILTERS "TO FILTERS"
#define POINT_OVERFLOW_HELD "TO HELD"
#define POINT_OVERFLOW_FORBIDDEN "FORBID"

#define POST_INTERACTION_DROP_AT_POINT "DROP AT DROPOFF"
#define POST_INTERACTION_DROP_AT_MACHINE "DROP AT MACHINE"
#define POST_INTERACTION_DROP_NEXT_FITTING "DROP AT FITTING"
