#define MIN_REAGENT_VOL 0.005 // The minimum volume of a reagent. Default is 5mU. Used to prevent volumes becoming equal to 1.73e-06 units.

// The big ol' list for defining reagent id's. Sort alphabetically, and by the file the reagent is defined in please.
// Naming sceme of defines: RID_definename where definename is lowercase and representative of the id, but still short enough that it's faster to use than types are.
// "actualid" preferably the same as the definename. But can be longer and more descriptive if necessary.
// As a general rule, if the definename is long enough that it displaces the tab formatting, then it's too long.

// alcohol_reagents.dm //

#define RID_absinthe 	"absinthe"
#define RID_acidspit	"acidspit"
#define RID_ale 		"ale"
#define RID_alliescock	"alliescocktail"
#define RID_aloe		"aloe"
#define RID_amasec		"amasec"
#define RID_andalusia	"andalusia"
#define RID_antifreeze	"antifreeze"
#define RID_b52			"bf2"
#define RID_bacchus		"bacchus_blessing"
#define RID_bahama_mama	"bahama_mama"
#define RID_bananahonk	"bananahonk"
#define RID_barefoot	"barefoot"
#define RID_bpskysmsh	"beepskysmash"
#define RID_beer		"beer"
#define RID_bilk		"bilk"
#define RID_blckruss	"blackrussian"
#define RID_bloodymary	"bloodymary"
#define RID_booger		"booger"
#define RID_bravebull	"bravebull"
#define RID_changesting	"changelingsting"
#define RID_cognac		"cognac"
#define RID_cubalibre	"cubalibre"
#define RID_demonsblood	"demonsblood"
#define RID_devilskiss	"devilskiss"
#define RID_drymartini	"driestmartini"
#define RID_drunkblump	"drunkenblumpkin"
#define RID_erikasrprse	"erikasurprise"
#define RID_ethanol		"ethanol"
#define RID_fetchfizz	"fetching_fizz"
#define RID_gin			"gin"
#define RID_ginfizz		"ginfizz"
#define RID_gintonic	"gintonic"
#define RID_goldschlagr "goldschlager"
#define RID_grappa		"grappa"
#define RID_greenbeer	"greenbeer"
#define RID_grog		"grog"
#define RID_hcider		"hcider"
#define RID_heartpunch	"hearty_punch"
#define RID_hooch		"hooch"
#define RID_iced_beer	"iced_beer"
#define RID_irishcarbmb "irishcarbomb"
#define RID_irishcoffee	"irishcoffee"
#define RID_irishcream	"irishcream"
#define RID_kahlua		"kahlua"
#define RID_lizardwine	"lizardwine"
#define RID_longisland	"longislandicedtea"
#define RID_manhattan	"manhattan"
#define RID_manhatproj	"manhattan_proj"
#define RID_manlydorf	"manlydorf"
#define RID_margarita	"margarita"
#define RID_martini		"martini"
#define RID_mead		"mead"
#define RID_moonshine	"moonshine"
#define RID_patron		"patron"
#define RID_red_mead	"red_mead"
#define RID_rum			"rum"
#define RID_sbiten		"sbiten"
#define RID_screwdriver	"screwdriver"
#define RID_silencer	"silencer"
#define RID_singulo		"singulo"
#define RID_snowwhite	"snowwhite"
#define RID_syndibomb	"syndicatebomb"
#define RID_tequila		"tequila"
#define RID_tequilasun	"tequilasunrise"
#define RID_thirtenloko "thirteenloko"
#define RID_threeisland	"threemileisland"
#define RID_toxinsspec	"toxinsspecial"
#define RID_vermouth	"vermouth"
#define RID_vodka		"vodka"
#define RID_vodkamartin "vodkamartini"
#define RID_vodkatonic	"vodkatonic"
#define RID_whiskey		"whiskey"
#define RID_whiskeysour	"whiskey_sour"
#define RID_whiskeycola	"whiskeycola"
#define RID_whiskeysoda	"whiskeysoda"
#define RID_whiteruss	"whiterussian"
#define RID_wine		"wine"

// blob_reagents.dm //

