
#define WASTELAND		(1<<0)

#define WASTELANDER		(1<<0)
#define RAIDER			(1<<1)

#define VAULT			(1<<1)

#define OVERSEER		(1<<0)
#define DWELLER			(1<<1)

#define JOB_DISPLAY_ORDER_WASTELANDER 1
#define JOB_DISPLAY_ORDER_RAIDER 2
#define JOB_DISPLAY_ORDER_OVERSEER 3
#define JOB_DISPLAY_ORDER_DWELLER 4