import { Food } from '../PreferencesMenu/types';

export const TYPE_ICONS = {
  'Can Make': 'utensils',
  [Food.Alcohol]: 'wine-glass',
  [Food.Breakfast]: 'sun',
  [Food.Bugs]: 'bug',
  [Food.Cloth]: 'tshirt',
  [Food.Dairy]: 'cheese',
  [Food.Egg]: 'egg',
  [Food.Fried]: 'fire',
  [Food.Fruit]: 'apple-alt',
  [Food.Gore]: 'skull',
  [Food.Grain]: 'wheat-awn',
  [Food.Gross]: 'trash',
  [Food.Junkfood]: 'pizza-slice',
  [Food.Meat]: 'bacon',
  [Food.Nuts]: 'seedling',
  [Food.Oranges]: 'apple-alt',
  [Food.Pineapple]: 'apple-alt',
  [Food.Raw]: 'drumstick-bite',
  [Food.Seafood]: 'fish',
  [Food.Stone]: 'gem',
  [Food.Sugar]: 'candy-cane',
  [Food.Toxic]: 'biohazard',
  [Food.Vegetables]: 'carrot',
} as const;

export const CATEGORY_ICONS_CRAFTING = {
  'Can Make': 'hammer',
  'Weapons Melee': 'hand-fist',
  'Weapons Ranged': 'gun',
  'Weapon Ammo': 'box',
  Robotics: 'robot',
  Misc: 'shapes',
  Tribal: 'campground',
  Clothing: 'shirt',
  Drinks: 'wine-bottle',
  Chemistry: 'microscope',
  Atmospherics: 'fan',
  Structures: 'cube',
  Tiles: 'border-all',
  Windows: 'person-through-window',
  Doors: 'door-open',
  Furniture: 'chair',
  Equipment: 'calculator',
  Containers: 'briefcase',
  Tools: 'screwdriver-wrench',
  Entertainment: 'masks-theater',
  'Blood Cult': 'users',
} as const;

export const CATEGORY_ICONS_COOKING = {
  'Can Make': 'utensils',
  Appetizer: 'bread-slice',
  Bread: 'bread-slice',
  Burger: 'burger',
  Burrito: 'circle-o',
  Cake: 'cake-candles',
  Candy: 'candy-cane',
  Component: 'cubes',
  Cookie: 'cookie',
  Dessert: 'face-grin-beam-sweat',
  Frozen: 'ice-cream',
  Italian: 'pizza-slice',
  Japanese: 'earth-asia',
  Lizard: 'dragon',
  Martian: 'globe',
  Meat: 'bacon',
  Mexican: 'earth-americas',
  Mothic: 'shirt',
  Noodles: 'wheat-awn',
  Pastry: 'cookie',
  Pie: 'chart-pie',
  Pizza: 'pizza-slice',
  Rice: 'bowl-rice',
  Salad: 'leaf',
  Sandwich: 'hotdog',
  Soup: 'mug-hot',
  Sushi: 'fish',
  Taco: 'circle-o',
  Terran: 'earth-europe',
  Uncategorized: 'shapes',
  'Main Course': 'drumstick-bite',
  Breakfast: 'sun',
  Snack: 'compress',
  Condiment: 'bottle-water',
} as const;
