/datum/asset/simple/inventory
	assets = list(
		"inventory-glasses.png" = 'icons/ui_icons/inventory/glasses.png',
		"inventory-head.png" = 'icons/ui_icons/inventory/head.png',
		"inventory-neck.png" = 'icons/ui_icons/inventory/neck.png',
		"inventory-mask.png" = 'icons/ui_icons/inventory/mask.png',
		"inventory-ears.png" = 'icons/ui_icons/inventory/ears.png',
		"inventory-uniform.png" = 'icons/ui_icons/inventory/uniform.png',
		"inventory-suit.png" = 'icons/ui_icons/inventory/suit.png',
		"inventory-gloves.png" = 'icons/ui_icons/inventory/gloves.png',
		"inventory-hand_l.png" = 'icons/ui_icons/inventory/hand_l.png',
		"inventory-hand_r.png" = 'icons/ui_icons/inventory/hand_r.png',
		"inventory-shoes.png" = 'icons/ui_icons/inventory/shoes.png',
		"inventory-suit_storage.png" = 'icons/ui_icons/inventory/suit_storage.png',
		"inventory-id.png" = 'icons/ui_icons/inventory/id.png',
		"inventory-belt.png" = 'icons/ui_icons/inventory/belt.png',
		"inventory-back.png" = 'icons/ui_icons/inventory/back.png',
		"inventory-pocket.png" = 'icons/ui_icons/inventory/pocket.png',
		"inventory-collar.png" = 'icons/ui_icons/inventory/collar.png',
	)
