/datum/asset/spritesheet/simple/patches
	name = "patches"
	assets = list(
		"bandaid_1" = 'icons/ui/patches/bandaid_1.png',
		"bandaid_2" = 'icons/ui/patches/bandaid_2.png',
		"bandaid_3" = 'icons/ui/patches/bandaid_3.png',
		"bandaid_4" = 'icons/ui/patches/bandaid_4.png',
		"bandaid_blank" = 'icons/ui/patches/bandaid_blank.png',
		"bandaid_both" = 'icons/ui/patches/bandaid_both.png',
		"bandaid_brute" = 'icons/ui/patches/bandaid_brute.png',
		"bandaid_brute_2" = 'icons/ui/patches/bandaid_brute_2.png',
		"bandaid_burn" = 'icons/ui/patches/bandaid_burn.png',
		"bandaid_burn_2" = 'icons/ui/patches/bandaid_burn_2.png',
		"bandaid_clown" = 'icons/ui/patches/bandaid_clown.png',
		"bandaid_colonthree" = 'icons/ui/patches/bandaid_colonthree.png',
		"bandaid_exclaimationpoint" = 'icons/ui/patches/bandaid_exclaimationpoint.png',
		"bandaid_mix" = 'icons/ui/patches/bandaid_mix.png',
		"bandaid_monke" = 'icons/ui/patches/bandaid_monke.png',
		"bandaid_msic" = 'icons/ui/patches/bandaid_msic.png',
		"bandaid_questionmark" = 'icons/ui/patches/bandaid_questionmark.png',
		"bandaid_suffocation" = 'icons/ui/patches/bandaid_suffocation.png',
		"bandaid_suffocation_2" = 'icons/ui/patches/bandaid_suffocation_2.png',
		"bandaid_toxin" = 'icons/ui/patches/bandaid_toxin.png',
		"bandaid_toxin_2" = 'icons/ui/patches/bandaid_toxin_2.png',
	)
