#define BB_CHICKEN_RECRUIT_COOLDOWN "BB_chicken_cooldown"
#define BB_CHICKEN_SELF_ABILITY "BB_chicken_ability"
#define BB_CHICKEN_TARGETED_ABILITY "BB_chicken_targeted_ability"
#define BB_CHICKEN_SPECALITY_ABILITY "BB_chicken_special_ability"
#define BB_CHICKEN_LAY_EGG "BB_chicken_lay_egg"
#define BB_CHICKEN_NESTING_BOX "BB_chicken_lay_target"
#define BB_CHICKEN_FEED "BB_chicken_feed_ability"

///gary defines
#define BB_GARY_HIDEOUT "BB_gary_hideout"
#define BB_GARY_HIDEOUT_SETTING_UP "BB_gary_hideout_setting_up"
#define BB_GARY_TARGET_AREA "BB_gary_target"
#define BB_GARY_BARTERING "BB_gary_bartering"
#define BB_GARY_COME_HOME "BB_gary_come_home"
#define BB_GARY_HAS_SHINY "BB_gary_has_shiny"
#define BB_GARY_BARTER_TARGET "BB_gary_barter_target"
#define BB_GARY_BARTER_ITEM "BB_gary_barter_item"
#define BB_GARY_BARTER_STEP "BB_gary_barter_step"
#define BB_GARY_WANDER_COOLDOWN "BB_gary_wander_cooldown"
