#define BB_CHICKEN_AGGRESSIVE "BB_chicken_aggressive"
#define BB_CHICKEN_RETALIATE "BB_chicken_retaliate"
#define BB_CHICKEN_SHITLIST "BB_chicken_shitlist"
#define BB_CHICKEN_RECRUIT_COOLDOWN "BB_chicken_cooldown"
#define BB_CHICKEN_CURRENT_ATTACK_TARGET "BB_chicken_target"
#define BB_CHICKEN_ABILITY "BB_chicken_ability"
#define BB_CHICKEN_PROJECTILE "BB_chicken_projectile"
#define BB_CHICKEN_COMBAT_ABILITY "BB_chicken_combat_ability"
#define BB_CHICKEN_ABILITY_COOLDOWN "BB_chicken_ability_cooldown"
#define BB_CHICKEN_SHOOT_PROB "BB_chicken_shoot_prob"
#define BB_CHICKEN_HONKS_SORROW "BB_chicken_honks_sorrow"
#define BB_CHICKEN_SPECALITY_ABILITY "BB_chicken_special_ability"
#define BB_CHICKEN_CURRENT_LEADER "BB_chicken_leader"
#define BB_CHICKEN_READY_LAY "BB_chicken_ready_lay"
#define BB_CHICKEN_ATTEMPT_TRACKING "BB_chicken_attempt_tracking"

///gary defines
#define BB_GARY_HIDEOUT "BB_gary_hideout"
#define BB_GARY_HIDEOUT_SETTING_UP "BB_gary_hideout_setting_up"
#define BB_GARY_TARGET_AREA "BB_gary_target"
#define BB_GARY_BARTERING "BB_gary_bartering"
#define BB_GARY_BARTER_FRIEND "BB_gary_barter_friend"
#define BB_GARY_COME_HOME "BB_gary_come_home"
#define BB_GARY_HAS_SHINY "BB_gary_has_shiny"
