#define MATERIAL_STACK (1<<0)

#define MATERIAL_TRACK_NO_STACK_PROCESS (1<<0)


#define COMSIG_CLIENT_CLICK_DIRTY "client_dirty_click"


#define CLICK_CD_BULKY_WEAPON 24
#define CLICK_CD_LARGE_WEAPON 16
#define CLICK_CD_LIGHT_WEAPON 12
