# Renders the diffs and uploads them to filehouse
name: Behavior tree diff

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "**/*.bt.json"

permissions:
  contents: read
  pull-requests: read

jobs:
  render:
    name: Render behavior tree diffs
    runs-on: ubuntu-24.04
    steps:
      - name: Render diffs
        uses: tgstation/BehaviorTreeG@main
        with:
          mode: render
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload rendered diffs
        uses: actions/upload-artifact@v7
        with:
          name: bt-diff
          path: bt-diff-out
          if-no-files-found: ignore
