name: Codeowner Reviews

# Controls when the workflow will run
on:
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  assign-users:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so the job can access it
      - uses: actions/checkout@v7

     #Request reviews
      - name: Request reviews
        uses: tgstation/code-reviewers@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
