name: Compare Screenshots

on:
  workflow_call:

jobs:
  compare_screenshots:
    timeout-minutes: 15
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
      - name: Setup directory
        run: mkdir -p artifacts
      # If we ever add more artifacts, this is going to break, but it'll be obvious.
      - name: Download screenshot tests
        uses: actions/download-artifact@v5
        with:
          path: artifacts
      - name: ls -R
        run: ls -R artifacts
      - name: Setup screenshot comparison
        run: npm i
        working-directory: tools/screenshot-test-comparison
      - name: Run screenshot comparison
        run: node tools/screenshot-test-comparison/index.js artifacts code/modules/unit_tests/screenshots artifacts/screenshot_comparisons
      # workflow_run does not give you the PR it ran on,
      # even through the thing literally named "matching pull requests".
      # However, in GraphQL, you can check if the check suite was ran
      # by a specific PR, so trusting the (user controlled) action here is okay,
      # as long as we check it later in show_screenshot_test_results
      - name: Save PR ID
        if: failure() && github.event.pull_request
        run: |
          echo ${{ github.event.pull_request.number }} > artifacts/screenshot_comparisons/pull_request_number.txt
      - name: Upload bad screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: bad-screenshots
          path: artifacts/screenshot_comparisons
