name: Mark stale issues and pull requests

on:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read

jobs:
  stale:
    permissions:
      issues: write # for actions/stale to close stale issues
      pull-requests: write # for actions/stale to close stale PRs
    runs-on: ubuntu-24.04
    outputs:
      staled_prs: ${{ steps.filter-prs.outputs.result }}

    steps:
      - name: Mark stale issues and pull requests
        uses: actions/stale@v10
        id: stale
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-pr-message: "Данный PR считается устаревшим, так как не обновлялся достаточно долгое время. Это означает, что он будет автоматически закрыт в течении 7 дней. Если это ошибка и PR в разработке, то сообщите об этом @Ревьювер в Discord." # NEMESIS EDIT CHANGE - localization
          close-pr-message: "Этот PR не получил обновлений после того, как был помечен как устаревший, и поэтому автоматически закрыт. Вы можете переоткрыть этот PR или создать новый, когда у вас появятся новые обновления." # NEMESIS EDIT CHANGE - localization
          days-before-stale: 14 # NEMESIS EDIT CHANGE - ORIGINAL: days-before-stale: 7
          days-before-close: 7
          days-before-issue-stale: 14
          days-before-issue-close: 14
          stale-pr-label: "Stale"
          stale-issue-label: "Stale"
          any-of-issue-labels: "Cleanup Flagged,🤖 Flaky Test Report"
          remove-issue-stale-when-updated: false
          exempt-issue-labels: "Не закрывать"
          exempt-pr-labels: "Не закрывать,Хороший первый PR,Upstream PR Merged,Stale-b-gone,Test Merged" # NOVA EDIT CHANGE - ORIGINAL: exempt-pr-labels: "RED LABEL,Good First PR"
          operations-per-run: 300
      - name: Filter staled pull requests for announcement
        id: filter-prs
        uses: actions/github-script@v9
        env:
          input: ${{steps.stale.outputs.staled-issues-prs}}
        with:
          script: |
            return JSON.parse(process.env.input)
                       .filter(issue => !!issue.pull_request)
                       .map(pr => ({
                        title: pr.title,
                        number: pr.number,
                        html_url: pr.pull_request.html_url,
                       }));

  announce:
    runs-on: ubuntu-24.04
    needs: stale
    if: ${{ needs.stale.outputs.staled_prs != '[]' }}
    strategy:
      matrix:
        pull_request: ${{ fromJSON(needs.stale.outputs.staled_prs) }}
    steps:
      - name: "Check for DISCORD_WEBHOOK"
        id: secrets_set
        env:
          ENABLER_SECRET: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          unset SECRET_EXISTS
          if [ -n "$ENABLER_SECRET" ]; then SECRET_EXISTS=true ; fi
          echo "SECRETS_ENABLED=$SECRET_EXISTS" >> $GITHUB_OUTPUT
      - name: Send Discord notification
        uses: tgstation/discord-notify@main
        if: >
          steps.secrets_set.outputs.SECRETS_ENABLED
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          title: ${{ matrix.pull_request.title }}
          message: ${{ format('**PR \#{0} автоматически помечается как устаревший.**', matrix.pull_request.number) }} # NEMESIS EDIT CHANGE - localization
          include_image: false
          show_author: false
          avatar_url: https://avatars.githubusercontent.com/u/1363778?s=200&v=4
          username: GitHub
          title_url: "${{ matrix.pull_request.html_url }}"
