	//Plasma fusion properties
#define PLASMA_BINDING_ENERGY_HIPPIE			6000000000000//this has to be a big number
#define PLASMA_FUSION_ENERGY_HIPPIE             999999
#define MAX_CARBON_EFFICENCY_HIPPIE				9
#define PLASMA_FUSED_COEFFICENT_HIPPIE			10
#define CARBON_CATALYST_COEFFICENT_HIPPIE		0.1
#define FUSION_PURITY_THRESHOLD_HIPPIE			0.9